package canon

// Code generated by github.com/tinylib/msgp DO NOT EDIT.

import (
	"github.com/tinylib/msgp/msgp"
)

// DecodeMsg implements msgp.Decodable
func (z *CIExposureTime) DecodeMsg(dc *msgp.Reader) (err error) {
	{
		var zb0001 float32
		zb0001, err = dc.ReadFloat32()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		(*z) = CIExposureTime(zb0001)
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z CIExposureTime) EncodeMsg(en *msgp.Writer) (err error) {
	err = en.WriteFloat32(float32(z))
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z CIExposureTime) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	o = msgp.AppendFloat32(o, float32(z))
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *CIExposureTime) UnmarshalMsg(bts []byte) (o []byte, err error) {
	{
		var zb0001 float32
		zb0001, bts, err = msgp.ReadFloat32Bytes(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		(*z) = CIExposureTime(zb0001)
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z CIExposureTime) Msgsize() (s int) {
	s = msgp.Float32Size
	return
}

// DecodeMsg implements msgp.Decodable
func (z *CIFocalLength) DecodeMsg(dc *msgp.Reader) (err error) {
	{
		var zb0001 uint16
		zb0001, err = dc.ReadUint16()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		(*z) = CIFocalLength(zb0001)
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z CIFocalLength) EncodeMsg(en *msgp.Writer) (err error) {
	err = en.WriteUint16(uint16(z))
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z CIFocalLength) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	o = msgp.AppendUint16(o, uint16(z))
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *CIFocalLength) UnmarshalMsg(bts []byte) (o []byte, err error) {
	{
		var zb0001 uint16
		zb0001, bts, err = msgp.ReadUint16Bytes(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		(*z) = CIFocalLength(zb0001)
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z CIFocalLength) Msgsize() (s int) {
	s = msgp.Uint16Size
	return
}

// DecodeMsg implements msgp.Decodable
func (z *CameraInfo6D) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "FNumber":
			{
				var zb0002 float32
				zb0002, err = dc.ReadFloat32()
				if err != nil {
					err = msgp.WrapError(err, "FNumber")
					return
				}
				z.FNumber = FNumber(zb0002)
			}
		case "ExposureTime":
			{
				var zb0003 float32
				zb0003, err = dc.ReadFloat32()
				if err != nil {
					err = msgp.WrapError(err, "ExposureTime")
					return
				}
				z.ExposureTime = CIExposureTime(zb0003)
			}
		case "ISO":
			{
				var zb0004 uint32
				zb0004, err = dc.ReadUint32()
				if err != nil {
					err = msgp.WrapError(err, "ISO")
					return
				}
				z.ISO = ISO(zb0004)
			}
		case "CameraTemperature":
			{
				var zb0005 uint8
				zb0005, err = dc.ReadUint8()
				if err != nil {
					err = msgp.WrapError(err, "CameraTemperature")
					return
				}
				z.CameraTemperature = CameraTemperature(zb0005)
			}
		case "FocalLength":
			err = z.FocalLength.DecodeMsg(dc)
			if err != nil {
				err = msgp.WrapError(err, "FocalLength")
				return
			}
		case "CameraOrientation":
			{
				var zb0006 uint8
				zb0006, err = dc.ReadUint8()
				if err != nil {
					err = msgp.WrapError(err, "CameraOrientation")
					return
				}
				z.CameraOrientation = CameraOrientation(zb0006)
			}
		case "FocusDistanceUpper":
			err = z.FocusDistanceUpper.DecodeMsg(dc)
			if err != nil {
				err = msgp.WrapError(err, "FocusDistanceUpper")
				return
			}
		case "FocusDistanceLower":
			err = z.FocusDistanceLower.DecodeMsg(dc)
			if err != nil {
				err = msgp.WrapError(err, "FocusDistanceLower")
				return
			}
		case "WhiteBalance":
			z.WhiteBalance, err = dc.ReadUint16()
			if err != nil {
				err = msgp.WrapError(err, "WhiteBalance")
				return
			}
		case "ColorTemperature":
			z.ColorTemperature, err = dc.ReadUint16()
			if err != nil {
				err = msgp.WrapError(err, "ColorTemperature")
				return
			}
		case "PictureStyle":
			z.PictureStyle, err = dc.ReadUint8()
			if err != nil {
				err = msgp.WrapError(err, "PictureStyle")
				return
			}
		case "LensType":
			err = z.LensType.DecodeMsg(dc)
			if err != nil {
				err = msgp.WrapError(err, "LensType")
				return
			}
		case "MinFocalLength":
			{
				var zb0007 uint16
				zb0007, err = dc.ReadUint16()
				if err != nil {
					err = msgp.WrapError(err, "MinFocalLength")
					return
				}
				z.MinFocalLength = CIFocalLength(zb0007)
			}
		case "MaxFocalLength":
			{
				var zb0008 uint16
				zb0008, err = dc.ReadUint16()
				if err != nil {
					err = msgp.WrapError(err, "MaxFocalLength")
					return
				}
				z.MaxFocalLength = CIFocalLength(zb0008)
			}
		case "FirmwareVersion":
			z.FirmwareVersion, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "FirmwareVersion")
				return
			}
		case "FileIndex":
			z.FileIndex, err = dc.ReadUint32()
			if err != nil {
				err = msgp.WrapError(err, "FileIndex")
				return
			}
		case "DirectoryIndex":
			z.DirectoryIndex, err = dc.ReadUint32()
			if err != nil {
				err = msgp.WrapError(err, "DirectoryIndex")
				return
			}
		case "PictureStyleInfo":
			err = z.PictureStyleInfo.DecodeMsg(dc)
			if err != nil {
				err = msgp.WrapError(err, "PictureStyleInfo")
				return
			}
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z *CameraInfo6D) EncodeMsg(en *msgp.Writer) (err error) {
	// map header, size 18
	// write "FNumber"
	err = en.Append(0xde, 0x0, 0x12, 0xa7, 0x46, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72)
	if err != nil {
		return
	}
	err = en.WriteFloat32(float32(z.FNumber))
	if err != nil {
		err = msgp.WrapError(err, "FNumber")
		return
	}
	// write "ExposureTime"
	err = en.Append(0xac, 0x45, 0x78, 0x70, 0x6f, 0x73, 0x75, 0x72, 0x65, 0x54, 0x69, 0x6d, 0x65)
	if err != nil {
		return
	}
	err = en.WriteFloat32(float32(z.ExposureTime))
	if err != nil {
		err = msgp.WrapError(err, "ExposureTime")
		return
	}
	// write "ISO"
	err = en.Append(0xa3, 0x49, 0x53, 0x4f)
	if err != nil {
		return
	}
	err = en.WriteUint32(uint32(z.ISO))
	if err != nil {
		err = msgp.WrapError(err, "ISO")
		return
	}
	// write "CameraTemperature"
	err = en.Append(0xb1, 0x43, 0x61, 0x6d, 0x65, 0x72, 0x61, 0x54, 0x65, 0x6d, 0x70, 0x65, 0x72, 0x61, 0x74, 0x75, 0x72, 0x65)
	if err != nil {
		return
	}
	err = en.WriteUint8(uint8(z.CameraTemperature))
	if err != nil {
		err = msgp.WrapError(err, "CameraTemperature")
		return
	}
	// write "FocalLength"
	err = en.Append(0xab, 0x46, 0x6f, 0x63, 0x61, 0x6c, 0x4c, 0x65, 0x6e, 0x67, 0x74, 0x68)
	if err != nil {
		return
	}
	err = z.FocalLength.EncodeMsg(en)
	if err != nil {
		err = msgp.WrapError(err, "FocalLength")
		return
	}
	// write "CameraOrientation"
	err = en.Append(0xb1, 0x43, 0x61, 0x6d, 0x65, 0x72, 0x61, 0x4f, 0x72, 0x69, 0x65, 0x6e, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e)
	if err != nil {
		return
	}
	err = en.WriteUint8(uint8(z.CameraOrientation))
	if err != nil {
		err = msgp.WrapError(err, "CameraOrientation")
		return
	}
	// write "FocusDistanceUpper"
	err = en.Append(0xb2, 0x46, 0x6f, 0x63, 0x75, 0x73, 0x44, 0x69, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x55, 0x70, 0x70, 0x65, 0x72)
	if err != nil {
		return
	}
	err = z.FocusDistanceUpper.EncodeMsg(en)
	if err != nil {
		err = msgp.WrapError(err, "FocusDistanceUpper")
		return
	}
	// write "FocusDistanceLower"
	err = en.Append(0xb2, 0x46, 0x6f, 0x63, 0x75, 0x73, 0x44, 0x69, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x4c, 0x6f, 0x77, 0x65, 0x72)
	if err != nil {
		return
	}
	err = z.FocusDistanceLower.EncodeMsg(en)
	if err != nil {
		err = msgp.WrapError(err, "FocusDistanceLower")
		return
	}
	// write "WhiteBalance"
	err = en.Append(0xac, 0x57, 0x68, 0x69, 0x74, 0x65, 0x42, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65)
	if err != nil {
		return
	}
	err = en.WriteUint16(z.WhiteBalance)
	if err != nil {
		err = msgp.WrapError(err, "WhiteBalance")
		return
	}
	// write "ColorTemperature"
	err = en.Append(0xb0, 0x43, 0x6f, 0x6c, 0x6f, 0x72, 0x54, 0x65, 0x6d, 0x70, 0x65, 0x72, 0x61, 0x74, 0x75, 0x72, 0x65)
	if err != nil {
		return
	}
	err = en.WriteUint16(z.ColorTemperature)
	if err != nil {
		err = msgp.WrapError(err, "ColorTemperature")
		return
	}
	// write "PictureStyle"
	err = en.Append(0xac, 0x50, 0x69, 0x63, 0x74, 0x75, 0x72, 0x65, 0x53, 0x74, 0x79, 0x6c, 0x65)
	if err != nil {
		return
	}
	err = en.WriteUint8(z.PictureStyle)
	if err != nil {
		err = msgp.WrapError(err, "PictureStyle")
		return
	}
	// write "LensType"
	err = en.Append(0xa8, 0x4c, 0x65, 0x6e, 0x73, 0x54, 0x79, 0x70, 0x65)
	if err != nil {
		return
	}
	err = z.LensType.EncodeMsg(en)
	if err != nil {
		err = msgp.WrapError(err, "LensType")
		return
	}
	// write "MinFocalLength"
	err = en.Append(0xae, 0x4d, 0x69, 0x6e, 0x46, 0x6f, 0x63, 0x61, 0x6c, 0x4c, 0x65, 0x6e, 0x67, 0x74, 0x68)
	if err != nil {
		return
	}
	err = en.WriteUint16(uint16(z.MinFocalLength))
	if err != nil {
		err = msgp.WrapError(err, "MinFocalLength")
		return
	}
	// write "MaxFocalLength"
	err = en.Append(0xae, 0x4d, 0x61, 0x78, 0x46, 0x6f, 0x63, 0x61, 0x6c, 0x4c, 0x65, 0x6e, 0x67, 0x74, 0x68)
	if err != nil {
		return
	}
	err = en.WriteUint16(uint16(z.MaxFocalLength))
	if err != nil {
		err = msgp.WrapError(err, "MaxFocalLength")
		return
	}
	// write "FirmwareVersion"
	err = en.Append(0xaf, 0x46, 0x69, 0x72, 0x6d, 0x77, 0x61, 0x72, 0x65, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e)
	if err != nil {
		return
	}
	err = en.WriteString(z.FirmwareVersion)
	if err != nil {
		err = msgp.WrapError(err, "FirmwareVersion")
		return
	}
	// write "FileIndex"
	err = en.Append(0xa9, 0x46, 0x69, 0x6c, 0x65, 0x49, 0x6e, 0x64, 0x65, 0x78)
	if err != nil {
		return
	}
	err = en.WriteUint32(z.FileIndex)
	if err != nil {
		err = msgp.WrapError(err, "FileIndex")
		return
	}
	// write "DirectoryIndex"
	err = en.Append(0xae, 0x44, 0x69, 0x72, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x79, 0x49, 0x6e, 0x64, 0x65, 0x78)
	if err != nil {
		return
	}
	err = en.WriteUint32(z.DirectoryIndex)
	if err != nil {
		err = msgp.WrapError(err, "DirectoryIndex")
		return
	}
	// write "PictureStyleInfo"
	err = en.Append(0xb0, 0x50, 0x69, 0x63, 0x74, 0x75, 0x72, 0x65, 0x53, 0x74, 0x79, 0x6c, 0x65, 0x49, 0x6e, 0x66, 0x6f)
	if err != nil {
		return
	}
	err = z.PictureStyleInfo.EncodeMsg(en)
	if err != nil {
		err = msgp.WrapError(err, "PictureStyleInfo")
		return
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z *CameraInfo6D) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// map header, size 18
	// string "FNumber"
	o = append(o, 0xde, 0x0, 0x12, 0xa7, 0x46, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72)
	o = msgp.AppendFloat32(o, float32(z.FNumber))
	// string "ExposureTime"
	o = append(o, 0xac, 0x45, 0x78, 0x70, 0x6f, 0x73, 0x75, 0x72, 0x65, 0x54, 0x69, 0x6d, 0x65)
	o = msgp.AppendFloat32(o, float32(z.ExposureTime))
	// string "ISO"
	o = append(o, 0xa3, 0x49, 0x53, 0x4f)
	o = msgp.AppendUint32(o, uint32(z.ISO))
	// string "CameraTemperature"
	o = append(o, 0xb1, 0x43, 0x61, 0x6d, 0x65, 0x72, 0x61, 0x54, 0x65, 0x6d, 0x70, 0x65, 0x72, 0x61, 0x74, 0x75, 0x72, 0x65)
	o = msgp.AppendUint8(o, uint8(z.CameraTemperature))
	// string "FocalLength"
	o = append(o, 0xab, 0x46, 0x6f, 0x63, 0x61, 0x6c, 0x4c, 0x65, 0x6e, 0x67, 0x74, 0x68)
	o, err = z.FocalLength.MarshalMsg(o)
	if err != nil {
		err = msgp.WrapError(err, "FocalLength")
		return
	}
	// string "CameraOrientation"
	o = append(o, 0xb1, 0x43, 0x61, 0x6d, 0x65, 0x72, 0x61, 0x4f, 0x72, 0x69, 0x65, 0x6e, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e)
	o = msgp.AppendUint8(o, uint8(z.CameraOrientation))
	// string "FocusDistanceUpper"
	o = append(o, 0xb2, 0x46, 0x6f, 0x63, 0x75, 0x73, 0x44, 0x69, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x55, 0x70, 0x70, 0x65, 0x72)
	o, err = z.FocusDistanceUpper.MarshalMsg(o)
	if err != nil {
		err = msgp.WrapError(err, "FocusDistanceUpper")
		return
	}
	// string "FocusDistanceLower"
	o = append(o, 0xb2, 0x46, 0x6f, 0x63, 0x75, 0x73, 0x44, 0x69, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x4c, 0x6f, 0x77, 0x65, 0x72)
	o, err = z.FocusDistanceLower.MarshalMsg(o)
	if err != nil {
		err = msgp.WrapError(err, "FocusDistanceLower")
		return
	}
	// string "WhiteBalance"
	o = append(o, 0xac, 0x57, 0x68, 0x69, 0x74, 0x65, 0x42, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65)
	o = msgp.AppendUint16(o, z.WhiteBalance)
	// string "ColorTemperature"
	o = append(o, 0xb0, 0x43, 0x6f, 0x6c, 0x6f, 0x72, 0x54, 0x65, 0x6d, 0x70, 0x65, 0x72, 0x61, 0x74, 0x75, 0x72, 0x65)
	o = msgp.AppendUint16(o, z.ColorTemperature)
	// string "PictureStyle"
	o = append(o, 0xac, 0x50, 0x69, 0x63, 0x74, 0x75, 0x72, 0x65, 0x53, 0x74, 0x79, 0x6c, 0x65)
	o = msgp.AppendUint8(o, z.PictureStyle)
	// string "LensType"
	o = append(o, 0xa8, 0x4c, 0x65, 0x6e, 0x73, 0x54, 0x79, 0x70, 0x65)
	o, err = z.LensType.MarshalMsg(o)
	if err != nil {
		err = msgp.WrapError(err, "LensType")
		return
	}
	// string "MinFocalLength"
	o = append(o, 0xae, 0x4d, 0x69, 0x6e, 0x46, 0x6f, 0x63, 0x61, 0x6c, 0x4c, 0x65, 0x6e, 0x67, 0x74, 0x68)
	o = msgp.AppendUint16(o, uint16(z.MinFocalLength))
	// string "MaxFocalLength"
	o = append(o, 0xae, 0x4d, 0x61, 0x78, 0x46, 0x6f, 0x63, 0x61, 0x6c, 0x4c, 0x65, 0x6e, 0x67, 0x74, 0x68)
	o = msgp.AppendUint16(o, uint16(z.MaxFocalLength))
	// string "FirmwareVersion"
	o = append(o, 0xaf, 0x46, 0x69, 0x72, 0x6d, 0x77, 0x61, 0x72, 0x65, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e)
	o = msgp.AppendString(o, z.FirmwareVersion)
	// string "FileIndex"
	o = append(o, 0xa9, 0x46, 0x69, 0x6c, 0x65, 0x49, 0x6e, 0x64, 0x65, 0x78)
	o = msgp.AppendUint32(o, z.FileIndex)
	// string "DirectoryIndex"
	o = append(o, 0xae, 0x44, 0x69, 0x72, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x79, 0x49, 0x6e, 0x64, 0x65, 0x78)
	o = msgp.AppendUint32(o, z.DirectoryIndex)
	// string "PictureStyleInfo"
	o = append(o, 0xb0, 0x50, 0x69, 0x63, 0x74, 0x75, 0x72, 0x65, 0x53, 0x74, 0x79, 0x6c, 0x65, 0x49, 0x6e, 0x66, 0x6f)
	o, err = z.PictureStyleInfo.MarshalMsg(o)
	if err != nil {
		err = msgp.WrapError(err, "PictureStyleInfo")
		return
	}
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *CameraInfo6D) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "FNumber":
			{
				var zb0002 float32
				zb0002, bts, err = msgp.ReadFloat32Bytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "FNumber")
					return
				}
				z.FNumber = FNumber(zb0002)
			}
		case "ExposureTime":
			{
				var zb0003 float32
				zb0003, bts, err = msgp.ReadFloat32Bytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "ExposureTime")
					return
				}
				z.ExposureTime = CIExposureTime(zb0003)
			}
		case "ISO":
			{
				var zb0004 uint32
				zb0004, bts, err = msgp.ReadUint32Bytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "ISO")
					return
				}
				z.ISO = ISO(zb0004)
			}
		case "CameraTemperature":
			{
				var zb0005 uint8
				zb0005, bts, err = msgp.ReadUint8Bytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "CameraTemperature")
					return
				}
				z.CameraTemperature = CameraTemperature(zb0005)
			}
		case "FocalLength":
			bts, err = z.FocalLength.UnmarshalMsg(bts)
			if err != nil {
				err = msgp.WrapError(err, "FocalLength")
				return
			}
		case "CameraOrientation":
			{
				var zb0006 uint8
				zb0006, bts, err = msgp.ReadUint8Bytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "CameraOrientation")
					return
				}
				z.CameraOrientation = CameraOrientation(zb0006)
			}
		case "FocusDistanceUpper":
			bts, err = z.FocusDistanceUpper.UnmarshalMsg(bts)
			if err != nil {
				err = msgp.WrapError(err, "FocusDistanceUpper")
				return
			}
		case "FocusDistanceLower":
			bts, err = z.FocusDistanceLower.UnmarshalMsg(bts)
			if err != nil {
				err = msgp.WrapError(err, "FocusDistanceLower")
				return
			}
		case "WhiteBalance":
			z.WhiteBalance, bts, err = msgp.ReadUint16Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "WhiteBalance")
				return
			}
		case "ColorTemperature":
			z.ColorTemperature, bts, err = msgp.ReadUint16Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "ColorTemperature")
				return
			}
		case "PictureStyle":
			z.PictureStyle, bts, err = msgp.ReadUint8Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "PictureStyle")
				return
			}
		case "LensType":
			bts, err = z.LensType.UnmarshalMsg(bts)
			if err != nil {
				err = msgp.WrapError(err, "LensType")
				return
			}
		case "MinFocalLength":
			{
				var zb0007 uint16
				zb0007, bts, err = msgp.ReadUint16Bytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "MinFocalLength")
					return
				}
				z.MinFocalLength = CIFocalLength(zb0007)
			}
		case "MaxFocalLength":
			{
				var zb0008 uint16
				zb0008, bts, err = msgp.ReadUint16Bytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "MaxFocalLength")
					return
				}
				z.MaxFocalLength = CIFocalLength(zb0008)
			}
		case "FirmwareVersion":
			z.FirmwareVersion, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "FirmwareVersion")
				return
			}
		case "FileIndex":
			z.FileIndex, bts, err = msgp.ReadUint32Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "FileIndex")
				return
			}
		case "DirectoryIndex":
			z.DirectoryIndex, bts, err = msgp.ReadUint32Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "DirectoryIndex")
				return
			}
		case "PictureStyleInfo":
			bts, err = z.PictureStyleInfo.UnmarshalMsg(bts)
			if err != nil {
				err = msgp.WrapError(err, "PictureStyleInfo")
				return
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *CameraInfo6D) Msgsize() (s int) {
	s = 3 + 8 + msgp.Float32Size + 13 + msgp.Float32Size + 4 + msgp.Uint32Size + 18 + msgp.Uint8Size + 12 + z.FocalLength.Msgsize() + 18 + msgp.Uint8Size + 19 + z.FocusDistanceUpper.Msgsize() + 19 + z.FocusDistanceLower.Msgsize() + 13 + msgp.Uint16Size + 17 + msgp.Uint16Size + 13 + msgp.Uint8Size + 9 + z.LensType.Msgsize() + 15 + msgp.Uint16Size + 15 + msgp.Uint16Size + 16 + msgp.StringPrefixSize + len(z.FirmwareVersion) + 10 + msgp.Uint32Size + 15 + msgp.Uint32Size + 17 + z.PictureStyleInfo.Msgsize()
	return
}

// DecodeMsg implements msgp.Decodable
func (z *CameraOrientation) DecodeMsg(dc *msgp.Reader) (err error) {
	{
		var zb0001 uint8
		zb0001, err = dc.ReadUint8()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		(*z) = CameraOrientation(zb0001)
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z CameraOrientation) EncodeMsg(en *msgp.Writer) (err error) {
	err = en.WriteUint8(uint8(z))
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z CameraOrientation) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	o = msgp.AppendUint8(o, uint8(z))
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *CameraOrientation) UnmarshalMsg(bts []byte) (o []byte, err error) {
	{
		var zb0001 uint8
		zb0001, bts, err = msgp.ReadUint8Bytes(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		(*z) = CameraOrientation(zb0001)
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z CameraOrientation) Msgsize() (s int) {
	s = msgp.Uint8Size
	return
}

// DecodeMsg implements msgp.Decodable
func (z *CameraTemperature) DecodeMsg(dc *msgp.Reader) (err error) {
	{
		var zb0001 uint8
		zb0001, err = dc.ReadUint8()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		(*z) = CameraTemperature(zb0001)
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z CameraTemperature) EncodeMsg(en *msgp.Writer) (err error) {
	err = en.WriteUint8(uint8(z))
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z CameraTemperature) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	o = msgp.AppendUint8(o, uint8(z))
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *CameraTemperature) UnmarshalMsg(bts []byte) (o []byte, err error) {
	{
		var zb0001 uint8
		zb0001, bts, err = msgp.ReadUint8Bytes(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		(*z) = CameraTemperature(zb0001)
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z CameraTemperature) Msgsize() (s int) {
	s = msgp.Uint8Size
	return
}

// DecodeMsg implements msgp.Decodable
func (z *FNumber) DecodeMsg(dc *msgp.Reader) (err error) {
	{
		var zb0001 float32
		zb0001, err = dc.ReadFloat32()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		(*z) = FNumber(zb0001)
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z FNumber) EncodeMsg(en *msgp.Writer) (err error) {
	err = en.WriteFloat32(float32(z))
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z FNumber) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	o = msgp.AppendFloat32(o, float32(z))
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *FNumber) UnmarshalMsg(bts []byte) (o []byte, err error) {
	{
		var zb0001 float32
		zb0001, bts, err = msgp.ReadFloat32Bytes(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		(*z) = FNumber(zb0001)
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z FNumber) Msgsize() (s int) {
	s = msgp.Float32Size
	return
}

// DecodeMsg implements msgp.Decodable
func (z *FilterEffect) DecodeMsg(dc *msgp.Reader) (err error) {
	{
		var zb0001 int32
		zb0001, err = dc.ReadInt32()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		(*z) = FilterEffect(zb0001)
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z FilterEffect) EncodeMsg(en *msgp.Writer) (err error) {
	err = en.WriteInt32(int32(z))
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z FilterEffect) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	o = msgp.AppendInt32(o, int32(z))
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *FilterEffect) UnmarshalMsg(bts []byte) (o []byte, err error) {
	{
		var zb0001 int32
		zb0001, bts, err = msgp.ReadInt32Bytes(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		(*z) = FilterEffect(zb0001)
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z FilterEffect) Msgsize() (s int) {
	s = msgp.Int32Size
	return
}

// DecodeMsg implements msgp.Decodable
func (z *ISO) DecodeMsg(dc *msgp.Reader) (err error) {
	{
		var zb0001 uint32
		zb0001, err = dc.ReadUint32()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		(*z) = ISO(zb0001)
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z ISO) EncodeMsg(en *msgp.Writer) (err error) {
	err = en.WriteUint32(uint32(z))
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z ISO) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	o = msgp.AppendUint32(o, uint32(z))
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *ISO) UnmarshalMsg(bts []byte) (o []byte, err error) {
	{
		var zb0001 uint32
		zb0001, bts, err = msgp.ReadUint32Bytes(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		(*z) = ISO(zb0001)
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z ISO) Msgsize() (s int) {
	s = msgp.Uint32Size
	return
}

// DecodeMsg implements msgp.Decodable
func (z *PictureStyleInfo2) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "ContrastStandard":
			z.ContrastStandard, err = dc.ReadInt32()
			if err != nil {
				err = msgp.WrapError(err, "ContrastStandard")
				return
			}
		case "SharpnessStandard":
			z.SharpnessStandard, err = dc.ReadInt32()
			if err != nil {
				err = msgp.WrapError(err, "SharpnessStandard")
				return
			}
		case "SaturationStandard":
			z.SaturationStandard, err = dc.ReadInt32()
			if err != nil {
				err = msgp.WrapError(err, "SaturationStandard")
				return
			}
		case "ColorToneStandard":
			z.ColorToneStandard, err = dc.ReadInt32()
			if err != nil {
				err = msgp.WrapError(err, "ColorToneStandard")
				return
			}
		case "FilterEffectStandard":
			z.FilterEffectStandard, err = dc.ReadInt32()
			if err != nil {
				err = msgp.WrapError(err, "FilterEffectStandard")
				return
			}
		case "ToningEffectStandard":
			z.ToningEffectStandard, err = dc.ReadInt32()
			if err != nil {
				err = msgp.WrapError(err, "ToningEffectStandard")
				return
			}
		case "ContrastPortrait":
			z.ContrastPortrait, err = dc.ReadInt32()
			if err != nil {
				err = msgp.WrapError(err, "ContrastPortrait")
				return
			}
		case "SharpnessPortrait":
			z.SharpnessPortrait, err = dc.ReadInt32()
			if err != nil {
				err = msgp.WrapError(err, "SharpnessPortrait")
				return
			}
		case "SaturationPortrait":
			z.SaturationPortrait, err = dc.ReadInt32()
			if err != nil {
				err = msgp.WrapError(err, "SaturationPortrait")
				return
			}
		case "ColorTonePortrait":
			z.ColorTonePortrait, err = dc.ReadInt32()
			if err != nil {
				err = msgp.WrapError(err, "ColorTonePortrait")
				return
			}
		case "FilterEffectPortrait":
			z.FilterEffectPortrait, err = dc.ReadInt32()
			if err != nil {
				err = msgp.WrapError(err, "FilterEffectPortrait")
				return
			}
		case "ToningEffectPortrait":
			z.ToningEffectPortrait, err = dc.ReadInt32()
			if err != nil {
				err = msgp.WrapError(err, "ToningEffectPortrait")
				return
			}
		case "ContrastLandscape":
			z.ContrastLandscape, err = dc.ReadInt32()
			if err != nil {
				err = msgp.WrapError(err, "ContrastLandscape")
				return
			}
		case "SharpnessLandscape":
			z.SharpnessLandscape, err = dc.ReadInt32()
			if err != nil {
				err = msgp.WrapError(err, "SharpnessLandscape")
				return
			}
		case "SaturationLandscape":
			z.SaturationLandscape, err = dc.ReadInt32()
			if err != nil {
				err = msgp.WrapError(err, "SaturationLandscape")
				return
			}
		case "ColorToneLandscape":
			z.ColorToneLandscape, err = dc.ReadInt32()
			if err != nil {
				err = msgp.WrapError(err, "ColorToneLandscape")
				return
			}
		case "FilterEffectLandscape":
			z.FilterEffectLandscape, err = dc.ReadInt32()
			if err != nil {
				err = msgp.WrapError(err, "FilterEffectLandscape")
				return
			}
		case "ToningEffectLandscape":
			z.ToningEffectLandscape, err = dc.ReadInt32()
			if err != nil {
				err = msgp.WrapError(err, "ToningEffectLandscape")
				return
			}
		case "ContrastNeutral":
			z.ContrastNeutral, err = dc.ReadInt32()
			if err != nil {
				err = msgp.WrapError(err, "ContrastNeutral")
				return
			}
		case "SharpnessNeutral":
			z.SharpnessNeutral, err = dc.ReadInt32()
			if err != nil {
				err = msgp.WrapError(err, "SharpnessNeutral")
				return
			}
		case "SaturationNeutral":
			z.SaturationNeutral, err = dc.ReadInt32()
			if err != nil {
				err = msgp.WrapError(err, "SaturationNeutral")
				return
			}
		case "ColorToneNeutral":
			z.ColorToneNeutral, err = dc.ReadInt32()
			if err != nil {
				err = msgp.WrapError(err, "ColorToneNeutral")
				return
			}
		case "FilterEffectNeutral":
			z.FilterEffectNeutral, err = dc.ReadInt32()
			if err != nil {
				err = msgp.WrapError(err, "FilterEffectNeutral")
				return
			}
		case "ToningEffectNeutral":
			z.ToningEffectNeutral, err = dc.ReadInt32()
			if err != nil {
				err = msgp.WrapError(err, "ToningEffectNeutral")
				return
			}
		case "ContrastFaithful":
			z.ContrastFaithful, err = dc.ReadInt32()
			if err != nil {
				err = msgp.WrapError(err, "ContrastFaithful")
				return
			}
		case "SharpnessFaithful":
			z.SharpnessFaithful, err = dc.ReadInt32()
			if err != nil {
				err = msgp.WrapError(err, "SharpnessFaithful")
				return
			}
		case "SaturationFaithful":
			z.SaturationFaithful, err = dc.ReadInt32()
			if err != nil {
				err = msgp.WrapError(err, "SaturationFaithful")
				return
			}
		case "ColorToneFaithful":
			z.ColorToneFaithful, err = dc.ReadInt32()
			if err != nil {
				err = msgp.WrapError(err, "ColorToneFaithful")
				return
			}
		case "FilterEffectFaithful":
			z.FilterEffectFaithful, err = dc.ReadInt32()
			if err != nil {
				err = msgp.WrapError(err, "FilterEffectFaithful")
				return
			}
		case "ToningEffectFaithful":
			z.ToningEffectFaithful, err = dc.ReadInt32()
			if err != nil {
				err = msgp.WrapError(err, "ToningEffectFaithful")
				return
			}
		case "ContrastMonochrome":
			z.ContrastMonochrome, err = dc.ReadInt32()
			if err != nil {
				err = msgp.WrapError(err, "ContrastMonochrome")
				return
			}
		case "SharpnessMonochrome":
			z.SharpnessMonochrome, err = dc.ReadInt32()
			if err != nil {
				err = msgp.WrapError(err, "SharpnessMonochrome")
				return
			}
		case "SaturationMonochrome":
			z.SaturationMonochrome, err = dc.ReadInt32()
			if err != nil {
				err = msgp.WrapError(err, "SaturationMonochrome")
				return
			}
		case "ColorToneMonochrome":
			z.ColorToneMonochrome, err = dc.ReadInt32()
			if err != nil {
				err = msgp.WrapError(err, "ColorToneMonochrome")
				return
			}
		case "FilterEffectMonochrome":
			{
				var zb0002 int32
				zb0002, err = dc.ReadInt32()
				if err != nil {
					err = msgp.WrapError(err, "FilterEffectMonochrome")
					return
				}
				z.FilterEffectMonochrome = FilterEffect(zb0002)
			}
		case "ToningEffectMonochrome":
			{
				var zb0003 int32
				zb0003, err = dc.ReadInt32()
				if err != nil {
					err = msgp.WrapError(err, "ToningEffectMonochrome")
					return
				}
				z.ToningEffectMonochrome = ToningEffect(zb0003)
			}
		case "ContrastAuto":
			z.ContrastAuto, err = dc.ReadInt32()
			if err != nil {
				err = msgp.WrapError(err, "ContrastAuto")
				return
			}
		case "SharpnessAuto":
			z.SharpnessAuto, err = dc.ReadInt32()
			if err != nil {
				err = msgp.WrapError(err, "SharpnessAuto")
				return
			}
		case "SaturationAuto":
			z.SaturationAuto, err = dc.ReadInt32()
			if err != nil {
				err = msgp.WrapError(err, "SaturationAuto")
				return
			}
		case "ColorToneAuto":
			z.ColorToneAuto, err = dc.ReadInt32()
			if err != nil {
				err = msgp.WrapError(err, "ColorToneAuto")
				return
			}
		case "FilterEffectAuto":
			{
				var zb0004 int32
				zb0004, err = dc.ReadInt32()
				if err != nil {
					err = msgp.WrapError(err, "FilterEffectAuto")
					return
				}
				z.FilterEffectAuto = FilterEffect(zb0004)
			}
		case "ToningEffectAuto":
			{
				var zb0005 int32
				zb0005, err = dc.ReadInt32()
				if err != nil {
					err = msgp.WrapError(err, "ToningEffectAuto")
					return
				}
				z.ToningEffectAuto = ToningEffect(zb0005)
			}
		case "ContrastUserDef1":
			z.ContrastUserDef1, err = dc.ReadInt32()
			if err != nil {
				err = msgp.WrapError(err, "ContrastUserDef1")
				return
			}
		case "SharpnessUserDef1":
			z.SharpnessUserDef1, err = dc.ReadInt32()
			if err != nil {
				err = msgp.WrapError(err, "SharpnessUserDef1")
				return
			}
		case "SaturationUserDef1":
			z.SaturationUserDef1, err = dc.ReadInt32()
			if err != nil {
				err = msgp.WrapError(err, "SaturationUserDef1")
				return
			}
		case "ColorToneUserDef1":
			z.ColorToneUserDef1, err = dc.ReadInt32()
			if err != nil {
				err = msgp.WrapError(err, "ColorToneUserDef1")
				return
			}
		case "FilterEffectUserDef1":
			{
				var zb0006 int32
				zb0006, err = dc.ReadInt32()
				if err != nil {
					err = msgp.WrapError(err, "FilterEffectUserDef1")
					return
				}
				z.FilterEffectUserDef1 = FilterEffect(zb0006)
			}
		case "ToningEffectUserDef1":
			{
				var zb0007 int32
				zb0007, err = dc.ReadInt32()
				if err != nil {
					err = msgp.WrapError(err, "ToningEffectUserDef1")
					return
				}
				z.ToningEffectUserDef1 = ToningEffect(zb0007)
			}
		case "ContrastUserDef2":
			z.ContrastUserDef2, err = dc.ReadInt32()
			if err != nil {
				err = msgp.WrapError(err, "ContrastUserDef2")
				return
			}
		case "SharpnessUserDef2":
			z.SharpnessUserDef2, err = dc.ReadInt32()
			if err != nil {
				err = msgp.WrapError(err, "SharpnessUserDef2")
				return
			}
		case "SaturationUserDef2":
			z.SaturationUserDef2, err = dc.ReadInt32()
			if err != nil {
				err = msgp.WrapError(err, "SaturationUserDef2")
				return
			}
		case "ColorToneUserDef2":
			z.ColorToneUserDef2, err = dc.ReadInt32()
			if err != nil {
				err = msgp.WrapError(err, "ColorToneUserDef2")
				return
			}
		case "FilterEffectUserDef2":
			{
				var zb0008 int32
				zb0008, err = dc.ReadInt32()
				if err != nil {
					err = msgp.WrapError(err, "FilterEffectUserDef2")
					return
				}
				z.FilterEffectUserDef2 = FilterEffect(zb0008)
			}
		case "ToningEffectUserDef2":
			{
				var zb0009 int32
				zb0009, err = dc.ReadInt32()
				if err != nil {
					err = msgp.WrapError(err, "ToningEffectUserDef2")
					return
				}
				z.ToningEffectUserDef2 = ToningEffect(zb0009)
			}
		case "ContrastUserDef3":
			z.ContrastUserDef3, err = dc.ReadInt32()
			if err != nil {
				err = msgp.WrapError(err, "ContrastUserDef3")
				return
			}
		case "SharpnessUserDef3":
			z.SharpnessUserDef3, err = dc.ReadInt32()
			if err != nil {
				err = msgp.WrapError(err, "SharpnessUserDef3")
				return
			}
		case "SaturationUserDef3":
			z.SaturationUserDef3, err = dc.ReadInt32()
			if err != nil {
				err = msgp.WrapError(err, "SaturationUserDef3")
				return
			}
		case "ColorToneUserDef3":
			z.ColorToneUserDef3, err = dc.ReadInt32()
			if err != nil {
				err = msgp.WrapError(err, "ColorToneUserDef3")
				return
			}
		case "FilterEffectUserDef3":
			{
				var zb0010 int32
				zb0010, err = dc.ReadInt32()
				if err != nil {
					err = msgp.WrapError(err, "FilterEffectUserDef3")
					return
				}
				z.FilterEffectUserDef3 = FilterEffect(zb0010)
			}
		case "ToningEffectUserDef3":
			{
				var zb0011 int32
				zb0011, err = dc.ReadInt32()
				if err != nil {
					err = msgp.WrapError(err, "ToningEffectUserDef3")
					return
				}
				z.ToningEffectUserDef3 = ToningEffect(zb0011)
			}
		case "UserDef1PictureStyle":
			z.UserDef1PictureStyle, err = dc.ReadUint16()
			if err != nil {
				err = msgp.WrapError(err, "UserDef1PictureStyle")
				return
			}
		case "UserDef2PictureStyle":
			z.UserDef2PictureStyle, err = dc.ReadUint16()
			if err != nil {
				err = msgp.WrapError(err, "UserDef2PictureStyle")
				return
			}
		case "UserDef3PictureStyle":
			z.UserDef3PictureStyle, err = dc.ReadUint16()
			if err != nil {
				err = msgp.WrapError(err, "UserDef3PictureStyle")
				return
			}
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z *PictureStyleInfo2) EncodeMsg(en *msgp.Writer) (err error) {
	// map header, size 63
	// write "ContrastStandard"
	err = en.Append(0xde, 0x0, 0x3f, 0xb0, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x73, 0x74, 0x53, 0x74, 0x61, 0x6e, 0x64, 0x61, 0x72, 0x64)
	if err != nil {
		return
	}
	err = en.WriteInt32(z.ContrastStandard)
	if err != nil {
		err = msgp.WrapError(err, "ContrastStandard")
		return
	}
	// write "SharpnessStandard"
	err = en.Append(0xb1, 0x53, 0x68, 0x61, 0x72, 0x70, 0x6e, 0x65, 0x73, 0x73, 0x53, 0x74, 0x61, 0x6e, 0x64, 0x61, 0x72, 0x64)
	if err != nil {
		return
	}
	err = en.WriteInt32(z.SharpnessStandard)
	if err != nil {
		err = msgp.WrapError(err, "SharpnessStandard")
		return
	}
	// write "SaturationStandard"
	err = en.Append(0xb2, 0x53, 0x61, 0x74, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x74, 0x61, 0x6e, 0x64, 0x61, 0x72, 0x64)
	if err != nil {
		return
	}
	err = en.WriteInt32(z.SaturationStandard)
	if err != nil {
		err = msgp.WrapError(err, "SaturationStandard")
		return
	}
	// write "ColorToneStandard"
	err = en.Append(0xb1, 0x43, 0x6f, 0x6c, 0x6f, 0x72, 0x54, 0x6f, 0x6e, 0x65, 0x53, 0x74, 0x61, 0x6e, 0x64, 0x61, 0x72, 0x64)
	if err != nil {
		return
	}
	err = en.WriteInt32(z.ColorToneStandard)
	if err != nil {
		err = msgp.WrapError(err, "ColorToneStandard")
		return
	}
	// write "FilterEffectStandard"
	err = en.Append(0xb4, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x45, 0x66, 0x66, 0x65, 0x63, 0x74, 0x53, 0x74, 0x61, 0x6e, 0x64, 0x61, 0x72, 0x64)
	if err != nil {
		return
	}
	err = en.WriteInt32(z.FilterEffectStandard)
	if err != nil {
		err = msgp.WrapError(err, "FilterEffectStandard")
		return
	}
	// write "ToningEffectStandard"
	err = en.Append(0xb4, 0x54, 0x6f, 0x6e, 0x69, 0x6e, 0x67, 0x45, 0x66, 0x66, 0x65, 0x63, 0x74, 0x53, 0x74, 0x61, 0x6e, 0x64, 0x61, 0x72, 0x64)
	if err != nil {
		return
	}
	err = en.WriteInt32(z.ToningEffectStandard)
	if err != nil {
		err = msgp.WrapError(err, "ToningEffectStandard")
		return
	}
	// write "ContrastPortrait"
	err = en.Append(0xb0, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x73, 0x74, 0x50, 0x6f, 0x72, 0x74, 0x72, 0x61, 0x69, 0x74)
	if err != nil {
		return
	}
	err = en.WriteInt32(z.ContrastPortrait)
	if err != nil {
		err = msgp.WrapError(err, "ContrastPortrait")
		return
	}
	// write "SharpnessPortrait"
	err = en.Append(0xb1, 0x53, 0x68, 0x61, 0x72, 0x70, 0x6e, 0x65, 0x73, 0x73, 0x50, 0x6f, 0x72, 0x74, 0x72, 0x61, 0x69, 0x74)
	if err != nil {
		return
	}
	err = en.WriteInt32(z.SharpnessPortrait)
	if err != nil {
		err = msgp.WrapError(err, "SharpnessPortrait")
		return
	}
	// write "SaturationPortrait"
	err = en.Append(0xb2, 0x53, 0x61, 0x74, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x50, 0x6f, 0x72, 0x74, 0x72, 0x61, 0x69, 0x74)
	if err != nil {
		return
	}
	err = en.WriteInt32(z.SaturationPortrait)
	if err != nil {
		err = msgp.WrapError(err, "SaturationPortrait")
		return
	}
	// write "ColorTonePortrait"
	err = en.Append(0xb1, 0x43, 0x6f, 0x6c, 0x6f, 0x72, 0x54, 0x6f, 0x6e, 0x65, 0x50, 0x6f, 0x72, 0x74, 0x72, 0x61, 0x69, 0x74)
	if err != nil {
		return
	}
	err = en.WriteInt32(z.ColorTonePortrait)
	if err != nil {
		err = msgp.WrapError(err, "ColorTonePortrait")
		return
	}
	// write "FilterEffectPortrait"
	err = en.Append(0xb4, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x45, 0x66, 0x66, 0x65, 0x63, 0x74, 0x50, 0x6f, 0x72, 0x74, 0x72, 0x61, 0x69, 0x74)
	if err != nil {
		return
	}
	err = en.WriteInt32(z.FilterEffectPortrait)
	if err != nil {
		err = msgp.WrapError(err, "FilterEffectPortrait")
		return
	}
	// write "ToningEffectPortrait"
	err = en.Append(0xb4, 0x54, 0x6f, 0x6e, 0x69, 0x6e, 0x67, 0x45, 0x66, 0x66, 0x65, 0x63, 0x74, 0x50, 0x6f, 0x72, 0x74, 0x72, 0x61, 0x69, 0x74)
	if err != nil {
		return
	}
	err = en.WriteInt32(z.ToningEffectPortrait)
	if err != nil {
		err = msgp.WrapError(err, "ToningEffectPortrait")
		return
	}
	// write "ContrastLandscape"
	err = en.Append(0xb1, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x73, 0x74, 0x4c, 0x61, 0x6e, 0x64, 0x73, 0x63, 0x61, 0x70, 0x65)
	if err != nil {
		return
	}
	err = en.WriteInt32(z.ContrastLandscape)
	if err != nil {
		err = msgp.WrapError(err, "ContrastLandscape")
		return
	}
	// write "SharpnessLandscape"
	err = en.Append(0xb2, 0x53, 0x68, 0x61, 0x72, 0x70, 0x6e, 0x65, 0x73, 0x73, 0x4c, 0x61, 0x6e, 0x64, 0x73, 0x63, 0x61, 0x70, 0x65)
	if err != nil {
		return
	}
	err = en.WriteInt32(z.SharpnessLandscape)
	if err != nil {
		err = msgp.WrapError(err, "SharpnessLandscape")
		return
	}
	// write "SaturationLandscape"
	err = en.Append(0xb3, 0x53, 0x61, 0x74, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4c, 0x61, 0x6e, 0x64, 0x73, 0x63, 0x61, 0x70, 0x65)
	if err != nil {
		return
	}
	err = en.WriteInt32(z.SaturationLandscape)
	if err != nil {
		err = msgp.WrapError(err, "SaturationLandscape")
		return
	}
	// write "ColorToneLandscape"
	err = en.Append(0xb2, 0x43, 0x6f, 0x6c, 0x6f, 0x72, 0x54, 0x6f, 0x6e, 0x65, 0x4c, 0x61, 0x6e, 0x64, 0x73, 0x63, 0x61, 0x70, 0x65)
	if err != nil {
		return
	}
	err = en.WriteInt32(z.ColorToneLandscape)
	if err != nil {
		err = msgp.WrapError(err, "ColorToneLandscape")
		return
	}
	// write "FilterEffectLandscape"
	err = en.Append(0xb5, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x45, 0x66, 0x66, 0x65, 0x63, 0x74, 0x4c, 0x61, 0x6e, 0x64, 0x73, 0x63, 0x61, 0x70, 0x65)
	if err != nil {
		return
	}
	err = en.WriteInt32(z.FilterEffectLandscape)
	if err != nil {
		err = msgp.WrapError(err, "FilterEffectLandscape")
		return
	}
	// write "ToningEffectLandscape"
	err = en.Append(0xb5, 0x54, 0x6f, 0x6e, 0x69, 0x6e, 0x67, 0x45, 0x66, 0x66, 0x65, 0x63, 0x74, 0x4c, 0x61, 0x6e, 0x64, 0x73, 0x63, 0x61, 0x70, 0x65)
	if err != nil {
		return
	}
	err = en.WriteInt32(z.ToningEffectLandscape)
	if err != nil {
		err = msgp.WrapError(err, "ToningEffectLandscape")
		return
	}
	// write "ContrastNeutral"
	err = en.Append(0xaf, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x73, 0x74, 0x4e, 0x65, 0x75, 0x74, 0x72, 0x61, 0x6c)
	if err != nil {
		return
	}
	err = en.WriteInt32(z.ContrastNeutral)
	if err != nil {
		err = msgp.WrapError(err, "ContrastNeutral")
		return
	}
	// write "SharpnessNeutral"
	err = en.Append(0xb0, 0x53, 0x68, 0x61, 0x72, 0x70, 0x6e, 0x65, 0x73, 0x73, 0x4e, 0x65, 0x75, 0x74, 0x72, 0x61, 0x6c)
	if err != nil {
		return
	}
	err = en.WriteInt32(z.SharpnessNeutral)
	if err != nil {
		err = msgp.WrapError(err, "SharpnessNeutral")
		return
	}
	// write "SaturationNeutral"
	err = en.Append(0xb1, 0x53, 0x61, 0x74, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4e, 0x65, 0x75, 0x74, 0x72, 0x61, 0x6c)
	if err != nil {
		return
	}
	err = en.WriteInt32(z.SaturationNeutral)
	if err != nil {
		err = msgp.WrapError(err, "SaturationNeutral")
		return
	}
	// write "ColorToneNeutral"
	err = en.Append(0xb0, 0x43, 0x6f, 0x6c, 0x6f, 0x72, 0x54, 0x6f, 0x6e, 0x65, 0x4e, 0x65, 0x75, 0x74, 0x72, 0x61, 0x6c)
	if err != nil {
		return
	}
	err = en.WriteInt32(z.ColorToneNeutral)
	if err != nil {
		err = msgp.WrapError(err, "ColorToneNeutral")
		return
	}
	// write "FilterEffectNeutral"
	err = en.Append(0xb3, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x45, 0x66, 0x66, 0x65, 0x63, 0x74, 0x4e, 0x65, 0x75, 0x74, 0x72, 0x61, 0x6c)
	if err != nil {
		return
	}
	err = en.WriteInt32(z.FilterEffectNeutral)
	if err != nil {
		err = msgp.WrapError(err, "FilterEffectNeutral")
		return
	}
	// write "ToningEffectNeutral"
	err = en.Append(0xb3, 0x54, 0x6f, 0x6e, 0x69, 0x6e, 0x67, 0x45, 0x66, 0x66, 0x65, 0x63, 0x74, 0x4e, 0x65, 0x75, 0x74, 0x72, 0x61, 0x6c)
	if err != nil {
		return
	}
	err = en.WriteInt32(z.ToningEffectNeutral)
	if err != nil {
		err = msgp.WrapError(err, "ToningEffectNeutral")
		return
	}
	// write "ContrastFaithful"
	err = en.Append(0xb0, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x73, 0x74, 0x46, 0x61, 0x69, 0x74, 0x68, 0x66, 0x75, 0x6c)
	if err != nil {
		return
	}
	err = en.WriteInt32(z.ContrastFaithful)
	if err != nil {
		err = msgp.WrapError(err, "ContrastFaithful")
		return
	}
	// write "SharpnessFaithful"
	err = en.Append(0xb1, 0x53, 0x68, 0x61, 0x72, 0x70, 0x6e, 0x65, 0x73, 0x73, 0x46, 0x61, 0x69, 0x74, 0x68, 0x66, 0x75, 0x6c)
	if err != nil {
		return
	}
	err = en.WriteInt32(z.SharpnessFaithful)
	if err != nil {
		err = msgp.WrapError(err, "SharpnessFaithful")
		return
	}
	// write "SaturationFaithful"
	err = en.Append(0xb2, 0x53, 0x61, 0x74, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x46, 0x61, 0x69, 0x74, 0x68, 0x66, 0x75, 0x6c)
	if err != nil {
		return
	}
	err = en.WriteInt32(z.SaturationFaithful)
	if err != nil {
		err = msgp.WrapError(err, "SaturationFaithful")
		return
	}
	// write "ColorToneFaithful"
	err = en.Append(0xb1, 0x43, 0x6f, 0x6c, 0x6f, 0x72, 0x54, 0x6f, 0x6e, 0x65, 0x46, 0x61, 0x69, 0x74, 0x68, 0x66, 0x75, 0x6c)
	if err != nil {
		return
	}
	err = en.WriteInt32(z.ColorToneFaithful)
	if err != nil {
		err = msgp.WrapError(err, "ColorToneFaithful")
		return
	}
	// write "FilterEffectFaithful"
	err = en.Append(0xb4, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x45, 0x66, 0x66, 0x65, 0x63, 0x74, 0x46, 0x61, 0x69, 0x74, 0x68, 0x66, 0x75, 0x6c)
	if err != nil {
		return
	}
	err = en.WriteInt32(z.FilterEffectFaithful)
	if err != nil {
		err = msgp.WrapError(err, "FilterEffectFaithful")
		return
	}
	// write "ToningEffectFaithful"
	err = en.Append(0xb4, 0x54, 0x6f, 0x6e, 0x69, 0x6e, 0x67, 0x45, 0x66, 0x66, 0x65, 0x63, 0x74, 0x46, 0x61, 0x69, 0x74, 0x68, 0x66, 0x75, 0x6c)
	if err != nil {
		return
	}
	err = en.WriteInt32(z.ToningEffectFaithful)
	if err != nil {
		err = msgp.WrapError(err, "ToningEffectFaithful")
		return
	}
	// write "ContrastMonochrome"
	err = en.Append(0xb2, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x73, 0x74, 0x4d, 0x6f, 0x6e, 0x6f, 0x63, 0x68, 0x72, 0x6f, 0x6d, 0x65)
	if err != nil {
		return
	}
	err = en.WriteInt32(z.ContrastMonochrome)
	if err != nil {
		err = msgp.WrapError(err, "ContrastMonochrome")
		return
	}
	// write "SharpnessMonochrome"
	err = en.Append(0xb3, 0x53, 0x68, 0x61, 0x72, 0x70, 0x6e, 0x65, 0x73, 0x73, 0x4d, 0x6f, 0x6e, 0x6f, 0x63, 0x68, 0x72, 0x6f, 0x6d, 0x65)
	if err != nil {
		return
	}
	err = en.WriteInt32(z.SharpnessMonochrome)
	if err != nil {
		err = msgp.WrapError(err, "SharpnessMonochrome")
		return
	}
	// write "SaturationMonochrome"
	err = en.Append(0xb4, 0x53, 0x61, 0x74, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4d, 0x6f, 0x6e, 0x6f, 0x63, 0x68, 0x72, 0x6f, 0x6d, 0x65)
	if err != nil {
		return
	}
	err = en.WriteInt32(z.SaturationMonochrome)
	if err != nil {
		err = msgp.WrapError(err, "SaturationMonochrome")
		return
	}
	// write "ColorToneMonochrome"
	err = en.Append(0xb3, 0x43, 0x6f, 0x6c, 0x6f, 0x72, 0x54, 0x6f, 0x6e, 0x65, 0x4d, 0x6f, 0x6e, 0x6f, 0x63, 0x68, 0x72, 0x6f, 0x6d, 0x65)
	if err != nil {
		return
	}
	err = en.WriteInt32(z.ColorToneMonochrome)
	if err != nil {
		err = msgp.WrapError(err, "ColorToneMonochrome")
		return
	}
	// write "FilterEffectMonochrome"
	err = en.Append(0xb6, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x45, 0x66, 0x66, 0x65, 0x63, 0x74, 0x4d, 0x6f, 0x6e, 0x6f, 0x63, 0x68, 0x72, 0x6f, 0x6d, 0x65)
	if err != nil {
		return
	}
	err = en.WriteInt32(int32(z.FilterEffectMonochrome))
	if err != nil {
		err = msgp.WrapError(err, "FilterEffectMonochrome")
		return
	}
	// write "ToningEffectMonochrome"
	err = en.Append(0xb6, 0x54, 0x6f, 0x6e, 0x69, 0x6e, 0x67, 0x45, 0x66, 0x66, 0x65, 0x63, 0x74, 0x4d, 0x6f, 0x6e, 0x6f, 0x63, 0x68, 0x72, 0x6f, 0x6d, 0x65)
	if err != nil {
		return
	}
	err = en.WriteInt32(int32(z.ToningEffectMonochrome))
	if err != nil {
		err = msgp.WrapError(err, "ToningEffectMonochrome")
		return
	}
	// write "ContrastAuto"
	err = en.Append(0xac, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x73, 0x74, 0x41, 0x75, 0x74, 0x6f)
	if err != nil {
		return
	}
	err = en.WriteInt32(z.ContrastAuto)
	if err != nil {
		err = msgp.WrapError(err, "ContrastAuto")
		return
	}
	// write "SharpnessAuto"
	err = en.Append(0xad, 0x53, 0x68, 0x61, 0x72, 0x70, 0x6e, 0x65, 0x73, 0x73, 0x41, 0x75, 0x74, 0x6f)
	if err != nil {
		return
	}
	err = en.WriteInt32(z.SharpnessAuto)
	if err != nil {
		err = msgp.WrapError(err, "SharpnessAuto")
		return
	}
	// write "SaturationAuto"
	err = en.Append(0xae, 0x53, 0x61, 0x74, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x41, 0x75, 0x74, 0x6f)
	if err != nil {
		return
	}
	err = en.WriteInt32(z.SaturationAuto)
	if err != nil {
		err = msgp.WrapError(err, "SaturationAuto")
		return
	}
	// write "ColorToneAuto"
	err = en.Append(0xad, 0x43, 0x6f, 0x6c, 0x6f, 0x72, 0x54, 0x6f, 0x6e, 0x65, 0x41, 0x75, 0x74, 0x6f)
	if err != nil {
		return
	}
	err = en.WriteInt32(z.ColorToneAuto)
	if err != nil {
		err = msgp.WrapError(err, "ColorToneAuto")
		return
	}
	// write "FilterEffectAuto"
	err = en.Append(0xb0, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x45, 0x66, 0x66, 0x65, 0x63, 0x74, 0x41, 0x75, 0x74, 0x6f)
	if err != nil {
		return
	}
	err = en.WriteInt32(int32(z.FilterEffectAuto))
	if err != nil {
		err = msgp.WrapError(err, "FilterEffectAuto")
		return
	}
	// write "ToningEffectAuto"
	err = en.Append(0xb0, 0x54, 0x6f, 0x6e, 0x69, 0x6e, 0x67, 0x45, 0x66, 0x66, 0x65, 0x63, 0x74, 0x41, 0x75, 0x74, 0x6f)
	if err != nil {
		return
	}
	err = en.WriteInt32(int32(z.ToningEffectAuto))
	if err != nil {
		err = msgp.WrapError(err, "ToningEffectAuto")
		return
	}
	// write "ContrastUserDef1"
	err = en.Append(0xb0, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x73, 0x74, 0x55, 0x73, 0x65, 0x72, 0x44, 0x65, 0x66, 0x31)
	if err != nil {
		return
	}
	err = en.WriteInt32(z.ContrastUserDef1)
	if err != nil {
		err = msgp.WrapError(err, "ContrastUserDef1")
		return
	}
	// write "SharpnessUserDef1"
	err = en.Append(0xb1, 0x53, 0x68, 0x61, 0x72, 0x70, 0x6e, 0x65, 0x73, 0x73, 0x55, 0x73, 0x65, 0x72, 0x44, 0x65, 0x66, 0x31)
	if err != nil {
		return
	}
	err = en.WriteInt32(z.SharpnessUserDef1)
	if err != nil {
		err = msgp.WrapError(err, "SharpnessUserDef1")
		return
	}
	// write "SaturationUserDef1"
	err = en.Append(0xb2, 0x53, 0x61, 0x74, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x55, 0x73, 0x65, 0x72, 0x44, 0x65, 0x66, 0x31)
	if err != nil {
		return
	}
	err = en.WriteInt32(z.SaturationUserDef1)
	if err != nil {
		err = msgp.WrapError(err, "SaturationUserDef1")
		return
	}
	// write "ColorToneUserDef1"
	err = en.Append(0xb1, 0x43, 0x6f, 0x6c, 0x6f, 0x72, 0x54, 0x6f, 0x6e, 0x65, 0x55, 0x73, 0x65, 0x72, 0x44, 0x65, 0x66, 0x31)
	if err != nil {
		return
	}
	err = en.WriteInt32(z.ColorToneUserDef1)
	if err != nil {
		err = msgp.WrapError(err, "ColorToneUserDef1")
		return
	}
	// write "FilterEffectUserDef1"
	err = en.Append(0xb4, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x45, 0x66, 0x66, 0x65, 0x63, 0x74, 0x55, 0x73, 0x65, 0x72, 0x44, 0x65, 0x66, 0x31)
	if err != nil {
		return
	}
	err = en.WriteInt32(int32(z.FilterEffectUserDef1))
	if err != nil {
		err = msgp.WrapError(err, "FilterEffectUserDef1")
		return
	}
	// write "ToningEffectUserDef1"
	err = en.Append(0xb4, 0x54, 0x6f, 0x6e, 0x69, 0x6e, 0x67, 0x45, 0x66, 0x66, 0x65, 0x63, 0x74, 0x55, 0x73, 0x65, 0x72, 0x44, 0x65, 0x66, 0x31)
	if err != nil {
		return
	}
	err = en.WriteInt32(int32(z.ToningEffectUserDef1))
	if err != nil {
		err = msgp.WrapError(err, "ToningEffectUserDef1")
		return
	}
	// write "ContrastUserDef2"
	err = en.Append(0xb0, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x73, 0x74, 0x55, 0x73, 0x65, 0x72, 0x44, 0x65, 0x66, 0x32)
	if err != nil {
		return
	}
	err = en.WriteInt32(z.ContrastUserDef2)
	if err != nil {
		err = msgp.WrapError(err, "ContrastUserDef2")
		return
	}
	// write "SharpnessUserDef2"
	err = en.Append(0xb1, 0x53, 0x68, 0x61, 0x72, 0x70, 0x6e, 0x65, 0x73, 0x73, 0x55, 0x73, 0x65, 0x72, 0x44, 0x65, 0x66, 0x32)
	if err != nil {
		return
	}
	err = en.WriteInt32(z.SharpnessUserDef2)
	if err != nil {
		err = msgp.WrapError(err, "SharpnessUserDef2")
		return
	}
	// write "SaturationUserDef2"
	err = en.Append(0xb2, 0x53, 0x61, 0x74, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x55, 0x73, 0x65, 0x72, 0x44, 0x65, 0x66, 0x32)
	if err != nil {
		return
	}
	err = en.WriteInt32(z.SaturationUserDef2)
	if err != nil {
		err = msgp.WrapError(err, "SaturationUserDef2")
		return
	}
	// write "ColorToneUserDef2"
	err = en.Append(0xb1, 0x43, 0x6f, 0x6c, 0x6f, 0x72, 0x54, 0x6f, 0x6e, 0x65, 0x55, 0x73, 0x65, 0x72, 0x44, 0x65, 0x66, 0x32)
	if err != nil {
		return
	}
	err = en.WriteInt32(z.ColorToneUserDef2)
	if err != nil {
		err = msgp.WrapError(err, "ColorToneUserDef2")
		return
	}
	// write "FilterEffectUserDef2"
	err = en.Append(0xb4, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x45, 0x66, 0x66, 0x65, 0x63, 0x74, 0x55, 0x73, 0x65, 0x72, 0x44, 0x65, 0x66, 0x32)
	if err != nil {
		return
	}
	err = en.WriteInt32(int32(z.FilterEffectUserDef2))
	if err != nil {
		err = msgp.WrapError(err, "FilterEffectUserDef2")
		return
	}
	// write "ToningEffectUserDef2"
	err = en.Append(0xb4, 0x54, 0x6f, 0x6e, 0x69, 0x6e, 0x67, 0x45, 0x66, 0x66, 0x65, 0x63, 0x74, 0x55, 0x73, 0x65, 0x72, 0x44, 0x65, 0x66, 0x32)
	if err != nil {
		return
	}
	err = en.WriteInt32(int32(z.ToningEffectUserDef2))
	if err != nil {
		err = msgp.WrapError(err, "ToningEffectUserDef2")
		return
	}
	// write "ContrastUserDef3"
	err = en.Append(0xb0, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x73, 0x74, 0x55, 0x73, 0x65, 0x72, 0x44, 0x65, 0x66, 0x33)
	if err != nil {
		return
	}
	err = en.WriteInt32(z.ContrastUserDef3)
	if err != nil {
		err = msgp.WrapError(err, "ContrastUserDef3")
		return
	}
	// write "SharpnessUserDef3"
	err = en.Append(0xb1, 0x53, 0x68, 0x61, 0x72, 0x70, 0x6e, 0x65, 0x73, 0x73, 0x55, 0x73, 0x65, 0x72, 0x44, 0x65, 0x66, 0x33)
	if err != nil {
		return
	}
	err = en.WriteInt32(z.SharpnessUserDef3)
	if err != nil {
		err = msgp.WrapError(err, "SharpnessUserDef3")
		return
	}
	// write "SaturationUserDef3"
	err = en.Append(0xb2, 0x53, 0x61, 0x74, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x55, 0x73, 0x65, 0x72, 0x44, 0x65, 0x66, 0x33)
	if err != nil {
		return
	}
	err = en.WriteInt32(z.SaturationUserDef3)
	if err != nil {
		err = msgp.WrapError(err, "SaturationUserDef3")
		return
	}
	// write "ColorToneUserDef3"
	err = en.Append(0xb1, 0x43, 0x6f, 0x6c, 0x6f, 0x72, 0x54, 0x6f, 0x6e, 0x65, 0x55, 0x73, 0x65, 0x72, 0x44, 0x65, 0x66, 0x33)
	if err != nil {
		return
	}
	err = en.WriteInt32(z.ColorToneUserDef3)
	if err != nil {
		err = msgp.WrapError(err, "ColorToneUserDef3")
		return
	}
	// write "FilterEffectUserDef3"
	err = en.Append(0xb4, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x45, 0x66, 0x66, 0x65, 0x63, 0x74, 0x55, 0x73, 0x65, 0x72, 0x44, 0x65, 0x66, 0x33)
	if err != nil {
		return
	}
	err = en.WriteInt32(int32(z.FilterEffectUserDef3))
	if err != nil {
		err = msgp.WrapError(err, "FilterEffectUserDef3")
		return
	}
	// write "ToningEffectUserDef3"
	err = en.Append(0xb4, 0x54, 0x6f, 0x6e, 0x69, 0x6e, 0x67, 0x45, 0x66, 0x66, 0x65, 0x63, 0x74, 0x55, 0x73, 0x65, 0x72, 0x44, 0x65, 0x66, 0x33)
	if err != nil {
		return
	}
	err = en.WriteInt32(int32(z.ToningEffectUserDef3))
	if err != nil {
		err = msgp.WrapError(err, "ToningEffectUserDef3")
		return
	}
	// write "UserDef1PictureStyle"
	err = en.Append(0xb4, 0x55, 0x73, 0x65, 0x72, 0x44, 0x65, 0x66, 0x31, 0x50, 0x69, 0x63, 0x74, 0x75, 0x72, 0x65, 0x53, 0x74, 0x79, 0x6c, 0x65)
	if err != nil {
		return
	}
	err = en.WriteUint16(z.UserDef1PictureStyle)
	if err != nil {
		err = msgp.WrapError(err, "UserDef1PictureStyle")
		return
	}
	// write "UserDef2PictureStyle"
	err = en.Append(0xb4, 0x55, 0x73, 0x65, 0x72, 0x44, 0x65, 0x66, 0x32, 0x50, 0x69, 0x63, 0x74, 0x75, 0x72, 0x65, 0x53, 0x74, 0x79, 0x6c, 0x65)
	if err != nil {
		return
	}
	err = en.WriteUint16(z.UserDef2PictureStyle)
	if err != nil {
		err = msgp.WrapError(err, "UserDef2PictureStyle")
		return
	}
	// write "UserDef3PictureStyle"
	err = en.Append(0xb4, 0x55, 0x73, 0x65, 0x72, 0x44, 0x65, 0x66, 0x33, 0x50, 0x69, 0x63, 0x74, 0x75, 0x72, 0x65, 0x53, 0x74, 0x79, 0x6c, 0x65)
	if err != nil {
		return
	}
	err = en.WriteUint16(z.UserDef3PictureStyle)
	if err != nil {
		err = msgp.WrapError(err, "UserDef3PictureStyle")
		return
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z *PictureStyleInfo2) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// map header, size 63
	// string "ContrastStandard"
	o = append(o, 0xde, 0x0, 0x3f, 0xb0, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x73, 0x74, 0x53, 0x74, 0x61, 0x6e, 0x64, 0x61, 0x72, 0x64)
	o = msgp.AppendInt32(o, z.ContrastStandard)
	// string "SharpnessStandard"
	o = append(o, 0xb1, 0x53, 0x68, 0x61, 0x72, 0x70, 0x6e, 0x65, 0x73, 0x73, 0x53, 0x74, 0x61, 0x6e, 0x64, 0x61, 0x72, 0x64)
	o = msgp.AppendInt32(o, z.SharpnessStandard)
	// string "SaturationStandard"
	o = append(o, 0xb2, 0x53, 0x61, 0x74, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x74, 0x61, 0x6e, 0x64, 0x61, 0x72, 0x64)
	o = msgp.AppendInt32(o, z.SaturationStandard)
	// string "ColorToneStandard"
	o = append(o, 0xb1, 0x43, 0x6f, 0x6c, 0x6f, 0x72, 0x54, 0x6f, 0x6e, 0x65, 0x53, 0x74, 0x61, 0x6e, 0x64, 0x61, 0x72, 0x64)
	o = msgp.AppendInt32(o, z.ColorToneStandard)
	// string "FilterEffectStandard"
	o = append(o, 0xb4, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x45, 0x66, 0x66, 0x65, 0x63, 0x74, 0x53, 0x74, 0x61, 0x6e, 0x64, 0x61, 0x72, 0x64)
	o = msgp.AppendInt32(o, z.FilterEffectStandard)
	// string "ToningEffectStandard"
	o = append(o, 0xb4, 0x54, 0x6f, 0x6e, 0x69, 0x6e, 0x67, 0x45, 0x66, 0x66, 0x65, 0x63, 0x74, 0x53, 0x74, 0x61, 0x6e, 0x64, 0x61, 0x72, 0x64)
	o = msgp.AppendInt32(o, z.ToningEffectStandard)
	// string "ContrastPortrait"
	o = append(o, 0xb0, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x73, 0x74, 0x50, 0x6f, 0x72, 0x74, 0x72, 0x61, 0x69, 0x74)
	o = msgp.AppendInt32(o, z.ContrastPortrait)
	// string "SharpnessPortrait"
	o = append(o, 0xb1, 0x53, 0x68, 0x61, 0x72, 0x70, 0x6e, 0x65, 0x73, 0x73, 0x50, 0x6f, 0x72, 0x74, 0x72, 0x61, 0x69, 0x74)
	o = msgp.AppendInt32(o, z.SharpnessPortrait)
	// string "SaturationPortrait"
	o = append(o, 0xb2, 0x53, 0x61, 0x74, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x50, 0x6f, 0x72, 0x74, 0x72, 0x61, 0x69, 0x74)
	o = msgp.AppendInt32(o, z.SaturationPortrait)
	// string "ColorTonePortrait"
	o = append(o, 0xb1, 0x43, 0x6f, 0x6c, 0x6f, 0x72, 0x54, 0x6f, 0x6e, 0x65, 0x50, 0x6f, 0x72, 0x74, 0x72, 0x61, 0x69, 0x74)
	o = msgp.AppendInt32(o, z.ColorTonePortrait)
	// string "FilterEffectPortrait"
	o = append(o, 0xb4, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x45, 0x66, 0x66, 0x65, 0x63, 0x74, 0x50, 0x6f, 0x72, 0x74, 0x72, 0x61, 0x69, 0x74)
	o = msgp.AppendInt32(o, z.FilterEffectPortrait)
	// string "ToningEffectPortrait"
	o = append(o, 0xb4, 0x54, 0x6f, 0x6e, 0x69, 0x6e, 0x67, 0x45, 0x66, 0x66, 0x65, 0x63, 0x74, 0x50, 0x6f, 0x72, 0x74, 0x72, 0x61, 0x69, 0x74)
	o = msgp.AppendInt32(o, z.ToningEffectPortrait)
	// string "ContrastLandscape"
	o = append(o, 0xb1, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x73, 0x74, 0x4c, 0x61, 0x6e, 0x64, 0x73, 0x63, 0x61, 0x70, 0x65)
	o = msgp.AppendInt32(o, z.ContrastLandscape)
	// string "SharpnessLandscape"
	o = append(o, 0xb2, 0x53, 0x68, 0x61, 0x72, 0x70, 0x6e, 0x65, 0x73, 0x73, 0x4c, 0x61, 0x6e, 0x64, 0x73, 0x63, 0x61, 0x70, 0x65)
	o = msgp.AppendInt32(o, z.SharpnessLandscape)
	// string "SaturationLandscape"
	o = append(o, 0xb3, 0x53, 0x61, 0x74, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4c, 0x61, 0x6e, 0x64, 0x73, 0x63, 0x61, 0x70, 0x65)
	o = msgp.AppendInt32(o, z.SaturationLandscape)
	// string "ColorToneLandscape"
	o = append(o, 0xb2, 0x43, 0x6f, 0x6c, 0x6f, 0x72, 0x54, 0x6f, 0x6e, 0x65, 0x4c, 0x61, 0x6e, 0x64, 0x73, 0x63, 0x61, 0x70, 0x65)
	o = msgp.AppendInt32(o, z.ColorToneLandscape)
	// string "FilterEffectLandscape"
	o = append(o, 0xb5, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x45, 0x66, 0x66, 0x65, 0x63, 0x74, 0x4c, 0x61, 0x6e, 0x64, 0x73, 0x63, 0x61, 0x70, 0x65)
	o = msgp.AppendInt32(o, z.FilterEffectLandscape)
	// string "ToningEffectLandscape"
	o = append(o, 0xb5, 0x54, 0x6f, 0x6e, 0x69, 0x6e, 0x67, 0x45, 0x66, 0x66, 0x65, 0x63, 0x74, 0x4c, 0x61, 0x6e, 0x64, 0x73, 0x63, 0x61, 0x70, 0x65)
	o = msgp.AppendInt32(o, z.ToningEffectLandscape)
	// string "ContrastNeutral"
	o = append(o, 0xaf, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x73, 0x74, 0x4e, 0x65, 0x75, 0x74, 0x72, 0x61, 0x6c)
	o = msgp.AppendInt32(o, z.ContrastNeutral)
	// string "SharpnessNeutral"
	o = append(o, 0xb0, 0x53, 0x68, 0x61, 0x72, 0x70, 0x6e, 0x65, 0x73, 0x73, 0x4e, 0x65, 0x75, 0x74, 0x72, 0x61, 0x6c)
	o = msgp.AppendInt32(o, z.SharpnessNeutral)
	// string "SaturationNeutral"
	o = append(o, 0xb1, 0x53, 0x61, 0x74, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4e, 0x65, 0x75, 0x74, 0x72, 0x61, 0x6c)
	o = msgp.AppendInt32(o, z.SaturationNeutral)
	// string "ColorToneNeutral"
	o = append(o, 0xb0, 0x43, 0x6f, 0x6c, 0x6f, 0x72, 0x54, 0x6f, 0x6e, 0x65, 0x4e, 0x65, 0x75, 0x74, 0x72, 0x61, 0x6c)
	o = msgp.AppendInt32(o, z.ColorToneNeutral)
	// string "FilterEffectNeutral"
	o = append(o, 0xb3, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x45, 0x66, 0x66, 0x65, 0x63, 0x74, 0x4e, 0x65, 0x75, 0x74, 0x72, 0x61, 0x6c)
	o = msgp.AppendInt32(o, z.FilterEffectNeutral)
	// string "ToningEffectNeutral"
	o = append(o, 0xb3, 0x54, 0x6f, 0x6e, 0x69, 0x6e, 0x67, 0x45, 0x66, 0x66, 0x65, 0x63, 0x74, 0x4e, 0x65, 0x75, 0x74, 0x72, 0x61, 0x6c)
	o = msgp.AppendInt32(o, z.ToningEffectNeutral)
	// string "ContrastFaithful"
	o = append(o, 0xb0, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x73, 0x74, 0x46, 0x61, 0x69, 0x74, 0x68, 0x66, 0x75, 0x6c)
	o = msgp.AppendInt32(o, z.ContrastFaithful)
	// string "SharpnessFaithful"
	o = append(o, 0xb1, 0x53, 0x68, 0x61, 0x72, 0x70, 0x6e, 0x65, 0x73, 0x73, 0x46, 0x61, 0x69, 0x74, 0x68, 0x66, 0x75, 0x6c)
	o = msgp.AppendInt32(o, z.SharpnessFaithful)
	// string "SaturationFaithful"
	o = append(o, 0xb2, 0x53, 0x61, 0x74, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x46, 0x61, 0x69, 0x74, 0x68, 0x66, 0x75, 0x6c)
	o = msgp.AppendInt32(o, z.SaturationFaithful)
	// string "ColorToneFaithful"
	o = append(o, 0xb1, 0x43, 0x6f, 0x6c, 0x6f, 0x72, 0x54, 0x6f, 0x6e, 0x65, 0x46, 0x61, 0x69, 0x74, 0x68, 0x66, 0x75, 0x6c)
	o = msgp.AppendInt32(o, z.ColorToneFaithful)
	// string "FilterEffectFaithful"
	o = append(o, 0xb4, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x45, 0x66, 0x66, 0x65, 0x63, 0x74, 0x46, 0x61, 0x69, 0x74, 0x68, 0x66, 0x75, 0x6c)
	o = msgp.AppendInt32(o, z.FilterEffectFaithful)
	// string "ToningEffectFaithful"
	o = append(o, 0xb4, 0x54, 0x6f, 0x6e, 0x69, 0x6e, 0x67, 0x45, 0x66, 0x66, 0x65, 0x63, 0x74, 0x46, 0x61, 0x69, 0x74, 0x68, 0x66, 0x75, 0x6c)
	o = msgp.AppendInt32(o, z.ToningEffectFaithful)
	// string "ContrastMonochrome"
	o = append(o, 0xb2, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x73, 0x74, 0x4d, 0x6f, 0x6e, 0x6f, 0x63, 0x68, 0x72, 0x6f, 0x6d, 0x65)
	o = msgp.AppendInt32(o, z.ContrastMonochrome)
	// string "SharpnessMonochrome"
	o = append(o, 0xb3, 0x53, 0x68, 0x61, 0x72, 0x70, 0x6e, 0x65, 0x73, 0x73, 0x4d, 0x6f, 0x6e, 0x6f, 0x63, 0x68, 0x72, 0x6f, 0x6d, 0x65)
	o = msgp.AppendInt32(o, z.SharpnessMonochrome)
	// string "SaturationMonochrome"
	o = append(o, 0xb4, 0x53, 0x61, 0x74, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4d, 0x6f, 0x6e, 0x6f, 0x63, 0x68, 0x72, 0x6f, 0x6d, 0x65)
	o = msgp.AppendInt32(o, z.SaturationMonochrome)
	// string "ColorToneMonochrome"
	o = append(o, 0xb3, 0x43, 0x6f, 0x6c, 0x6f, 0x72, 0x54, 0x6f, 0x6e, 0x65, 0x4d, 0x6f, 0x6e, 0x6f, 0x63, 0x68, 0x72, 0x6f, 0x6d, 0x65)
	o = msgp.AppendInt32(o, z.ColorToneMonochrome)
	// string "FilterEffectMonochrome"
	o = append(o, 0xb6, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x45, 0x66, 0x66, 0x65, 0x63, 0x74, 0x4d, 0x6f, 0x6e, 0x6f, 0x63, 0x68, 0x72, 0x6f, 0x6d, 0x65)
	o = msgp.AppendInt32(o, int32(z.FilterEffectMonochrome))
	// string "ToningEffectMonochrome"
	o = append(o, 0xb6, 0x54, 0x6f, 0x6e, 0x69, 0x6e, 0x67, 0x45, 0x66, 0x66, 0x65, 0x63, 0x74, 0x4d, 0x6f, 0x6e, 0x6f, 0x63, 0x68, 0x72, 0x6f, 0x6d, 0x65)
	o = msgp.AppendInt32(o, int32(z.ToningEffectMonochrome))
	// string "ContrastAuto"
	o = append(o, 0xac, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x73, 0x74, 0x41, 0x75, 0x74, 0x6f)
	o = msgp.AppendInt32(o, z.ContrastAuto)
	// string "SharpnessAuto"
	o = append(o, 0xad, 0x53, 0x68, 0x61, 0x72, 0x70, 0x6e, 0x65, 0x73, 0x73, 0x41, 0x75, 0x74, 0x6f)
	o = msgp.AppendInt32(o, z.SharpnessAuto)
	// string "SaturationAuto"
	o = append(o, 0xae, 0x53, 0x61, 0x74, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x41, 0x75, 0x74, 0x6f)
	o = msgp.AppendInt32(o, z.SaturationAuto)
	// string "ColorToneAuto"
	o = append(o, 0xad, 0x43, 0x6f, 0x6c, 0x6f, 0x72, 0x54, 0x6f, 0x6e, 0x65, 0x41, 0x75, 0x74, 0x6f)
	o = msgp.AppendInt32(o, z.ColorToneAuto)
	// string "FilterEffectAuto"
	o = append(o, 0xb0, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x45, 0x66, 0x66, 0x65, 0x63, 0x74, 0x41, 0x75, 0x74, 0x6f)
	o = msgp.AppendInt32(o, int32(z.FilterEffectAuto))
	// string "ToningEffectAuto"
	o = append(o, 0xb0, 0x54, 0x6f, 0x6e, 0x69, 0x6e, 0x67, 0x45, 0x66, 0x66, 0x65, 0x63, 0x74, 0x41, 0x75, 0x74, 0x6f)
	o = msgp.AppendInt32(o, int32(z.ToningEffectAuto))
	// string "ContrastUserDef1"
	o = append(o, 0xb0, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x73, 0x74, 0x55, 0x73, 0x65, 0x72, 0x44, 0x65, 0x66, 0x31)
	o = msgp.AppendInt32(o, z.ContrastUserDef1)
	// string "SharpnessUserDef1"
	o = append(o, 0xb1, 0x53, 0x68, 0x61, 0x72, 0x70, 0x6e, 0x65, 0x73, 0x73, 0x55, 0x73, 0x65, 0x72, 0x44, 0x65, 0x66, 0x31)
	o = msgp.AppendInt32(o, z.SharpnessUserDef1)
	// string "SaturationUserDef1"
	o = append(o, 0xb2, 0x53, 0x61, 0x74, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x55, 0x73, 0x65, 0x72, 0x44, 0x65, 0x66, 0x31)
	o = msgp.AppendInt32(o, z.SaturationUserDef1)
	// string "ColorToneUserDef1"
	o = append(o, 0xb1, 0x43, 0x6f, 0x6c, 0x6f, 0x72, 0x54, 0x6f, 0x6e, 0x65, 0x55, 0x73, 0x65, 0x72, 0x44, 0x65, 0x66, 0x31)
	o = msgp.AppendInt32(o, z.ColorToneUserDef1)
	// string "FilterEffectUserDef1"
	o = append(o, 0xb4, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x45, 0x66, 0x66, 0x65, 0x63, 0x74, 0x55, 0x73, 0x65, 0x72, 0x44, 0x65, 0x66, 0x31)
	o = msgp.AppendInt32(o, int32(z.FilterEffectUserDef1))
	// string "ToningEffectUserDef1"
	o = append(o, 0xb4, 0x54, 0x6f, 0x6e, 0x69, 0x6e, 0x67, 0x45, 0x66, 0x66, 0x65, 0x63, 0x74, 0x55, 0x73, 0x65, 0x72, 0x44, 0x65, 0x66, 0x31)
	o = msgp.AppendInt32(o, int32(z.ToningEffectUserDef1))
	// string "ContrastUserDef2"
	o = append(o, 0xb0, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x73, 0x74, 0x55, 0x73, 0x65, 0x72, 0x44, 0x65, 0x66, 0x32)
	o = msgp.AppendInt32(o, z.ContrastUserDef2)
	// string "SharpnessUserDef2"
	o = append(o, 0xb1, 0x53, 0x68, 0x61, 0x72, 0x70, 0x6e, 0x65, 0x73, 0x73, 0x55, 0x73, 0x65, 0x72, 0x44, 0x65, 0x66, 0x32)
	o = msgp.AppendInt32(o, z.SharpnessUserDef2)
	// string "SaturationUserDef2"
	o = append(o, 0xb2, 0x53, 0x61, 0x74, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x55, 0x73, 0x65, 0x72, 0x44, 0x65, 0x66, 0x32)
	o = msgp.AppendInt32(o, z.SaturationUserDef2)
	// string "ColorToneUserDef2"
	o = append(o, 0xb1, 0x43, 0x6f, 0x6c, 0x6f, 0x72, 0x54, 0x6f, 0x6e, 0x65, 0x55, 0x73, 0x65, 0x72, 0x44, 0x65, 0x66, 0x32)
	o = msgp.AppendInt32(o, z.ColorToneUserDef2)
	// string "FilterEffectUserDef2"
	o = append(o, 0xb4, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x45, 0x66, 0x66, 0x65, 0x63, 0x74, 0x55, 0x73, 0x65, 0x72, 0x44, 0x65, 0x66, 0x32)
	o = msgp.AppendInt32(o, int32(z.FilterEffectUserDef2))
	// string "ToningEffectUserDef2"
	o = append(o, 0xb4, 0x54, 0x6f, 0x6e, 0x69, 0x6e, 0x67, 0x45, 0x66, 0x66, 0x65, 0x63, 0x74, 0x55, 0x73, 0x65, 0x72, 0x44, 0x65, 0x66, 0x32)
	o = msgp.AppendInt32(o, int32(z.ToningEffectUserDef2))
	// string "ContrastUserDef3"
	o = append(o, 0xb0, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x73, 0x74, 0x55, 0x73, 0x65, 0x72, 0x44, 0x65, 0x66, 0x33)
	o = msgp.AppendInt32(o, z.ContrastUserDef3)
	// string "SharpnessUserDef3"
	o = append(o, 0xb1, 0x53, 0x68, 0x61, 0x72, 0x70, 0x6e, 0x65, 0x73, 0x73, 0x55, 0x73, 0x65, 0x72, 0x44, 0x65, 0x66, 0x33)
	o = msgp.AppendInt32(o, z.SharpnessUserDef3)
	// string "SaturationUserDef3"
	o = append(o, 0xb2, 0x53, 0x61, 0x74, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x55, 0x73, 0x65, 0x72, 0x44, 0x65, 0x66, 0x33)
	o = msgp.AppendInt32(o, z.SaturationUserDef3)
	// string "ColorToneUserDef3"
	o = append(o, 0xb1, 0x43, 0x6f, 0x6c, 0x6f, 0x72, 0x54, 0x6f, 0x6e, 0x65, 0x55, 0x73, 0x65, 0x72, 0x44, 0x65, 0x66, 0x33)
	o = msgp.AppendInt32(o, z.ColorToneUserDef3)
	// string "FilterEffectUserDef3"
	o = append(o, 0xb4, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x45, 0x66, 0x66, 0x65, 0x63, 0x74, 0x55, 0x73, 0x65, 0x72, 0x44, 0x65, 0x66, 0x33)
	o = msgp.AppendInt32(o, int32(z.FilterEffectUserDef3))
	// string "ToningEffectUserDef3"
	o = append(o, 0xb4, 0x54, 0x6f, 0x6e, 0x69, 0x6e, 0x67, 0x45, 0x66, 0x66, 0x65, 0x63, 0x74, 0x55, 0x73, 0x65, 0x72, 0x44, 0x65, 0x66, 0x33)
	o = msgp.AppendInt32(o, int32(z.ToningEffectUserDef3))
	// string "UserDef1PictureStyle"
	o = append(o, 0xb4, 0x55, 0x73, 0x65, 0x72, 0x44, 0x65, 0x66, 0x31, 0x50, 0x69, 0x63, 0x74, 0x75, 0x72, 0x65, 0x53, 0x74, 0x79, 0x6c, 0x65)
	o = msgp.AppendUint16(o, z.UserDef1PictureStyle)
	// string "UserDef2PictureStyle"
	o = append(o, 0xb4, 0x55, 0x73, 0x65, 0x72, 0x44, 0x65, 0x66, 0x32, 0x50, 0x69, 0x63, 0x74, 0x75, 0x72, 0x65, 0x53, 0x74, 0x79, 0x6c, 0x65)
	o = msgp.AppendUint16(o, z.UserDef2PictureStyle)
	// string "UserDef3PictureStyle"
	o = append(o, 0xb4, 0x55, 0x73, 0x65, 0x72, 0x44, 0x65, 0x66, 0x33, 0x50, 0x69, 0x63, 0x74, 0x75, 0x72, 0x65, 0x53, 0x74, 0x79, 0x6c, 0x65)
	o = msgp.AppendUint16(o, z.UserDef3PictureStyle)
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *PictureStyleInfo2) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "ContrastStandard":
			z.ContrastStandard, bts, err = msgp.ReadInt32Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "ContrastStandard")
				return
			}
		case "SharpnessStandard":
			z.SharpnessStandard, bts, err = msgp.ReadInt32Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "SharpnessStandard")
				return
			}
		case "SaturationStandard":
			z.SaturationStandard, bts, err = msgp.ReadInt32Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "SaturationStandard")
				return
			}
		case "ColorToneStandard":
			z.ColorToneStandard, bts, err = msgp.ReadInt32Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "ColorToneStandard")
				return
			}
		case "FilterEffectStandard":
			z.FilterEffectStandard, bts, err = msgp.ReadInt32Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "FilterEffectStandard")
				return
			}
		case "ToningEffectStandard":
			z.ToningEffectStandard, bts, err = msgp.ReadInt32Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "ToningEffectStandard")
				return
			}
		case "ContrastPortrait":
			z.ContrastPortrait, bts, err = msgp.ReadInt32Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "ContrastPortrait")
				return
			}
		case "SharpnessPortrait":
			z.SharpnessPortrait, bts, err = msgp.ReadInt32Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "SharpnessPortrait")
				return
			}
		case "SaturationPortrait":
			z.SaturationPortrait, bts, err = msgp.ReadInt32Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "SaturationPortrait")
				return
			}
		case "ColorTonePortrait":
			z.ColorTonePortrait, bts, err = msgp.ReadInt32Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "ColorTonePortrait")
				return
			}
		case "FilterEffectPortrait":
			z.FilterEffectPortrait, bts, err = msgp.ReadInt32Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "FilterEffectPortrait")
				return
			}
		case "ToningEffectPortrait":
			z.ToningEffectPortrait, bts, err = msgp.ReadInt32Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "ToningEffectPortrait")
				return
			}
		case "ContrastLandscape":
			z.ContrastLandscape, bts, err = msgp.ReadInt32Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "ContrastLandscape")
				return
			}
		case "SharpnessLandscape":
			z.SharpnessLandscape, bts, err = msgp.ReadInt32Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "SharpnessLandscape")
				return
			}
		case "SaturationLandscape":
			z.SaturationLandscape, bts, err = msgp.ReadInt32Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "SaturationLandscape")
				return
			}
		case "ColorToneLandscape":
			z.ColorToneLandscape, bts, err = msgp.ReadInt32Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "ColorToneLandscape")
				return
			}
		case "FilterEffectLandscape":
			z.FilterEffectLandscape, bts, err = msgp.ReadInt32Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "FilterEffectLandscape")
				return
			}
		case "ToningEffectLandscape":
			z.ToningEffectLandscape, bts, err = msgp.ReadInt32Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "ToningEffectLandscape")
				return
			}
		case "ContrastNeutral":
			z.ContrastNeutral, bts, err = msgp.ReadInt32Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "ContrastNeutral")
				return
			}
		case "SharpnessNeutral":
			z.SharpnessNeutral, bts, err = msgp.ReadInt32Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "SharpnessNeutral")
				return
			}
		case "SaturationNeutral":
			z.SaturationNeutral, bts, err = msgp.ReadInt32Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "SaturationNeutral")
				return
			}
		case "ColorToneNeutral":
			z.ColorToneNeutral, bts, err = msgp.ReadInt32Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "ColorToneNeutral")
				return
			}
		case "FilterEffectNeutral":
			z.FilterEffectNeutral, bts, err = msgp.ReadInt32Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "FilterEffectNeutral")
				return
			}
		case "ToningEffectNeutral":
			z.ToningEffectNeutral, bts, err = msgp.ReadInt32Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "ToningEffectNeutral")
				return
			}
		case "ContrastFaithful":
			z.ContrastFaithful, bts, err = msgp.ReadInt32Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "ContrastFaithful")
				return
			}
		case "SharpnessFaithful":
			z.SharpnessFaithful, bts, err = msgp.ReadInt32Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "SharpnessFaithful")
				return
			}
		case "SaturationFaithful":
			z.SaturationFaithful, bts, err = msgp.ReadInt32Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "SaturationFaithful")
				return
			}
		case "ColorToneFaithful":
			z.ColorToneFaithful, bts, err = msgp.ReadInt32Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "ColorToneFaithful")
				return
			}
		case "FilterEffectFaithful":
			z.FilterEffectFaithful, bts, err = msgp.ReadInt32Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "FilterEffectFaithful")
				return
			}
		case "ToningEffectFaithful":
			z.ToningEffectFaithful, bts, err = msgp.ReadInt32Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "ToningEffectFaithful")
				return
			}
		case "ContrastMonochrome":
			z.ContrastMonochrome, bts, err = msgp.ReadInt32Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "ContrastMonochrome")
				return
			}
		case "SharpnessMonochrome":
			z.SharpnessMonochrome, bts, err = msgp.ReadInt32Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "SharpnessMonochrome")
				return
			}
		case "SaturationMonochrome":
			z.SaturationMonochrome, bts, err = msgp.ReadInt32Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "SaturationMonochrome")
				return
			}
		case "ColorToneMonochrome":
			z.ColorToneMonochrome, bts, err = msgp.ReadInt32Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "ColorToneMonochrome")
				return
			}
		case "FilterEffectMonochrome":
			{
				var zb0002 int32
				zb0002, bts, err = msgp.ReadInt32Bytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "FilterEffectMonochrome")
					return
				}
				z.FilterEffectMonochrome = FilterEffect(zb0002)
			}
		case "ToningEffectMonochrome":
			{
				var zb0003 int32
				zb0003, bts, err = msgp.ReadInt32Bytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "ToningEffectMonochrome")
					return
				}
				z.ToningEffectMonochrome = ToningEffect(zb0003)
			}
		case "ContrastAuto":
			z.ContrastAuto, bts, err = msgp.ReadInt32Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "ContrastAuto")
				return
			}
		case "SharpnessAuto":
			z.SharpnessAuto, bts, err = msgp.ReadInt32Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "SharpnessAuto")
				return
			}
		case "SaturationAuto":
			z.SaturationAuto, bts, err = msgp.ReadInt32Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "SaturationAuto")
				return
			}
		case "ColorToneAuto":
			z.ColorToneAuto, bts, err = msgp.ReadInt32Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "ColorToneAuto")
				return
			}
		case "FilterEffectAuto":
			{
				var zb0004 int32
				zb0004, bts, err = msgp.ReadInt32Bytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "FilterEffectAuto")
					return
				}
				z.FilterEffectAuto = FilterEffect(zb0004)
			}
		case "ToningEffectAuto":
			{
				var zb0005 int32
				zb0005, bts, err = msgp.ReadInt32Bytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "ToningEffectAuto")
					return
				}
				z.ToningEffectAuto = ToningEffect(zb0005)
			}
		case "ContrastUserDef1":
			z.ContrastUserDef1, bts, err = msgp.ReadInt32Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "ContrastUserDef1")
				return
			}
		case "SharpnessUserDef1":
			z.SharpnessUserDef1, bts, err = msgp.ReadInt32Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "SharpnessUserDef1")
				return
			}
		case "SaturationUserDef1":
			z.SaturationUserDef1, bts, err = msgp.ReadInt32Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "SaturationUserDef1")
				return
			}
		case "ColorToneUserDef1":
			z.ColorToneUserDef1, bts, err = msgp.ReadInt32Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "ColorToneUserDef1")
				return
			}
		case "FilterEffectUserDef1":
			{
				var zb0006 int32
				zb0006, bts, err = msgp.ReadInt32Bytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "FilterEffectUserDef1")
					return
				}
				z.FilterEffectUserDef1 = FilterEffect(zb0006)
			}
		case "ToningEffectUserDef1":
			{
				var zb0007 int32
				zb0007, bts, err = msgp.ReadInt32Bytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "ToningEffectUserDef1")
					return
				}
				z.ToningEffectUserDef1 = ToningEffect(zb0007)
			}
		case "ContrastUserDef2":
			z.ContrastUserDef2, bts, err = msgp.ReadInt32Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "ContrastUserDef2")
				return
			}
		case "SharpnessUserDef2":
			z.SharpnessUserDef2, bts, err = msgp.ReadInt32Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "SharpnessUserDef2")
				return
			}
		case "SaturationUserDef2":
			z.SaturationUserDef2, bts, err = msgp.ReadInt32Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "SaturationUserDef2")
				return
			}
		case "ColorToneUserDef2":
			z.ColorToneUserDef2, bts, err = msgp.ReadInt32Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "ColorToneUserDef2")
				return
			}
		case "FilterEffectUserDef2":
			{
				var zb0008 int32
				zb0008, bts, err = msgp.ReadInt32Bytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "FilterEffectUserDef2")
					return
				}
				z.FilterEffectUserDef2 = FilterEffect(zb0008)
			}
		case "ToningEffectUserDef2":
			{
				var zb0009 int32
				zb0009, bts, err = msgp.ReadInt32Bytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "ToningEffectUserDef2")
					return
				}
				z.ToningEffectUserDef2 = ToningEffect(zb0009)
			}
		case "ContrastUserDef3":
			z.ContrastUserDef3, bts, err = msgp.ReadInt32Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "ContrastUserDef3")
				return
			}
		case "SharpnessUserDef3":
			z.SharpnessUserDef3, bts, err = msgp.ReadInt32Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "SharpnessUserDef3")
				return
			}
		case "SaturationUserDef3":
			z.SaturationUserDef3, bts, err = msgp.ReadInt32Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "SaturationUserDef3")
				return
			}
		case "ColorToneUserDef3":
			z.ColorToneUserDef3, bts, err = msgp.ReadInt32Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "ColorToneUserDef3")
				return
			}
		case "FilterEffectUserDef3":
			{
				var zb0010 int32
				zb0010, bts, err = msgp.ReadInt32Bytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "FilterEffectUserDef3")
					return
				}
				z.FilterEffectUserDef3 = FilterEffect(zb0010)
			}
		case "ToningEffectUserDef3":
			{
				var zb0011 int32
				zb0011, bts, err = msgp.ReadInt32Bytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "ToningEffectUserDef3")
					return
				}
				z.ToningEffectUserDef3 = ToningEffect(zb0011)
			}
		case "UserDef1PictureStyle":
			z.UserDef1PictureStyle, bts, err = msgp.ReadUint16Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "UserDef1PictureStyle")
				return
			}
		case "UserDef2PictureStyle":
			z.UserDef2PictureStyle, bts, err = msgp.ReadUint16Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "UserDef2PictureStyle")
				return
			}
		case "UserDef3PictureStyle":
			z.UserDef3PictureStyle, bts, err = msgp.ReadUint16Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "UserDef3PictureStyle")
				return
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *PictureStyleInfo2) Msgsize() (s int) {
	s = 3 + 17 + msgp.Int32Size + 18 + msgp.Int32Size + 19 + msgp.Int32Size + 18 + msgp.Int32Size + 21 + msgp.Int32Size + 21 + msgp.Int32Size + 17 + msgp.Int32Size + 18 + msgp.Int32Size + 19 + msgp.Int32Size + 18 + msgp.Int32Size + 21 + msgp.Int32Size + 21 + msgp.Int32Size + 18 + msgp.Int32Size + 19 + msgp.Int32Size + 20 + msgp.Int32Size + 19 + msgp.Int32Size + 22 + msgp.Int32Size + 22 + msgp.Int32Size + 16 + msgp.Int32Size + 17 + msgp.Int32Size + 18 + msgp.Int32Size + 17 + msgp.Int32Size + 20 + msgp.Int32Size + 20 + msgp.Int32Size + 17 + msgp.Int32Size + 18 + msgp.Int32Size + 19 + msgp.Int32Size + 18 + msgp.Int32Size + 21 + msgp.Int32Size + 21 + msgp.Int32Size + 19 + msgp.Int32Size + 20 + msgp.Int32Size + 21 + msgp.Int32Size + 20 + msgp.Int32Size + 23 + msgp.Int32Size + 23 + msgp.Int32Size + 13 + msgp.Int32Size + 14 + msgp.Int32Size + 15 + msgp.Int32Size + 14 + msgp.Int32Size + 17 + msgp.Int32Size + 17 + msgp.Int32Size + 17 + msgp.Int32Size + 18 + msgp.Int32Size + 19 + msgp.Int32Size + 18 + msgp.Int32Size + 21 + msgp.Int32Size + 21 + msgp.Int32Size + 17 + msgp.Int32Size + 18 + msgp.Int32Size + 19 + msgp.Int32Size + 18 + msgp.Int32Size + 21 + msgp.Int32Size + 21 + msgp.Int32Size + 17 + msgp.Int32Size + 18 + msgp.Int32Size + 19 + msgp.Int32Size + 18 + msgp.Int32Size + 21 + msgp.Int32Size + 21 + msgp.Int32Size + 21 + msgp.Uint16Size + 21 + msgp.Uint16Size + 21 + msgp.Uint16Size
	return
}

// DecodeMsg implements msgp.Decodable
func (z *ToningEffect) DecodeMsg(dc *msgp.Reader) (err error) {
	{
		var zb0001 int32
		zb0001, err = dc.ReadInt32()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		(*z) = ToningEffect(zb0001)
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z ToningEffect) EncodeMsg(en *msgp.Writer) (err error) {
	err = en.WriteInt32(int32(z))
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z ToningEffect) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	o = msgp.AppendInt32(o, int32(z))
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *ToningEffect) UnmarshalMsg(bts []byte) (o []byte, err error) {
	{
		var zb0001 int32
		zb0001, bts, err = msgp.ReadInt32Bytes(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		(*z) = ToningEffect(zb0001)
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z ToningEffect) Msgsize() (s int) {
	s = msgp.Int32Size
	return
}
