// Code generated by "stringer -type=MakerNoteTag -linecomment -output=makernote_tags_string.go"; DO NOT EDIT.

package canon

import (
	"strconv"
)

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[CanonCameraSettings-1]
	_ = x[CanonFocalLength-2]
	_ = x[CanonFlashInfo-3]
	_ = x[CanonShotInfo-4]
	_ = x[CanonPanorama-5]
	_ = x[CanonImageType-6]
	_ = x[CanonFirmwareVersion-7]
	_ = x[FileNumber-8]
	_ = x[OwnerName-9]
	_ = x[UnknownD30-10]
	_ = x[SerialNumber-12]
	_ = x[CanonCameraInfo-13]
	_ = x[CanonFileLength-14]
	_ = x[CustomFunctions-15]
	_ = x[CanonModelID-16]
	_ = x[MovieInfo-17]
	_ = x[CanonAFInfo-18]
	_ = x[ThumbnailImageValidArea-19]
	_ = x[SerialNumberFormat-21]
	_ = x[SuperMacro-26]
	_ = x[DateStampMode-28]
	_ = x[MyColors-29]
	_ = x[FirmwareRevision-30]
	_ = x[Categories-35]
	_ = x[FaceDetect1-36]
	_ = x[FaceDetect2-37]
	_ = x[CanonAFInfo2-38]
	_ = x[ContrastInfo-39]
	_ = x[ImageUniqueID-40]
	_ = x[WBInfo-41]
	_ = x[FaceDetect3-47]
	_ = x[TimeInfo-53]
	_ = x[BatteryType-56]
	_ = x[AFInfo3-60]
	_ = x[RawDataOffset-129]
	_ = x[RawDataLength-130]
	_ = x[OriginalDecisionDataOffset-131]
	_ = x[CustomFunctions1D-144]
	_ = x[PersonalFunctions-145]
	_ = x[PersonalFunctionValues-146]
	_ = x[CanonFileInfo-147]
	_ = x[AFPointsInFocus1D-148]
	_ = x[LensModel-149]
	_ = x[CanonInternalSerialNumber-150]
	_ = x[CanonDustRemovalData-151]
	_ = x[CanonCropInfo-152]
	_ = x[CanonCustomFunctions-153]
	_ = x[CanonAspectInfo-154]
	_ = x[CanonProcessingInfo-160]
	_ = x[CanonColorBalance-169]
	_ = x[CanonMeasuredColor-170]
	_ = x[CanonColorTemperature-174]
	_ = x[CanonCanonFlags-176]
	_ = x[CanonModifiedInfo-177]
	_ = x[CanonColorSpace-180]
	_ = x[CanonPreviewImageInfo-182]
	_ = x[CanonVRDOffset-208]
	_ = x[CanonSensorInfo-224]
	_ = x[CanonColorData-16385]
	_ = x[CanonCRWParam-16386]
	_ = x[CanonColorInfo-16387]
	_ = x[CanonFlavor-16389]
	_ = x[CanonPictureStyleUserDef-16392]
	_ = x[CanonPictureStylePC-16393]
	_ = x[CanonCustomPictureStyleFileName-16400]
	_ = x[CanonAFMicroAdj-16403]
	_ = x[CanonVignettingCorr-16405]
	_ = x[CanonVignettingCorr2-16406]
	_ = x[CanonLightingOpt-16408]
	_ = x[CanonLensInfo-16409]
	_ = x[CanonAmbienceInfo-16416]
	_ = x[CanonMultiExp-16417]
	_ = x[CanonFilterInfo-16420]
	_ = x[CanonHDRInfo-16421]
	_ = x[CanonLogInfo-16422]
	_ = x[CanonAFConfig-16424]
	_ = x[CanonRawBurstModeRoll-16447]
	_ = x[CanonLevelInfo-16473]
}

const _MakerNoteTag_name = "CanonCameraSettingsCanonFocalLengthCanonFlashInfoCanonShotInfoCanonPanoramaCanonImageTypeCanonFirmwareVersionFileNumberOwnerNameUnknownD30SerialNumberCanonCameraInfoCanonFileLengthCustomFunctionsCanonModelIDMovieInfoCanonAFInfoThumbnailImageValidAreaSerialNumberFormatSuperMacroDateStampModeMyColorsFirmwareRevisionCategoriesFaceDetect1FaceDetect2CanonAFInfo2ContrastInfoImageUniqueIDWBInfoFaceDetect3TimeInfoBatteryTypeAFInfo3RawDataOffsetRawDataLengthOriginalDecisionDataOffsetCustomFunctions1DPersonalFunctionsPersonalFunctionValuesCanonFileInfoAFPointsInFocus1DLensModelInternalSerialNumberDustRemovalDataCropInfoCustomFunctions2AspectInfoProcessingInfoColorBalanceMeasuredColorColorTemperatureCanonFlagsModifiedInfoColorSpacePreviewImageInfoVRDOffsetSensorInfoColorDataCRWParamColorInfoFlavorPictureStyleUserDefPictureStylePCCustomPictureStyleFileNameAFMicroAdjVignettingCorrVignettingCorr2LightingOptLensInfoAmbienceInfoMultiExpFilterInfoHDRInfoLogInfoAFConfigRawBurstModeRollLevelInfo"

var _MakerNoteTag_map = map[MakerNoteTag]string{
	1:     _MakerNoteTag_name[0:19],
	2:     _MakerNoteTag_name[19:35],
	3:     _MakerNoteTag_name[35:49],
	4:     _MakerNoteTag_name[49:62],
	5:     _MakerNoteTag_name[62:75],
	6:     _MakerNoteTag_name[75:89],
	7:     _MakerNoteTag_name[89:109],
	8:     _MakerNoteTag_name[109:119],
	9:     _MakerNoteTag_name[119:128],
	10:    _MakerNoteTag_name[128:138],
	12:    _MakerNoteTag_name[138:150],
	13:    _MakerNoteTag_name[150:165],
	14:    _MakerNoteTag_name[165:180],
	15:    _MakerNoteTag_name[180:195],
	16:    _MakerNoteTag_name[195:207],
	17:    _MakerNoteTag_name[207:216],
	18:    _MakerNoteTag_name[216:227],
	19:    _MakerNoteTag_name[227:250],
	21:    _MakerNoteTag_name[250:268],
	26:    _MakerNoteTag_name[268:278],
	28:    _MakerNoteTag_name[278:291],
	29:    _MakerNoteTag_name[291:299],
	30:    _MakerNoteTag_name[299:315],
	35:    _MakerNoteTag_name[315:325],
	36:    _MakerNoteTag_name[325:336],
	37:    _MakerNoteTag_name[336:347],
	38:    _MakerNoteTag_name[347:359],
	39:    _MakerNoteTag_name[359:371],
	40:    _MakerNoteTag_name[371:384],
	41:    _MakerNoteTag_name[384:390],
	47:    _MakerNoteTag_name[390:401],
	53:    _MakerNoteTag_name[401:409],
	56:    _MakerNoteTag_name[409:420],
	60:    _MakerNoteTag_name[420:427],
	129:   _MakerNoteTag_name[427:440],
	130:   _MakerNoteTag_name[440:453],
	131:   _MakerNoteTag_name[453:479],
	144:   _MakerNoteTag_name[479:496],
	145:   _MakerNoteTag_name[496:513],
	146:   _MakerNoteTag_name[513:535],
	147:   _MakerNoteTag_name[535:548],
	148:   _MakerNoteTag_name[548:565],
	149:   _MakerNoteTag_name[565:574],
	150:   _MakerNoteTag_name[574:594],
	151:   _MakerNoteTag_name[594:609],
	152:   _MakerNoteTag_name[609:617],
	153:   _MakerNoteTag_name[617:633],
	154:   _MakerNoteTag_name[633:643],
	160:   _MakerNoteTag_name[643:657],
	169:   _MakerNoteTag_name[657:669],
	170:   _MakerNoteTag_name[669:682],
	174:   _MakerNoteTag_name[682:698],
	176:   _MakerNoteTag_name[698:708],
	177:   _MakerNoteTag_name[708:720],
	180:   _MakerNoteTag_name[720:730],
	182:   _MakerNoteTag_name[730:746],
	208:   _MakerNoteTag_name[746:755],
	224:   _MakerNoteTag_name[755:765],
	16385: _MakerNoteTag_name[765:774],
	16386: _MakerNoteTag_name[774:782],
	16387: _MakerNoteTag_name[782:791],
	16389: _MakerNoteTag_name[791:797],
	16392: _MakerNoteTag_name[797:816],
	16393: _MakerNoteTag_name[816:830],
	16400: _MakerNoteTag_name[830:856],
	16403: _MakerNoteTag_name[856:866],
	16405: _MakerNoteTag_name[866:880],
	16406: _MakerNoteTag_name[880:895],
	16408: _MakerNoteTag_name[895:906],
	16409: _MakerNoteTag_name[906:914],
	16416: _MakerNoteTag_name[914:926],
	16417: _MakerNoteTag_name[926:934],
	16420: _MakerNoteTag_name[934:944],
	16421: _MakerNoteTag_name[944:951],
	16422: _MakerNoteTag_name[951:958],
	16424: _MakerNoteTag_name[958:966],
	16447: _MakerNoteTag_name[966:982],
	16473: _MakerNoteTag_name[982:991],
}

func (i MakerNoteTag) String() string {
	if str, ok := _MakerNoteTag_map[i]; ok {
		return str
	}
	return "MakerNoteTag(" + strconv.FormatInt(int64(i), 10) + ")"
}
