package canon

import "fmt"

var (
	_ fmt.Stringer = MacroMode(0)
	_ fmt.Stringer = Quality(0)
	_ fmt.Stringer = CanonFlashMode(0)
	_ fmt.Stringer = ContinuousDrive(0)
	_ fmt.Stringer = FocusMode(0)
	_ fmt.Stringer = RecordMode(0)
	_ fmt.Stringer = CanonImageSize(0)
	_ fmt.Stringer = EasyMode(0)
	_ fmt.Stringer = DigitalZoom(0)
	_ fmt.Stringer = CameraISO(0)
	_ fmt.Stringer = MeteringMode(0)
	_ fmt.Stringer = FocusRange(0)
	_ fmt.Stringer = ExposureMode(0)
	_ fmt.Stringer = FlashModel(0)
	_ fmt.Stringer = FocusContinuous(0)
	_ fmt.Stringer = BracketMode(0)
	_ fmt.Stringer = ImageStabilization(0)
	_ fmt.Stringer = SpotMeteringMode(0)
	_ fmt.Stringer = PhotoEffect(0)
	_ fmt.Stringer = ManualFlashOutput(0)
	_ fmt.Stringer = SRAWQuality(0)
	_ fmt.Stringer = FocusBracketing(0)
	_ fmt.Stringer = HDRPQ(0)
	_ fmt.Stringer = OnOffAuto(0)
	_ fmt.Stringer = FilterEffect(0)
	_ fmt.Stringer = ToningEffect(0)
	_ fmt.Stringer = ShutterMode(0)
	_ fmt.Stringer = RawJpgQuality(0)
	_ fmt.Stringer = RawJpgSize(0)
	_ fmt.Stringer = TimeZoneCity(0)
	_ fmt.Stringer = DaylightSavings(0)
	_ fmt.Stringer = AESetting(0)
	_ fmt.Stringer = AFAreaMode(0)
	_ fmt.Stringer = CanonRFLensType(0)
)
