package sony

import "github.com/evanoberholster/imagemeta/meta/exif/tag"

// MakerNoteTag is a Sony maker-note tag ID from ExifTool Sony::Main table.
//
// Source:
//   - ExifTool 13.50
//   - /usr/share/perl5/Image/ExifTool/Sony.pm
//   - %Image::ExifTool::Sony::Main
type MakerNoteTag = tag.ID

// Sony maker-note Main-table tag IDs.
const (
	CameraInfo                    MakerNoteTag = 0x0010 // CameraInfo (sub-dir)
	FocusInfo                     MakerNoteTag = 0x0020 // FocusInfo (sub-dir)
	Quality                       MakerNoteTag = 0x0102 // Quality (int32u)
	FlashExposureComp             MakerNoteTag = 0x0104 // FlashExposureComp (rational64s)
	Teleconverter                 MakerNoteTag = 0x0105 // Teleconverter (int32u)
	WhiteBalanceFineTune          MakerNoteTag = 0x0112 // WhiteBalanceFineTune (int32s)
	CameraSettings                MakerNoteTag = 0x0114 // CameraSettings (sub-dir)
	WhiteBalance                  MakerNoteTag = 0x0115 // WhiteBalance (int32u)
	ExtraInfo                     MakerNoteTag = 0x0116 // ExtraInfo (sub-dir)
	PrintIM                       MakerNoteTag = 0x0e00 // PrintIM (sub-dir)
	MultiBurstMode                MakerNoteTag = 0x1000 // MultiBurstMode (undef)
	MultiBurstImageWidth          MakerNoteTag = 0x1001 // MultiBurstImageWidth (int16u)
	MultiBurstImageHeight         MakerNoteTag = 0x1002 // MultiBurstImageHeight (int16u)
	Panorama                      MakerNoteTag = 0x1003 // Panorama (sub-dir)
	PreviewImage                  MakerNoteTag = 0x2001 // PreviewImage (undef)
	Rating                        MakerNoteTag = 0x2002 // Rating (int32u)
	Contrast                      MakerNoteTag = 0x2004 // Contrast (int32s)
	Saturation                    MakerNoteTag = 0x2005 // Saturation (int32s)
	Sharpness                     MakerNoteTag = 0x2006 // Sharpness (int32s)
	Brightness                    MakerNoteTag = 0x2007 // Brightness (int32s)
	LongExposureNoiseReduction    MakerNoteTag = 0x2008 // LongExposureNoiseReduction (int32u)
	HighISONoiseReduction         MakerNoteTag = 0x2009 // HighISONoiseReduction (int16u)
	HDR                           MakerNoteTag = 0x200a // HDR (int32u)
	MultiFrameNoiseReduction      MakerNoteTag = 0x200b // MultiFrameNoiseReduction (int32u)
	PictureEffect                 MakerNoteTag = 0x200e // PictureEffect (int16u)
	SoftSkinEffect                MakerNoteTag = 0x200f // SoftSkinEffect (int32u)
	Tag2010a                      MakerNoteTag = 0x2010 // Tag2010 (sub-dir)
	VignettingCorrection          MakerNoteTag = 0x2011 // VignettingCorrection (int32u)
	LateralChromaticAberration    MakerNoteTag = 0x2012 // LateralChromaticAberration (int32u)
	DistortionCorrectionSetting   MakerNoteTag = 0x2013 // DistortionCorrectionSetting (int32u)
	WBShiftABGM                   MakerNoteTag = 0x2014 // WBShiftAB_GM (int32s[2])
	AutoPortraitFramed            MakerNoteTag = 0x2016 // AutoPortraitFramed (int16u)
	FlashAction                   MakerNoteTag = 0x2017 // FlashAction (int32u)
	ElectronicFrontCurtainShutter MakerNoteTag = 0x201a // ElectronicFrontCurtainShutter (int32u)
	FocusMode                     MakerNoteTag = 0x201b // FocusMode (int8u)
	AFAreaModeSetting             MakerNoteTag = 0x201c // AFAreaModeSetting (int8u)
	FlexibleSpotPosition          MakerNoteTag = 0x201d // FlexibleSpotPosition (int16u[2])
	AFPointSelected               MakerNoteTag = 0x201e // AFPointSelected (int8u)
	AFPointsUsed                  MakerNoteTag = 0x2020 // AFPointsUsed (no)
	AFTracking                    MakerNoteTag = 0x2021 // AFTracking (int8u)
	FocalPlaneAFPointsUsed        MakerNoteTag = 0x2022 // FocalPlaneAFPointsUsed (no)
	MultiFrameNREffect            MakerNoteTag = 0x2023 // MultiFrameNREffect (int32u)
	WBShiftABGMPrecise            MakerNoteTag = 0x2026 // WBShiftAB_GM_Precise (int32s[2])
	FocusLocation                 MakerNoteTag = 0x2027 // FocusLocation (int16u[4])
	VariableLowPassFilter         MakerNoteTag = 0x2028 // VariableLowPassFilter (int16u[2])
	RAWFileType                   MakerNoteTag = 0x2029 // RAWFileType (int16u)
	Tag202a                       MakerNoteTag = 0x202a // Tag202a (sub-dir)
	PrioritySetInAWB              MakerNoteTag = 0x202b // PrioritySetInAWB (int8u)
	MeteringMode2                 MakerNoteTag = 0x202c // MeteringMode2 (int16u)
	ExposureStandardAdjustment    MakerNoteTag = 0x202d // ExposureStandardAdjustment (rational64s)
	Quality2                      MakerNoteTag = 0x202e // Quality (int16u[2])
	PixelShiftInfo                MakerNoteTag = 0x202f // PixelShiftInfo (undef)
	SerialNumber                  MakerNoteTag = 0x2031 // SerialNumber (string)
	Shadows                       MakerNoteTag = 0x2032 // Shadows (int32s)
	Highlights                    MakerNoteTag = 0x2033 // Highlights (int32s)
	Fade                          MakerNoteTag = 0x2034 // Fade (int32s)
	SharpnessRange                MakerNoteTag = 0x2035 // SharpnessRange (int32s)
	Clarity                       MakerNoteTag = 0x2036 // Clarity (int32s)
	FocusFrameSize                MakerNoteTag = 0x2037 // FocusFrameSize (no)
	JPEGHEIFSwitch                MakerNoteTag = 0x2039 // JPEG-HEIFSwitch (int16u)
	HiddenInfo                    MakerNoteTag = 0x2044 // HiddenInfo (sub-dir)
	FocusLocation2                MakerNoteTag = 0x204a // FocusLocation2 (int16u[4])
	StepCropShooting              MakerNoteTag = 0x205c // StepCropShooting (int8u)
	ShotInfo                      MakerNoteTag = 0x3000 // ShotInfo (sub-dir)
	Tag900b                       MakerNoteTag = 0x900b // Tag900b (sub-dir)
	Tag9050a                      MakerNoteTag = 0x9050 // Tag9050 (sub-dir)
	Tag9400a                      MakerNoteTag = 0x9400 // Tag9400 (sub-dir)
	Tag9401                       MakerNoteTag = 0x9401 // Tag9401 (sub-dir)
	Tag9402                       MakerNoteTag = 0x9402 // Tag9402 (sub-dir)
	Tag9403                       MakerNoteTag = 0x9403 // Tag9403 (sub-dir)
	Tag9404a                      MakerNoteTag = 0x9404 // Tag9404 (sub-dir)
	Tag9405a                      MakerNoteTag = 0x9405 // Tag9405 (sub-dir)
	Tag9406                       MakerNoteTag = 0x9406 // Tag9406 (sub-dir)
	Sony0x9407                    MakerNoteTag = 0x9407 // Sony_0x9407 (undef)
	Sony0x9408                    MakerNoteTag = 0x9408 // Sony_0x9408 (undef)
	Sony0x9409                    MakerNoteTag = 0x9409 // Sony_0x9409 (undef)
	Tag940a                       MakerNoteTag = 0x940a // Tag940a (sub-dir)
	Sony0x940b                    MakerNoteTag = 0x940b // Sony_0x940b (undef)
	Tag940c                       MakerNoteTag = 0x940c // Tag940c (sub-dir)
	Sony0x940d                    MakerNoteTag = 0x940d // Sony_0x940d (undef)
	AFInfo                        MakerNoteTag = 0x940e // AFInfo (sub-dir)
	Sony0x940f                    MakerNoteTag = 0x940f // Sony_0x940f (undef)
	Sony0x9411                    MakerNoteTag = 0x9411 // Sony_0x9411 (undef)
	Sony0x9416                    MakerNoteTag = 0x9416 // Sony_0x9416 (undef)
	FileFormat                    MakerNoteTag = 0xb000 // FileFormat (int8u[4])
	SonyModelID                   MakerNoteTag = 0xb001 // SonyModelID (int16u)
	CreativeStyle                 MakerNoteTag = 0xb020 // CreativeStyle (string)
	ColorTemperature              MakerNoteTag = 0xb021 // ColorTemperature (int32u)
	ColorCompensationFilter       MakerNoteTag = 0xb022 // ColorCompensationFilter (int32s)
	SceneMode                     MakerNoteTag = 0xb023 // SceneMode (int32u)
	ZoneMatching                  MakerNoteTag = 0xb024 // ZoneMatching (int32u)
	DynamicRangeOptimizer         MakerNoteTag = 0xb025 // DynamicRangeOptimizer (int32u)
	ImageStabilization            MakerNoteTag = 0xb026 // ImageStabilization (int32u)
	LensType                      MakerNoteTag = 0xb027 // LensType (int32u)
	MinoltaMakerNote              MakerNoteTag = 0xb028 // MinoltaMakerNote (sub-dir)
	ColorMode                     MakerNoteTag = 0xb029 // ColorMode (int32u)
	LensSpec                      MakerNoteTag = 0xb02a // LensSpec (int8u[8])
	FullImageSize                 MakerNoteTag = 0xb02b // FullImageSize (int32u[2])
	PreviewImageSize              MakerNoteTag = 0xb02c // PreviewImageSize (int32u[2])
	Macro                         MakerNoteTag = 0xb040 // Macro (int16u)
	ExposureMode                  MakerNoteTag = 0xb041 // ExposureMode (int16u)
	FocusMode0xB042               MakerNoteTag = 0xb042 // FocusMode (int16u)
	AFAreaMode                    MakerNoteTag = 0xb043 // AFAreaMode (int16u)
	AFIlluminator                 MakerNoteTag = 0xb044 // AFIlluminator (int16u)
	JPEGQuality                   MakerNoteTag = 0xb047 // JPEGQuality (int16u)
	FlashLevel                    MakerNoteTag = 0xb048 // FlashLevel (int16s)
	ReleaseMode                   MakerNoteTag = 0xb049 // ReleaseMode (int16u)
	SequenceNumber                MakerNoteTag = 0xb04a // SequenceNumber (int16u)
	AntiBlur                      MakerNoteTag = 0xb04b // Anti-Blur (int16u)
	FocusMode0xB04E               MakerNoteTag = 0xb04e // FocusMode (int16u)
	DynamicRangeOptimizer0xB04F   MakerNoteTag = 0xb04f // DynamicRangeOptimizer (int16u)
	HighISONoiseReduction2        MakerNoteTag = 0xb050 // HighISONoiseReduction2 (int16u)
	IntelligentAuto               MakerNoteTag = 0xb052 // IntelligentAuto (int16u)
	WhiteBalance0xB054            MakerNoteTag = 0xb054 // WhiteBalance (int16u)
)
