// Code generated by "stringer -type=SonyCameraModel -linecomment -output=/Volumes/EOBlue/code/go/imagemeta/meta/exif/makernote/sony/models_string.go /Volumes/EOBlue/code/go/imagemeta/meta/exif/makernote/sony/models.go"; DO NOT EDIT.

package sony

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[SonyCameraUnknown-0]
	_ = x[SonyCameraDSCR1-2]
	_ = x[SonyCameraDSLRA100-256]
	_ = x[SonyCameraDSLRA900-257]
	_ = x[SonyCameraDSLRA700-258]
	_ = x[SonyCameraDSLRA200-259]
	_ = x[SonyCameraDSLRA350-260]
	_ = x[SonyCameraDSLRA300-261]
	_ = x[SonyCameraDSLRA900C-262]
	_ = x[SonyCameraDSLRA380-263]
	_ = x[SonyCameraDSLRA330-264]
	_ = x[SonyCameraDSLRA230-265]
	_ = x[SonyCameraDSLRA290-266]
	_ = x[SonyCameraDSLRA850-269]
	_ = x[SonyCameraDSLRA850C-270]
	_ = x[SonyCameraDSLRA550-273]
	_ = x[SonyCameraDSLRA500-274]
	_ = x[SonyCameraDSLRA450-275]
	_ = x[SonyCameraNEX5-278]
	_ = x[SonyCameraNEX3-279]
	_ = x[SonyCameraSLTA33-280]
	_ = x[SonyCameraSLTA55-281]
	_ = x[SonyCameraDSLRA560-282]
	_ = x[SonyCameraDSLRA580-283]
	_ = x[SonyCameraNEXC3-284]
	_ = x[SonyCameraSLTA35-285]
	_ = x[SonyCameraSLTA65-286]
	_ = x[SonyCameraSLTA77-287]
	_ = x[SonyCameraNEX5N-288]
	_ = x[SonyCameraNEX7-289]
	_ = x[SonyCameraNEXVG20E-290]
	_ = x[SonyCameraSLTA37-291]
	_ = x[SonyCameraSLTA57-292]
	_ = x[SonyCameraNEXF3-293]
	_ = x[SonyCameraSLTA99-294]
	_ = x[SonyCameraNEX6-295]
	_ = x[SonyCameraNEX5R-296]
	_ = x[SonyCameraDSCRX100-297]
	_ = x[SonyCameraDSCRX1-298]
	_ = x[SonyCameraNEXVG900-299]
	_ = x[SonyCameraNEXVG30E-300]
	_ = x[SonyCameraILCE3000-302]
	_ = x[SonyCameraSLTA58-303]
	_ = x[SonyCameraNEX3N-305]
	_ = x[SonyCameraILCE7-306]
	_ = x[SonyCameraNEX5T-307]
	_ = x[SonyCameraDSCRX100M2-308]
	_ = x[SonyCameraDSCRX10-309]
	_ = x[SonyCameraDSCRX1R-310]
	_ = x[SonyCameraILCE7R-311]
	_ = x[SonyCameraILCE6000-312]
	_ = x[SonyCameraILCE5000-313]
	_ = x[SonyCameraDSCRX100M3-317]
	_ = x[SonyCameraILCE7S-318]
	_ = x[SonyCameraILCA77M2-319]
	_ = x[SonyCameraILCE5100-339]
	_ = x[SonyCameraILCE7M2-340]
	_ = x[SonyCameraDSCRX100M4-341]
	_ = x[SonyCameraDSCRX10M2-342]
	_ = x[SonyCameraDSCRX1RM2-344]
	_ = x[SonyCameraILCEQX1-346]
	_ = x[SonyCameraILCE7RM2-347]
	_ = x[SonyCameraILCE7SM2-350]
	_ = x[SonyCameraILCA68-353]
	_ = x[SonyCameraILCA99M2-354]
	_ = x[SonyCameraDSCRX10M3-355]
	_ = x[SonyCameraDSCRX100M5-356]
	_ = x[SonyCameraILCE6300-357]
	_ = x[SonyCameraILCE9-358]
	_ = x[SonyCameraILCE6500-360]
	_ = x[SonyCameraILCE7RM3-362]
	_ = x[SonyCameraILCE7M3-363]
	_ = x[SonyCameraDSCRX0-364]
	_ = x[SonyCameraDSCRX10M4-365]
	_ = x[SonyCameraDSCRX100M6-366]
	_ = x[SonyCameraDSCHX99-367]
	_ = x[SonyCameraDSCRX100M5A-369]
	_ = x[SonyCameraILCE6400-371]
	_ = x[SonyCameraDSCRX0M2-372]
	_ = x[SonyCameraDSCHX95-373]
	_ = x[SonyCameraDSCRX100M7-374]
	_ = x[SonyCameraILCE7RM4-375]
	_ = x[SonyCameraILCE9M2-376]
	_ = x[SonyCameraILCE6600-378]
	_ = x[SonyCameraILCE6100-379]
	_ = x[SonyCameraZV1-380]
	_ = x[SonyCameraILCE7C-381]
	_ = x[SonyCameraZVE10-382]
	_ = x[SonyCameraILCE7SM3-383]
	_ = x[SonyCameraILCE1-384]
	_ = x[SonyCameraILMEFX3-385]
	_ = x[SonyCameraILCE7RM3A-386]
	_ = x[SonyCameraILCE7RM4A-387]
	_ = x[SonyCameraILCE7M4-388]
	_ = x[SonyCameraZV1F-389]
	_ = x[SonyCameraILCE7RM5-390]
	_ = x[SonyCameraILMEFX30-391]
	_ = x[SonyCameraILCE9M3-392]
	_ = x[SonyCameraZVE1-393]
	_ = x[SonyCameraILCE6700-394]
	_ = x[SonyCameraZV1M2-395]
	_ = x[SonyCameraILCE7CR-396]
	_ = x[SonyCameraILCE7CM2-397]
	_ = x[SonyCameraILXLR1-398]
	_ = x[SonyCameraZVE10M2-399]
	_ = x[SonyCameraILCE1M2-400]
	_ = x[SonyCameraDSCRX1RM3-401]
	_ = x[SonyCameraILCE6400A-402]
	_ = x[SonyCameraILCE6100A-403]
	_ = x[SonyCameraDSCRX100M7A-404]
	_ = x[SonyCameraILMEFX2-406]
	_ = x[SonyCameraILCE7M5-407]
	_ = x[SonyCameraZV1A-408]
}

const _SonyCameraModel_name = "UnknownDSC-R1DSLR-A100DSLR-A900DSLR-A700DSLR-A200DSLR-A350DSLR-A300DSLR-A900 (APS-C mode)DSLR-A380/A390DSLR-A330DSLR-A230DSLR-A290DSLR-A850DSLR-A850 (APS-C mode)DSLR-A550DSLR-A500DSLR-A450NEX-5NEX-3SLT-A33SLT-A55/SLT-A55VDSLR-A560DSLR-A580NEX-C3SLT-A35SLT-A65/SLT-A65VSLT-A77/SLT-A77VNEX-5NNEX-7NEX-VG20ESLT-A37SLT-A57NEX-F3SLT-A99/SLT-A99VNEX-6NEX-5RDSC-RX100DSC-RX1NEX-VG900NEX-VG30EILCE-3000/ILCE-3500SLT-A58NEX-3NILCE-7NEX-5TDSC-RX100M2DSC-RX10DSC-RX1RILCE-7RILCE-6000ILCE-5000DSC-RX100M3ILCE-7SILCA-77M2ILCE-5100ILCE-7M2DSC-RX100M4DSC-RX10M2DSC-RX1RM2ILCE-QX1ILCE-7RM2ILCE-7SM2ILCA-68ILCA-99M2DSC-RX10M3DSC-RX100M5ILCE-6300ILCE-9ILCE-6500ILCE-7RM3ILCE-7M3DSC-RX0DSC-RX10M4DSC-RX100M6DSC-HX99DSC-RX100M5AILCE-6400DSC-RX0M2DSC-HX95DSC-RX100M7ILCE-7RM4ILCE-9M2ILCE-6600ILCE-6100ZV-1ILCE-7CZV-E10ILCE-7SM3ILCE-1ILME-FX3ILCE-7RM3AILCE-7RM4AILCE-7M4ZV-1FILCE-7RM5ILME-FX30ILCE-9M3ZV-E1ILCE-6700ZV-1M2ILCE-7CRILCE-7CM2ILX-LR1ZV-E10M2ILCE-1M2DSC-RX1RM3ILCE-6400AILCE-6100ADSC-RX100M7AILME-FX2ILCE-7M5ZV-1A"

var _SonyCameraModel_map = map[SonyCameraModel]string{
	0:   _SonyCameraModel_name[0:7],
	2:   _SonyCameraModel_name[7:13],
	256: _SonyCameraModel_name[13:22],
	257: _SonyCameraModel_name[22:31],
	258: _SonyCameraModel_name[31:40],
	259: _SonyCameraModel_name[40:49],
	260: _SonyCameraModel_name[49:58],
	261: _SonyCameraModel_name[58:67],
	262: _SonyCameraModel_name[67:89],
	263: _SonyCameraModel_name[89:103],
	264: _SonyCameraModel_name[103:112],
	265: _SonyCameraModel_name[112:121],
	266: _SonyCameraModel_name[121:130],
	269: _SonyCameraModel_name[130:139],
	270: _SonyCameraModel_name[139:161],
	273: _SonyCameraModel_name[161:170],
	274: _SonyCameraModel_name[170:179],
	275: _SonyCameraModel_name[179:188],
	278: _SonyCameraModel_name[188:193],
	279: _SonyCameraModel_name[193:198],
	280: _SonyCameraModel_name[198:205],
	281: _SonyCameraModel_name[205:221],
	282: _SonyCameraModel_name[221:230],
	283: _SonyCameraModel_name[230:239],
	284: _SonyCameraModel_name[239:245],
	285: _SonyCameraModel_name[245:252],
	286: _SonyCameraModel_name[252:268],
	287: _SonyCameraModel_name[268:284],
	288: _SonyCameraModel_name[284:290],
	289: _SonyCameraModel_name[290:295],
	290: _SonyCameraModel_name[295:304],
	291: _SonyCameraModel_name[304:311],
	292: _SonyCameraModel_name[311:318],
	293: _SonyCameraModel_name[318:324],
	294: _SonyCameraModel_name[324:340],
	295: _SonyCameraModel_name[340:345],
	296: _SonyCameraModel_name[345:351],
	297: _SonyCameraModel_name[351:360],
	298: _SonyCameraModel_name[360:367],
	299: _SonyCameraModel_name[367:376],
	300: _SonyCameraModel_name[376:385],
	302: _SonyCameraModel_name[385:404],
	303: _SonyCameraModel_name[404:411],
	305: _SonyCameraModel_name[411:417],
	306: _SonyCameraModel_name[417:423],
	307: _SonyCameraModel_name[423:429],
	308: _SonyCameraModel_name[429:440],
	309: _SonyCameraModel_name[440:448],
	310: _SonyCameraModel_name[448:456],
	311: _SonyCameraModel_name[456:463],
	312: _SonyCameraModel_name[463:472],
	313: _SonyCameraModel_name[472:481],
	317: _SonyCameraModel_name[481:492],
	318: _SonyCameraModel_name[492:499],
	319: _SonyCameraModel_name[499:508],
	339: _SonyCameraModel_name[508:517],
	340: _SonyCameraModel_name[517:525],
	341: _SonyCameraModel_name[525:536],
	342: _SonyCameraModel_name[536:546],
	344: _SonyCameraModel_name[546:556],
	346: _SonyCameraModel_name[556:564],
	347: _SonyCameraModel_name[564:573],
	350: _SonyCameraModel_name[573:582],
	353: _SonyCameraModel_name[582:589],
	354: _SonyCameraModel_name[589:598],
	355: _SonyCameraModel_name[598:608],
	356: _SonyCameraModel_name[608:619],
	357: _SonyCameraModel_name[619:628],
	358: _SonyCameraModel_name[628:634],
	360: _SonyCameraModel_name[634:643],
	362: _SonyCameraModel_name[643:652],
	363: _SonyCameraModel_name[652:660],
	364: _SonyCameraModel_name[660:667],
	365: _SonyCameraModel_name[667:677],
	366: _SonyCameraModel_name[677:688],
	367: _SonyCameraModel_name[688:696],
	369: _SonyCameraModel_name[696:708],
	371: _SonyCameraModel_name[708:717],
	372: _SonyCameraModel_name[717:726],
	373: _SonyCameraModel_name[726:734],
	374: _SonyCameraModel_name[734:745],
	375: _SonyCameraModel_name[745:754],
	376: _SonyCameraModel_name[754:762],
	378: _SonyCameraModel_name[762:771],
	379: _SonyCameraModel_name[771:780],
	380: _SonyCameraModel_name[780:784],
	381: _SonyCameraModel_name[784:791],
	382: _SonyCameraModel_name[791:797],
	383: _SonyCameraModel_name[797:806],
	384: _SonyCameraModel_name[806:812],
	385: _SonyCameraModel_name[812:820],
	386: _SonyCameraModel_name[820:830],
	387: _SonyCameraModel_name[830:840],
	388: _SonyCameraModel_name[840:848],
	389: _SonyCameraModel_name[848:853],
	390: _SonyCameraModel_name[853:862],
	391: _SonyCameraModel_name[862:871],
	392: _SonyCameraModel_name[871:879],
	393: _SonyCameraModel_name[879:884],
	394: _SonyCameraModel_name[884:893],
	395: _SonyCameraModel_name[893:899],
	396: _SonyCameraModel_name[899:907],
	397: _SonyCameraModel_name[907:916],
	398: _SonyCameraModel_name[916:923],
	399: _SonyCameraModel_name[923:931],
	400: _SonyCameraModel_name[931:939],
	401: _SonyCameraModel_name[939:949],
	402: _SonyCameraModel_name[949:959],
	403: _SonyCameraModel_name[959:969],
	404: _SonyCameraModel_name[969:981],
	406: _SonyCameraModel_name[981:989],
	407: _SonyCameraModel_name[989:997],
	408: _SonyCameraModel_name[997:1002],
}

func (i SonyCameraModel) String() string {
	if str, ok := _SonyCameraModel_map[i]; ok {
		return str
	}
	return "SonyCameraModel(" + strconv.FormatInt(int64(i), 10) + ")"
}
