// Code generated by "stringer -type=WhiteBalanceValue,WhiteBalance0xB054Value,QualityValue,SceneModeValue,DynamicRangeOptimizerValue,FocusModeValue,FocusMode0xB042Value,AFAreaModeSettingValue,MeteringModeValue,FlashModeValue,ReleaseModeValue,PictureEffectValue,CreativeStyleValue,LongExposureNoiseReductionValue,HighISONoiseReductionValue,AntiBlurValue,IntelligentAutoValue,ExposureModeValue,ColorModeValue,AFAreaModeValue,ZoneMatchingValue,ImageStabilizationValue,SoftSkinEffectValue,MacroValue,AFIlluminatorValue,JPEGQualityValue,RAWFileTypeValue,PrioritySetInAWBValue,FlashActionValue,AFTrackingValue,MultiFrameNREffectValue,HDRValue -linecomment -output=sony_string.go"; DO NOT EDIT.

package sony

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[WBAuto-0]
	_ = x[WBColorTemp-1]
	_ = x[WBDaylight-16]
	_ = x[WBCloudy-32]
	_ = x[WBShade-48]
	_ = x[WBTungsten-64]
	_ = x[WBFlash-80]
	_ = x[WBFluorescent-96]
	_ = x[WBCustom-112]
	_ = x[WBUnderwater-128]
}

const (
	_WhiteBalanceValue_name_0 = "AutoColor Temperature/Color Filter"
	_WhiteBalanceValue_name_1 = "Daylight"
	_WhiteBalanceValue_name_2 = "Cloudy"
	_WhiteBalanceValue_name_3 = "Shade"
	_WhiteBalanceValue_name_4 = "Tungsten"
	_WhiteBalanceValue_name_5 = "Flash"
	_WhiteBalanceValue_name_6 = "Fluorescent"
	_WhiteBalanceValue_name_7 = "Custom"
	_WhiteBalanceValue_name_8 = "Underwater"
)

var (
	_WhiteBalanceValue_index_0 = [...]uint8{0, 4, 34}
)

func (i WhiteBalanceValue) String() string {
	switch {
	case i <= 1:
		return _WhiteBalanceValue_name_0[_WhiteBalanceValue_index_0[i]:_WhiteBalanceValue_index_0[i+1]]
	case i == 16:
		return _WhiteBalanceValue_name_1
	case i == 32:
		return _WhiteBalanceValue_name_2
	case i == 48:
		return _WhiteBalanceValue_name_3
	case i == 64:
		return _WhiteBalanceValue_name_4
	case i == 80:
		return _WhiteBalanceValue_name_5
	case i == 96:
		return _WhiteBalanceValue_name_6
	case i == 112:
		return _WhiteBalanceValue_name_7
	case i == 128:
		return _WhiteBalanceValue_name_8
	default:
		return "WhiteBalanceValue(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[WB54Auto-0]
	_ = x[WB54Custom-4]
	_ = x[WB54Daylight-5]
	_ = x[WB54Cloudy-6]
	_ = x[WB54CoolWhiteFluor-7]
	_ = x[WB54DayWhiteFluor-8]
	_ = x[WB54DaylightFluor-9]
	_ = x[WB54Incandescent2-10]
	_ = x[WB54WarmWhiteFluor-11]
	_ = x[WB54Incandescent-14]
	_ = x[WB54Flash-15]
	_ = x[WB54Underwater1-17]
	_ = x[WB54Underwater2-18]
}

const (
	_WhiteBalance0xB054Value_name_0 = "Auto"
	_WhiteBalance0xB054Value_name_1 = "CustomDaylightCloudyCool White FluorescentDay White FluorescentDaylight FluorescentIncandescent2Warm White Fluorescent"
	_WhiteBalance0xB054Value_name_2 = "IncandescentFlash"
	_WhiteBalance0xB054Value_name_3 = "Underwater 1 (Blue Water)Underwater 2 (Green Water)"
)

var (
	_WhiteBalance0xB054Value_index_1 = [...]uint8{0, 6, 14, 20, 42, 63, 83, 96, 118}
	_WhiteBalance0xB054Value_index_2 = [...]uint8{0, 12, 17}
	_WhiteBalance0xB054Value_index_3 = [...]uint8{0, 25, 51}
)

func (i WhiteBalance0xB054Value) String() string {
	switch {
	case i == 0:
		return _WhiteBalance0xB054Value_name_0
	case 4 <= i && i <= 11:
		i -= 4
		return _WhiteBalance0xB054Value_name_1[_WhiteBalance0xB054Value_index_1[i]:_WhiteBalance0xB054Value_index_1[i+1]]
	case 14 <= i && i <= 15:
		i -= 14
		return _WhiteBalance0xB054Value_name_2[_WhiteBalance0xB054Value_index_2[i]:_WhiteBalance0xB054Value_index_2[i+1]]
	case 17 <= i && i <= 18:
		i -= 17
		return _WhiteBalance0xB054Value_name_3[_WhiteBalance0xB054Value_index_3[i]:_WhiteBalance0xB054Value_index_3[i+1]]
	default:
		return "WhiteBalance0xB054Value(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[QualRAW-0]
	_ = x[QualSuperFine-1]
	_ = x[QualFine-2]
	_ = x[QualStandard-3]
	_ = x[QualEconomy-4]
	_ = x[QualExtraFine-5]
	_ = x[QualRAWJPEG-6]
	_ = x[QualCompressedRAW-7]
	_ = x[QualCompressedRAWJPEG-8]
	_ = x[QualLight-9]
	_ = x[QualNA-4294967295]
}

const (
	_QualityValue_name_0 = "RAWSuper FineFineStandardEconomyExtra FineRAW + JPEG/HEIFCompressed RAWCompressed RAW + JPEGLight"
	_QualityValue_name_1 = "n/a"
)

var (
	_QualityValue_index_0 = [...]uint8{0, 3, 13, 17, 25, 32, 42, 57, 71, 92, 97}
)

func (i QualityValue) String() string {
	switch {
	case i <= 9:
		return _QualityValue_name_0[_QualityValue_index_0[i]:_QualityValue_index_0[i+1]]
	case i == 4294967295:
		return _QualityValue_name_1
	default:
		return "QualityValue(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[SceneStandard-0]
	_ = x[ScenePortrait-1]
	_ = x[SceneText-2]
	_ = x[SceneNight-3]
	_ = x[SceneSunset-4]
	_ = x[SceneSports-5]
	_ = x[SceneLandscape-6]
	_ = x[SceneNightPortrait-7]
	_ = x[SceneMacro-8]
	_ = x[SceneSuperMacro-9]
	_ = x[SceneAuto-16]
	_ = x[SceneNightView-17]
	_ = x[SceneSweepPanorama-18]
	_ = x[SceneHandheldNight-19]
	_ = x[SceneAntiMotionBlur-20]
	_ = x[SceneContPriority-21]
	_ = x[SceneAutoPlus-22]
	_ = x[Scene3DSweepPan-23]
	_ = x[SceneSuperiorAuto-24]
	_ = x[SceneHighSensitivity-25]
	_ = x[SceneFireworks-26]
	_ = x[SceneFood-27]
	_ = x[ScenePet-28]
	_ = x[SceneHDR-33]
	_ = x[SceneNA-65535]
}

const (
	_SceneModeValue_name_0 = "StandardPortraitTextNight SceneSunsetSportsLandscapeNight PortraitMacroSuper Macro"
	_SceneModeValue_name_1 = "AutoNight View/PortraitSweep PanoramaHandheld Night ShotAnti Motion BlurCont. Priority AEAuto+3D Sweep PanoramaSuperior AutoHigh SensitivityFireworksFoodPet"
	_SceneModeValue_name_2 = "HDR"
	_SceneModeValue_name_3 = "n/a"
)

var (
	_SceneModeValue_index_0 = [...]uint8{0, 8, 16, 20, 31, 37, 43, 52, 66, 71, 82}
	_SceneModeValue_index_1 = [...]uint8{0, 4, 23, 37, 56, 72, 89, 94, 111, 124, 140, 149, 153, 156}
)

func (i SceneModeValue) String() string {
	switch {
	case i <= 9:
		return _SceneModeValue_name_0[_SceneModeValue_index_0[i]:_SceneModeValue_index_0[i+1]]
	case 16 <= i && i <= 28:
		i -= 16
		return _SceneModeValue_name_1[_SceneModeValue_index_1[i]:_SceneModeValue_index_1[i+1]]
	case i == 33:
		return _SceneModeValue_name_2
	case i == 65535:
		return _SceneModeValue_name_3
	default:
		return "SceneModeValue(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[DROOff-0]
	_ = x[DROStandard-1]
	_ = x[DROAdvancedAuto-2]
	_ = x[DROAuto-3]
	_ = x[DROAdvancedLv1-8]
	_ = x[DROAdvancedLv2-9]
	_ = x[DROAdvancedLv3-10]
	_ = x[DROAdvancedLv4-11]
	_ = x[DROAdvancedLv5-12]
	_ = x[DROLv1-16]
	_ = x[DROLv2-17]
	_ = x[DROLv3-18]
	_ = x[DROLv4-19]
	_ = x[DROLv5-20]
}

const (
	_DynamicRangeOptimizerValue_name_0 = "OffStandardAdvanced AutoAuto"
	_DynamicRangeOptimizerValue_name_1 = "Advanced Lv1Advanced Lv2Advanced Lv3Advanced Lv4Advanced Lv5"
	_DynamicRangeOptimizerValue_name_2 = "Lv1Lv2Lv3Lv4Lv5"
)

var (
	_DynamicRangeOptimizerValue_index_0 = [...]uint8{0, 3, 11, 24, 28}
	_DynamicRangeOptimizerValue_index_1 = [...]uint8{0, 12, 24, 36, 48, 60}
	_DynamicRangeOptimizerValue_index_2 = [...]uint8{0, 3, 6, 9, 12, 15}
)

func (i DynamicRangeOptimizerValue) String() string {
	switch {
	case i <= 3:
		return _DynamicRangeOptimizerValue_name_0[_DynamicRangeOptimizerValue_index_0[i]:_DynamicRangeOptimizerValue_index_0[i+1]]
	case 8 <= i && i <= 12:
		i -= 8
		return _DynamicRangeOptimizerValue_name_1[_DynamicRangeOptimizerValue_index_1[i]:_DynamicRangeOptimizerValue_index_1[i+1]]
	case 16 <= i && i <= 20:
		i -= 16
		return _DynamicRangeOptimizerValue_name_2[_DynamicRangeOptimizerValue_index_2[i]:_DynamicRangeOptimizerValue_index_2[i+1]]
	default:
		return "DynamicRangeOptimizerValue(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[FocusManual-0]
	_ = x[FocusAFS-2]
	_ = x[FocusAFC-3]
	_ = x[FocusAFA-4]
	_ = x[FocusDMF-6]
	_ = x[FocusAFD-7]
}

const (
	_FocusModeValue_name_0 = "Manual"
	_FocusModeValue_name_1 = "AF-SAF-CAF-A"
	_FocusModeValue_name_2 = "DMFAF-D"
)

var (
	_FocusModeValue_index_1 = [...]uint8{0, 4, 8, 12}
	_FocusModeValue_index_2 = [...]uint8{0, 3, 7}
)

func (i FocusModeValue) String() string {
	switch {
	case i == 0:
		return _FocusModeValue_name_0
	case 2 <= i && i <= 4:
		i -= 2
		return _FocusModeValue_name_1[_FocusModeValue_index_1[i]:_FocusModeValue_index_1[i+1]]
	case 6 <= i && i <= 7:
		i -= 6
		return _FocusModeValue_name_2[_FocusModeValue_index_2[i]:_FocusModeValue_index_2[i+1]]
	default:
		return "FocusModeValue(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[FocusB042AFS-1]
	_ = x[FocusB042AFC-2]
	_ = x[FocusB042Permanent-4]
	_ = x[FocusB042NA-65535]
}

const (
	_FocusMode0xB042Value_name_0 = "AF-SAF-C"
	_FocusMode0xB042Value_name_1 = "Permanent-AF"
	_FocusMode0xB042Value_name_2 = "n/a"
)

var (
	_FocusMode0xB042Value_index_0 = [...]uint8{0, 4, 8}
)

func (i FocusMode0xB042Value) String() string {
	switch {
	case 1 <= i && i <= 2:
		i -= 1
		return _FocusMode0xB042Value_name_0[_FocusMode0xB042Value_index_0[i]:_FocusMode0xB042Value_index_0[i+1]]
	case i == 4:
		return _FocusMode0xB042Value_name_1
	case i == 65535:
		return _FocusMode0xB042Value_name_2
	default:
		return "FocusMode0xB042Value(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[AFAWide-0]
	_ = x[AFCenter-1]
	_ = x[AFFlexSpot-3]
	_ = x[AFLocal-4]
	_ = x[AFZone-8]
	_ = x[AFSpot-9]
	_ = x[AFZoneNEX-11]
	_ = x[AFExpandFlexSpot-12]
	_ = x[AFCustomAFArea-13]
}

const (
	_AFAreaModeSettingValue_name_0 = "WideCenter"
	_AFAreaModeSettingValue_name_1 = "Flexible SpotLocal"
	_AFAreaModeSettingValue_name_2 = "ZoneSpot"
	_AFAreaModeSettingValue_name_3 = "Zone (NEX/ILCE)Expanded Flexible SpotCustom AF Area"
)

var (
	_AFAreaModeSettingValue_index_0 = [...]uint8{0, 4, 10}
	_AFAreaModeSettingValue_index_1 = [...]uint8{0, 13, 18}
	_AFAreaModeSettingValue_index_2 = [...]uint8{0, 4, 8}
	_AFAreaModeSettingValue_index_3 = [...]uint8{0, 15, 37, 51}
)

func (i AFAreaModeSettingValue) String() string {
	switch {
	case i <= 1:
		return _AFAreaModeSettingValue_name_0[_AFAreaModeSettingValue_index_0[i]:_AFAreaModeSettingValue_index_0[i+1]]
	case 3 <= i && i <= 4:
		i -= 3
		return _AFAreaModeSettingValue_name_1[_AFAreaModeSettingValue_index_1[i]:_AFAreaModeSettingValue_index_1[i+1]]
	case 8 <= i && i <= 9:
		i -= 8
		return _AFAreaModeSettingValue_name_2[_AFAreaModeSettingValue_index_2[i]:_AFAreaModeSettingValue_index_2[i+1]]
	case 11 <= i && i <= 13:
		i -= 11
		return _AFAreaModeSettingValue_name_3[_AFAreaModeSettingValue_index_3[i]:_AFAreaModeSettingValue_index_3[i+1]]
	default:
		return "AFAreaModeSettingValue(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[MeterMultiSegment-256]
	_ = x[MeterCenterWeighted-512]
	_ = x[MeterSpotStandard-769]
	_ = x[MeterSpotLarge-770]
	_ = x[MeterAverage-1024]
	_ = x[MeterHighlight-1280]
}

const (
	_MeteringModeValue_name_0 = "Multi-segment"
	_MeteringModeValue_name_1 = "Center-weighted average"
	_MeteringModeValue_name_2 = "Spot (Standard)Spot (Large)"
	_MeteringModeValue_name_3 = "Average"
	_MeteringModeValue_name_4 = "Highlight"
)

var (
	_MeteringModeValue_index_2 = [...]uint8{0, 15, 27}
)

func (i MeteringModeValue) String() string {
	switch {
	case i == 256:
		return _MeteringModeValue_name_0
	case i == 512:
		return _MeteringModeValue_name_1
	case 769 <= i && i <= 770:
		i -= 769
		return _MeteringModeValue_name_2[_MeteringModeValue_index_2[i]:_MeteringModeValue_index_2[i+1]]
	case i == 1024:
		return _MeteringModeValue_name_3
	case i == 1280:
		return _MeteringModeValue_name_4
	default:
		return "MeteringModeValue(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[FlashOff-1]
	_ = x[FlashAuto-16]
	_ = x[FlashFill-17]
	_ = x[FlashSlow-18]
	_ = x[FlashRear-19]
	_ = x[FlashWireless-20]
}

const (
	_FlashModeValue_name_0 = "Flash Off"
	_FlashModeValue_name_1 = "AutoflashFill-flashSlow SyncRear SyncWireless"
)

var (
	_FlashModeValue_index_1 = [...]uint8{0, 9, 19, 28, 37, 45}
)

func (i FlashModeValue) String() string {
	switch {
	case i == 1:
		return _FlashModeValue_name_0
	case 16 <= i && i <= 20:
		i -= 16
		return _FlashModeValue_name_1[_FlashModeValue_index_1[i]:_FlashModeValue_index_1[i+1]]
	default:
		return "FlashModeValue(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ReleaseNormal-0]
	_ = x[ReleaseContinuous-2]
	_ = x[ReleaseExpBkt-5]
	_ = x[ReleaseWBBkt-6]
	_ = x[ReleaseDROBkt-8]
	_ = x[ReleaseNA-65535]
}

const (
	_ReleaseModeValue_name_0 = "Normal"
	_ReleaseModeValue_name_1 = "Continuous"
	_ReleaseModeValue_name_2 = "Exposure BracketingWhite Balance Bracketing"
	_ReleaseModeValue_name_3 = "DRO Bracketing"
	_ReleaseModeValue_name_4 = "n/a"
)

var (
	_ReleaseModeValue_index_2 = [...]uint8{0, 19, 43}
)

func (i ReleaseModeValue) String() string {
	switch {
	case i == 0:
		return _ReleaseModeValue_name_0
	case i == 2:
		return _ReleaseModeValue_name_1
	case 5 <= i && i <= 6:
		i -= 5
		return _ReleaseModeValue_name_2[_ReleaseModeValue_index_2[i]:_ReleaseModeValue_index_2[i+1]]
	case i == 8:
		return _ReleaseModeValue_name_3
	case i == 65535:
		return _ReleaseModeValue_name_4
	default:
		return "ReleaseModeValue(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[PEOff-0]
	_ = x[PEToyCamera-1]
	_ = x[PEPopColor-2]
	_ = x[PEPoster-3]
	_ = x[PEPosterBW-4]
	_ = x[PERetro-5]
	_ = x[PESoftHighKey-6]
	_ = x[PERed-7]
	_ = x[PEGreen-8]
	_ = x[PEBlue-9]
	_ = x[PEYellow-10]
	_ = x[PEHighContBW-13]
	_ = x[PEToyNormal-16]
	_ = x[PEToyCool-17]
	_ = x[PEToyWarm-18]
	_ = x[PEToyGreen-19]
	_ = x[PEToyMagenta-20]
	_ = x[PESoftLow-32]
	_ = x[PESoftFocus-33]
	_ = x[PESoftHigh-34]
	_ = x[PEMiniAuto-48]
	_ = x[PEMiniTop-49]
	_ = x[PEMiniMidH-50]
	_ = x[PEMiniBottom-51]
	_ = x[PEMiniLeft-52]
	_ = x[PEMiniMidV-53]
	_ = x[PEMiniRight-54]
	_ = x[PEHDRPaintLow-64]
	_ = x[PEHDRPaint-65]
	_ = x[PEHDRPaintHigh-66]
	_ = x[PERichTone-80]
	_ = x[PEWaterColor-97]
	_ = x[PEWaterColor2-98]
	_ = x[PEIllustLow-112]
	_ = x[PEIllustrate-113]
	_ = x[PEIllustHigh-114]
}

const (
	_PictureEffectValue_name_0 = "OffToy CameraPop ColorPosterizationPosterization B/WRetro PhotoSoft High KeyPartial Color (red)Partial Color (green)Partial Color (blue)Partial Color (yellow)"
	_PictureEffectValue_name_1 = "High Contrast Monochrome"
	_PictureEffectValue_name_2 = "Toy Camera (normal)Toy Camera (cool)Toy Camera (warm)Toy Camera (green)Toy Camera (magenta)"
	_PictureEffectValue_name_3 = "Soft Focus (low)Soft FocusSoft Focus (high)"
	_PictureEffectValue_name_4 = "Miniature (auto)Miniature (top)Miniature (middle horizontal)Miniature (bottom)Miniature (left)Miniature (middle vertical)Miniature (right)"
	_PictureEffectValue_name_5 = "HDR Painting (low)HDR PaintingHDR Painting (high)"
	_PictureEffectValue_name_6 = "Rich-tone Monochrome"
	_PictureEffectValue_name_7 = "Water ColorWater Color 2"
	_PictureEffectValue_name_8 = "Illustration (low)IllustrationIllustration (high)"
)

var (
	_PictureEffectValue_index_0 = [...]uint8{0, 3, 13, 22, 35, 52, 63, 76, 95, 116, 136, 158}
	_PictureEffectValue_index_2 = [...]uint8{0, 19, 36, 53, 71, 91}
	_PictureEffectValue_index_3 = [...]uint8{0, 16, 26, 43}
	_PictureEffectValue_index_4 = [...]uint8{0, 16, 31, 60, 78, 94, 121, 138}
	_PictureEffectValue_index_5 = [...]uint8{0, 18, 30, 49}
	_PictureEffectValue_index_7 = [...]uint8{0, 11, 24}
	_PictureEffectValue_index_8 = [...]uint8{0, 18, 30, 49}
)

func (i PictureEffectValue) String() string {
	switch {
	case i <= 10:
		return _PictureEffectValue_name_0[_PictureEffectValue_index_0[i]:_PictureEffectValue_index_0[i+1]]
	case i == 13:
		return _PictureEffectValue_name_1
	case 16 <= i && i <= 20:
		i -= 16
		return _PictureEffectValue_name_2[_PictureEffectValue_index_2[i]:_PictureEffectValue_index_2[i+1]]
	case 32 <= i && i <= 34:
		i -= 32
		return _PictureEffectValue_name_3[_PictureEffectValue_index_3[i]:_PictureEffectValue_index_3[i+1]]
	case 48 <= i && i <= 54:
		i -= 48
		return _PictureEffectValue_name_4[_PictureEffectValue_index_4[i]:_PictureEffectValue_index_4[i+1]]
	case 64 <= i && i <= 66:
		i -= 64
		return _PictureEffectValue_name_5[_PictureEffectValue_index_5[i]:_PictureEffectValue_index_5[i+1]]
	case i == 80:
		return _PictureEffectValue_name_6
	case 97 <= i && i <= 98:
		i -= 97
		return _PictureEffectValue_name_7[_PictureEffectValue_index_7[i]:_PictureEffectValue_index_7[i+1]]
	case 112 <= i && i <= 114:
		i -= 112
		return _PictureEffectValue_name_8[_PictureEffectValue_index_8[i]:_PictureEffectValue_index_8[i+1]]
	default:
		return "PictureEffectValue(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[CreativeStandard-0]
	_ = x[CreativeVivid-2]
	_ = x[CreativePortrait-3]
	_ = x[CreativeLandscape-4]
	_ = x[CreativeSunset-5]
	_ = x[CreativeNightView-6]
	_ = x[CreativeBAndW-8]
	_ = x[CreativeAdobeRGB-9]
	_ = x[CreativeNeutral-11]
	_ = x[CreativeClear-12]
	_ = x[CreativeDeep-13]
	_ = x[CreativeLight-14]
	_ = x[CreativeAutumnLeaves-15]
	_ = x[CreativeOff-255]
}

const (
	_CreativeStyleValue_name_0 = "Standard"
	_CreativeStyleValue_name_1 = "VividPortraitLandscapeSunsetNight View/Portrait"
	_CreativeStyleValue_name_2 = "B&WAdobe RGB"
	_CreativeStyleValue_name_3 = "NeutralClearDeepLightAutumn Leaves"
	_CreativeStyleValue_name_4 = "Off"
)

var (
	_CreativeStyleValue_index_1 = [...]uint8{0, 5, 13, 22, 28, 47}
	_CreativeStyleValue_index_2 = [...]uint8{0, 3, 12}
	_CreativeStyleValue_index_3 = [...]uint8{0, 7, 12, 16, 21, 34}
)

func (i CreativeStyleValue) String() string {
	switch {
	case i == 0:
		return _CreativeStyleValue_name_0
	case 2 <= i && i <= 6:
		i -= 2
		return _CreativeStyleValue_name_1[_CreativeStyleValue_index_1[i]:_CreativeStyleValue_index_1[i+1]]
	case 8 <= i && i <= 9:
		i -= 8
		return _CreativeStyleValue_name_2[_CreativeStyleValue_index_2[i]:_CreativeStyleValue_index_2[i+1]]
	case 11 <= i && i <= 15:
		i -= 11
		return _CreativeStyleValue_name_3[_CreativeStyleValue_index_3[i]:_CreativeStyleValue_index_3[i+1]]
	case i == 255:
		return _CreativeStyleValue_name_4
	default:
		return "CreativeStyleValue(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[LENROff-0]
	_ = x[LENROnUnused-1]
	_ = x[LENROnDarkSub-65537]
	_ = x[LENROff65535-4294901760]
	_ = x[LENROn65535-4294901761]
	_ = x[LENRNA-4294967295]
}

const (
	_LongExposureNoiseReductionValue_name_0 = "OffOn (unused)"
	_LongExposureNoiseReductionValue_name_1 = "On (dark subtracted)"
	_LongExposureNoiseReductionValue_name_2 = "Off (65535)On (65535)"
	_LongExposureNoiseReductionValue_name_3 = "n/a"
)

var (
	_LongExposureNoiseReductionValue_index_0 = [...]uint8{0, 3, 14}
	_LongExposureNoiseReductionValue_index_2 = [...]uint8{0, 11, 21}
)

func (i LongExposureNoiseReductionValue) String() string {
	switch {
	case i <= 1:
		return _LongExposureNoiseReductionValue_name_0[_LongExposureNoiseReductionValue_index_0[i]:_LongExposureNoiseReductionValue_index_0[i+1]]
	case i == 65537:
		return _LongExposureNoiseReductionValue_name_1
	case 4294901760 <= i && i <= 4294901761:
		i -= 4294901760
		return _LongExposureNoiseReductionValue_name_2[_LongExposureNoiseReductionValue_index_2[i]:_LongExposureNoiseReductionValue_index_2[i+1]]
	case i == 4294967295:
		return _LongExposureNoiseReductionValue_name_3
	default:
		return "LongExposureNoiseReductionValue(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[HNROff-0]
	_ = x[HNRLow-1]
	_ = x[HNRNormal-2]
	_ = x[HNRHigh-3]
	_ = x[HNRAuto-256]
	_ = x[HNRNA-65535]
}

const (
	_HighISONoiseReductionValue_name_0 = "OffLowNormalHigh"
	_HighISONoiseReductionValue_name_1 = "Auto"
	_HighISONoiseReductionValue_name_2 = "n/a"
)

var (
	_HighISONoiseReductionValue_index_0 = [...]uint8{0, 3, 6, 12, 16}
)

func (i HighISONoiseReductionValue) String() string {
	switch {
	case i <= 3:
		return _HighISONoiseReductionValue_name_0[_HighISONoiseReductionValue_index_0[i]:_HighISONoiseReductionValue_index_0[i+1]]
	case i == 256:
		return _HighISONoiseReductionValue_name_1
	case i == 65535:
		return _HighISONoiseReductionValue_name_2
	default:
		return "HighISONoiseReductionValue(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[AntiBlurOff-0]
	_ = x[AntiBlurContinuous-1]
	_ = x[AntiBlurShooting-2]
	_ = x[AntiBlurNA-65535]
}

const (
	_AntiBlurValue_name_0 = "OffOn (Continuous)On (Shooting)"
	_AntiBlurValue_name_1 = "n/a"
)

var (
	_AntiBlurValue_index_0 = [...]uint8{0, 3, 18, 31}
)

func (i AntiBlurValue) String() string {
	switch {
	case i <= 2:
		return _AntiBlurValue_name_0[_AntiBlurValue_index_0[i]:_AntiBlurValue_index_0[i+1]]
	case i == 65535:
		return _AntiBlurValue_name_1
	default:
		return "AntiBlurValue(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[IAOff-0]
	_ = x[IAOn-1]
	_ = x[IAAdvanced-2]
}

const _IntelligentAutoValue_name = "OffOnAdvanced"

var _IntelligentAutoValue_index = [...]uint8{0, 3, 5, 13}

func (i IntelligentAutoValue) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_IntelligentAutoValue_index)-1 {
		return "IntelligentAutoValue(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _IntelligentAutoValue_name[_IntelligentAutoValue_index[idx]:_IntelligentAutoValue_index[idx+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ExpProgramAE-0]
	_ = x[ExpPortrait-1]
	_ = x[ExpBeach-2]
	_ = x[ExpSports-3]
	_ = x[ExpSnow-4]
	_ = x[ExpLandscape-5]
	_ = x[ExpAuto-6]
	_ = x[ExpApertureAE-7]
	_ = x[ExpShutterAE-8]
	_ = x[ExpNightScene-9]
	_ = x[ExpHiSpeedShutter-10]
	_ = x[ExpTwilightPortrait-11]
	_ = x[ExpSoftSnap-12]
	_ = x[ExpFireworks-13]
	_ = x[ExpSmileShutter-14]
	_ = x[ExpManual-15]
	_ = x[ExpHighSensitivity-18]
	_ = x[ExpMacro-19]
	_ = x[ExpAdvSports-20]
	_ = x[ExpUnderwater-29]
	_ = x[ExpFood-33]
	_ = x[ExpSweepPanorama-34]
	_ = x[ExpHandheldNight-35]
	_ = x[ExpAntiMotionBlur-36]
	_ = x[ExpPet-37]
	_ = x[ExpBacklightHDR-38]
	_ = x[ExpSuperiorAuto-39]
	_ = x[ExpBgDefocus-40]
	_ = x[ExpSoftSkin-41]
	_ = x[Exp3DImage-42]
	_ = x[ExpNA-65535]
}

const (
	_ExposureModeValue_name_0 = "Program AEPortraitBeachSportsSnowLandscapeAutoAperture-priority AEShutter speed priority AENight Scene / TwilightHi-Speed ShutterTwilight PortraitSoft Snap/PortraitFireworksSmile ShutterManual"
	_ExposureModeValue_name_1 = "High SensitivityMacroAdvanced Sports Shooting"
	_ExposureModeValue_name_2 = "Underwater"
	_ExposureModeValue_name_3 = "FoodSweep PanoramaHandheld Night ShotAnti Motion BlurPetBacklight Correction HDRSuperior AutoBackground DefocusSoft Skin3D Image"
	_ExposureModeValue_name_4 = "n/a"
)

var (
	_ExposureModeValue_index_0 = [...]uint8{0, 10, 18, 23, 29, 33, 42, 46, 66, 91, 113, 129, 146, 164, 173, 186, 192}
	_ExposureModeValue_index_1 = [...]uint8{0, 16, 21, 45}
	_ExposureModeValue_index_3 = [...]uint8{0, 4, 18, 37, 53, 56, 80, 93, 111, 120, 128}
)

func (i ExposureModeValue) String() string {
	switch {
	case i <= 15:
		return _ExposureModeValue_name_0[_ExposureModeValue_index_0[i]:_ExposureModeValue_index_0[i+1]]
	case 18 <= i && i <= 20:
		i -= 18
		return _ExposureModeValue_name_1[_ExposureModeValue_index_1[i]:_ExposureModeValue_index_1[i+1]]
	case i == 29:
		return _ExposureModeValue_name_2
	case 33 <= i && i <= 42:
		i -= 33
		return _ExposureModeValue_name_3[_ExposureModeValue_index_3[i]:_ExposureModeValue_index_3[i+1]]
	case i == 65535:
		return _ExposureModeValue_name_4
	default:
		return "ExposureModeValue(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[CMStandard-0]
	_ = x[CMVivid-1]
	_ = x[CMPortrait-2]
	_ = x[CMLandscape-3]
	_ = x[CMSunset-4]
	_ = x[CMNightView-5]
	_ = x[CMBAndW-6]
	_ = x[CMAdobeRGB-7]
	_ = x[CMNeutral-12]
	_ = x[CMClear-13]
	_ = x[CMDeep-14]
	_ = x[CMLight-15]
	_ = x[CMAutumnLeaves-16]
	_ = x[CMSepia-17]
	_ = x[CMFL-18]
	_ = x[CMVivid2-19]
	_ = x[CMIN-20]
	_ = x[CMSH-21]
	_ = x[CMFL2-22]
	_ = x[CMFL3-23]
	_ = x[CMNeutral100-100]
	_ = x[CMClear100-101]
	_ = x[CMDeep100-102]
	_ = x[CMLight100-103]
	_ = x[CMNightView100-104]
	_ = x[CMAutumnLeaves100-105]
	_ = x[CMOff-255]
	_ = x[CMNA-4294967295]
}

const (
	_ColorModeValue_name_0 = "StandardVividPortraitLandscapeSunsetNight View/PortraitB&WAdobe RGB"
	_ColorModeValue_name_1 = "NeutralClearDeepLightAutumn LeavesSepiaFLVivid 2INSHFL2FL3"
	_ColorModeValue_name_2 = "NeutralClearDeepLightNight ViewAutumn Leaves"
	_ColorModeValue_name_3 = "Off"
	_ColorModeValue_name_4 = "n/a"
)

var (
	_ColorModeValue_index_0 = [...]uint8{0, 8, 13, 21, 30, 36, 55, 58, 67}
	_ColorModeValue_index_1 = [...]uint8{0, 7, 12, 16, 21, 34, 39, 41, 48, 50, 52, 55, 58}
	_ColorModeValue_index_2 = [...]uint8{0, 7, 12, 16, 21, 31, 44}
)

func (i ColorModeValue) String() string {
	switch {
	case i <= 7:
		return _ColorModeValue_name_0[_ColorModeValue_index_0[i]:_ColorModeValue_index_0[i+1]]
	case 12 <= i && i <= 23:
		i -= 12
		return _ColorModeValue_name_1[_ColorModeValue_index_1[i]:_ColorModeValue_index_1[i+1]]
	case 100 <= i && i <= 105:
		i -= 100
		return _ColorModeValue_name_2[_ColorModeValue_index_2[i]:_ColorModeValue_index_2[i+1]]
	case i == 255:
		return _ColorModeValue_name_3
	case i == 4294967295:
		return _ColorModeValue_name_4
	default:
		return "ColorModeValue(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[AFAreaDefault-0]
	_ = x[AFAreaMulti-1]
	_ = x[AFAreaCenter-2]
	_ = x[AFAreaSpot-3]
	_ = x[AFAreaFlexSpot-4]
	_ = x[AFAreaTouch-6]
	_ = x[AFAreaTrack-14]
	_ = x[AFAreaFaceTrack-15]
	_ = x[AFAreaNA-65535]
}

const (
	_AFAreaModeValue_name_0 = "DefaultMultiCenterSpotFlexible Spot"
	_AFAreaModeValue_name_1 = "Touch"
	_AFAreaModeValue_name_2 = "TrackingFace Tracking"
	_AFAreaModeValue_name_3 = "n/a"
)

var (
	_AFAreaModeValue_index_0 = [...]uint8{0, 7, 12, 18, 22, 35}
	_AFAreaModeValue_index_2 = [...]uint8{0, 8, 21}
)

func (i AFAreaModeValue) String() string {
	switch {
	case i <= 4:
		return _AFAreaModeValue_name_0[_AFAreaModeValue_index_0[i]:_AFAreaModeValue_index_0[i+1]]
	case i == 6:
		return _AFAreaModeValue_name_1
	case 14 <= i && i <= 15:
		i -= 14
		return _AFAreaModeValue_name_2[_AFAreaModeValue_index_2[i]:_AFAreaModeValue_index_2[i+1]]
	case i == 65535:
		return _AFAreaModeValue_name_3
	default:
		return "AFAreaModeValue(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ZoneISO-0]
	_ = x[ZoneHigh-1]
	_ = x[ZoneLow-2]
}

const _ZoneMatchingValue_name = "ISO Setting UsedHigh KeyLow Key"

var _ZoneMatchingValue_index = [...]uint8{0, 16, 24, 31}

func (i ZoneMatchingValue) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_ZoneMatchingValue_index)-1 {
		return "ZoneMatchingValue(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ZoneMatchingValue_name[_ZoneMatchingValue_index[idx]:_ZoneMatchingValue_index[idx+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ISOff-0]
	_ = x[ISOn-1]
	_ = x[ISNA-4294967295]
}

const (
	_ImageStabilizationValue_name_0 = "OffOn"
	_ImageStabilizationValue_name_1 = "n/a"
)

var (
	_ImageStabilizationValue_index_0 = [...]uint8{0, 3, 5}
)

func (i ImageStabilizationValue) String() string {
	switch {
	case i <= 1:
		return _ImageStabilizationValue_name_0[_ImageStabilizationValue_index_0[i]:_ImageStabilizationValue_index_0[i+1]]
	case i == 4294967295:
		return _ImageStabilizationValue_name_1
	default:
		return "ImageStabilizationValue(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[SSOff-0]
	_ = x[SSLow-1]
	_ = x[SSMid-2]
	_ = x[SSHigh-3]
	_ = x[SSNA-4294967295]
}

const (
	_SoftSkinEffectValue_name_0 = "OffLowMidHigh"
	_SoftSkinEffectValue_name_1 = "n/a"
)

var (
	_SoftSkinEffectValue_index_0 = [...]uint8{0, 3, 6, 9, 13}
)

func (i SoftSkinEffectValue) String() string {
	switch {
	case i <= 3:
		return _SoftSkinEffectValue_name_0[_SoftSkinEffectValue_index_0[i]:_SoftSkinEffectValue_index_0[i+1]]
	case i == 4294967295:
		return _SoftSkinEffectValue_name_1
	default:
		return "SoftSkinEffectValue(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[MacroOff-0]
	_ = x[MacroOn-1]
	_ = x[MacroCloseFocus-2]
	_ = x[MacroNA-65535]
}

const (
	_MacroValue_name_0 = "OffOnClose Focus"
	_MacroValue_name_1 = "n/a"
)

var (
	_MacroValue_index_0 = [...]uint8{0, 3, 5, 16}
)

func (i MacroValue) String() string {
	switch {
	case i <= 2:
		return _MacroValue_name_0[_MacroValue_index_0[i]:_MacroValue_index_0[i+1]]
	case i == 65535:
		return _MacroValue_name_1
	default:
		return "MacroValue(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[AFIllumOff-0]
	_ = x[AFIllumAuto-1]
	_ = x[AFIllumNA-65535]
}

const (
	_AFIlluminatorValue_name_0 = "OffAuto"
	_AFIlluminatorValue_name_1 = "n/a"
)

var (
	_AFIlluminatorValue_index_0 = [...]uint8{0, 3, 7}
)

func (i AFIlluminatorValue) String() string {
	switch {
	case i <= 1:
		return _AFIlluminatorValue_name_0[_AFIlluminatorValue_index_0[i]:_AFIlluminatorValue_index_0[i+1]]
	case i == 65535:
		return _AFIlluminatorValue_name_1
	default:
		return "AFIlluminatorValue(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[JpegStandard-0]
	_ = x[JpegFine-1]
	_ = x[JpegExtraFine-2]
	_ = x[JpegNA-65535]
}

const (
	_JPEGQualityValue_name_0 = "StandardFineExtra Fine"
	_JPEGQualityValue_name_1 = "n/a"
)

var (
	_JPEGQualityValue_index_0 = [...]uint8{0, 8, 12, 22}
)

func (i JPEGQualityValue) String() string {
	switch {
	case i <= 2:
		return _JPEGQualityValue_name_0[_JPEGQualityValue_index_0[i]:_JPEGQualityValue_index_0[i+1]]
	case i == 65535:
		return _JPEGQualityValue_name_1
	default:
		return "JPEGQualityValue(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[RAWCompressed-0]
	_ = x[RAWUncompressed-1]
	_ = x[RAWLosslessComp-2]
	_ = x[RAWCompressed2-3]
	_ = x[RAWFileTypeNA-65535]
}

const (
	_RAWFileTypeValue_name_0 = "Compressed RAWUncompressed RAWLossless Compressed RAWCompressed RAW 2"
	_RAWFileTypeValue_name_1 = "n/a"
)

var (
	_RAWFileTypeValue_index_0 = [...]uint8{0, 14, 30, 53, 69}
)

func (i RAWFileTypeValue) String() string {
	switch {
	case i <= 3:
		return _RAWFileTypeValue_name_0[_RAWFileTypeValue_index_0[i]:_RAWFileTypeValue_index_0[i+1]]
	case i == 65535:
		return _RAWFileTypeValue_name_1
	default:
		return "RAWFileTypeValue(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[AWBPriorityStandard-0]
	_ = x[AWBPriorityAmbience-1]
	_ = x[AWBPriorityWhite-2]
}

const _PrioritySetInAWBValue_name = "StandardAmbienceWhite"

var _PrioritySetInAWBValue_index = [...]uint8{0, 8, 16, 21}

func (i PrioritySetInAWBValue) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_PrioritySetInAWBValue_index)-1 {
		return "PrioritySetInAWBValue(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _PrioritySetInAWBValue_name[_PrioritySetInAWBValue_index[idx]:_PrioritySetInAWBValue_index[idx+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[FlashDidNotFire-0]
	_ = x[FlashFired-1]
	_ = x[FlashExternal-2]
	_ = x[FlashWirelessCtrl-3]
}

const _FlashActionValue_name = "Did not fireFlash FiredExternal Flash FiredWireless Controlled Flash Fired"

var _FlashActionValue_index = [...]uint8{0, 12, 23, 43, 74}

func (i FlashActionValue) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_FlashActionValue_index)-1 {
		return "FlashActionValue(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _FlashActionValue_name[_FlashActionValue_index[idx]:_FlashActionValue_index[idx+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[AFTrackOff-0]
	_ = x[AFTrackFace-1]
	_ = x[AFTrackLockOn-2]
}

const _AFTrackingValue_name = "OffFace trackingLock On AF"

var _AFTrackingValue_index = [...]uint8{0, 3, 16, 26}

func (i AFTrackingValue) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_AFTrackingValue_index)-1 {
		return "AFTrackingValue(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _AFTrackingValue_name[_AFTrackingValue_index[idx]:_AFTrackingValue_index[idx+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[MFNRNormal-0]
	_ = x[MFNRHigh-1]
}

const _MultiFrameNREffectValue_name = "NormalHigh"

var _MultiFrameNREffectValue_index = [...]uint8{0, 6, 10}

func (i MultiFrameNREffectValue) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_MultiFrameNREffectValue_index)-1 {
		return "MultiFrameNREffectValue(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _MultiFrameNREffectValue_name[_MultiFrameNREffectValue_index[idx]:_MultiFrameNREffectValue_index[idx+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[HDROff-0]
	_ = x[HDRAuto-1]
	_ = x[HDR1_0EV-16]
	_ = x[HDR1_5EV-17]
	_ = x[HDR2_0EV-18]
	_ = x[HDR2_5EV-19]
	_ = x[HDR3_0EV-20]
	_ = x[HDR3_5EV-21]
	_ = x[HDR4_0EV-22]
	_ = x[HDR4_5EV-23]
	_ = x[HDR5_0EV-24]
	_ = x[HDR5_5EV-25]
	_ = x[HDR6_0EV-26]
}

const (
	_HDRValue_name_0 = "OffAuto"
	_HDRValue_name_1 = "1.0 EV1.5 EV2.0 EV2.5 EV3.0 EV3.5 EV4.0 EV4.5 EV5.0 EV5.5 EV6.0 EV"
)

var (
	_HDRValue_index_0 = [...]uint8{0, 3, 7}
	_HDRValue_index_1 = [...]uint8{0, 6, 12, 18, 24, 30, 36, 42, 48, 54, 60, 66}
)

func (i HDRValue) String() string {
	switch {
	case i <= 1:
		return _HDRValue_name_0[_HDRValue_index_0[i]:_HDRValue_index_0[i+1]]
	case 16 <= i && i <= 26:
		i -= 16
		return _HDRValue_name_1[_HDRValue_index_1[i]:_HDRValue_index_1[i+1]]
	default:
		return "HDRValue(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
