package sony

import "fmt"

var (
	_ fmt.Stringer = WhiteBalanceValue(0)
	_ fmt.Stringer = WhiteBalance0xB054Value(0)
	_ fmt.Stringer = QualityValue(0)
	_ fmt.Stringer = SceneModeValue(0)
	_ fmt.Stringer = DynamicRangeOptimizerValue(0)
	_ fmt.Stringer = FocusModeValue(0)
	_ fmt.Stringer = FocusMode0xB042Value(0)
	_ fmt.Stringer = AFAreaModeSettingValue(0)
	_ fmt.Stringer = MeteringModeValue(0)
	_ fmt.Stringer = FlashModeValue(0)
	_ fmt.Stringer = ReleaseModeValue(0)
	_ fmt.Stringer = PictureEffectValue(0)
	_ fmt.Stringer = CreativeStyleValue(0)
	_ fmt.Stringer = LongExposureNoiseReductionValue(0)
	_ fmt.Stringer = HighISONoiseReductionValue(0)
	_ fmt.Stringer = AntiBlurValue(0)
	_ fmt.Stringer = IntelligentAutoValue(0)
	_ fmt.Stringer = ExposureModeValue(0)
	_ fmt.Stringer = ColorModeValue(0)
	_ fmt.Stringer = AFAreaModeValue(0)
	_ fmt.Stringer = ZoneMatchingValue(0)
	_ fmt.Stringer = ImageStabilizationValue(0)
	_ fmt.Stringer = SoftSkinEffectValue(0)
	_ fmt.Stringer = MacroValue(0)
	_ fmt.Stringer = AFIlluminatorValue(0)
	_ fmt.Stringer = JPEGQualityValue(0)
	_ fmt.Stringer = RAWFileTypeValue(0)
	_ fmt.Stringer = PrioritySetInAWBValue(0)
	_ fmt.Stringer = FlashActionValue(0)
	_ fmt.Stringer = AFTrackingValue(0)
	_ fmt.Stringer = MultiFrameNREffectValue(0)
	_ fmt.Stringer = HDRValue(0)
)
