package xmp

// identifyName resolves XML local names to internal property names.
//
// Fast-path lowercases the token in-place, then uses a single string switch.
func identifyName(buf []byte) Name {
	toLowercaseBufInPlace(buf)
	switch string(buf) {
	case "h":
		return H
	case "w":
		return W
	case "x":
		return X
	case "y":
		return Y
	case "dc":
		return Dc
	case "li":
		return Li
	case "alt":
		return Alt
	case "bag":
		return Bag
	case "iso":
		return ISOSpeedRatings
	case "rdf":
		return RDF
	case "seq":
		return Seq
	case "xap":
		return Xap
	case "date":
		return Date
	case "good":
		return Good
	case "lang":
		return Lang
	case "lens":
		return Lens
	case "make":
		return Make
	case "mode":
		return Mode
	case "oecf":
		return OECF
	case "pick":
		return Pick
	case "type":
		return Type
	case "when":
		return When
	case "about":
		return About
	case "area":
		return AreaTag
	case "fired":
		return Fired
	case "flash":
		return FlashTag
	case "label":
		return Label
	case "model":
		return Model
	case "name":
		return NameTag
	case "role":
		return RoleTag
	case "stdim":
		return StDim
	case "title":
		return Title
	case "xmpdm":
		return XmpDM
	case "xmptk":
		return XMPToolkit
	case "unit":
		return Unit
	case "action":
		return Action
	case "format":
		return Format
	case "gpsdop":
		return GPSDOP
	case "lensid":
		return LensID
	case "rating":
		return Rating
	case "redhue":
		return HueAdjustmentRed
	case "return":
		return Return
	case "rights":
		return Rights
	case "source":
		return Source
	case "bluehue":
		return HueAdjustmentBlue
	case "changed":
		return Changed
	case "creator":
		return Creator
	case "fnumber":
		return FNumber
	case "history":
		return HistoryTag
	case "subject":
		return Subject
	case "xmpmeta":
		return XmpMeta
	case "contrast":
		return Contrast
	case "coverage":
		return Coverage
	case "copyright":
		return Copyright
	case "datetime":
		return DateTime
	case "firmware":
		return Firmware
	case "function":
		return Function
	case "gpsspeed":
		return GPSSpeed
	case "gpstrack":
		return GPSTrack
	case "greenhue":
		return HueAdjustmentGreen
	case "language":
		return Language
	case "lensinfo":
		return LensInfo
	case "oecfrows":
		return OECFRows
	case "relation":
		return Relation
	case "software":
		return Software
	case "tapename":
		return TapeName
	case "colormode":
		return ColorMode
	case "flashmode":
		return Mode
	case "gpsstatus":
		return GPSStatus
	case "lensmodel":
		return LensModel
	case "makernote":
		return MakerNote
	case "oecfnames":
		return OECFNames
	case "parsetype":
		return ParseType
	case "publisher":
		return Publisher
	case "scenetype":
		return SceneType
	case "sharpness":
		return Sharpness
	case "timevalue":
		return TimeValue
	case "tonecurve":
		return ToneCurve
	case "cfapattern":
		return CFAPattern
	case "colorspace":
		return ColorSpace
	case "createdate":
		return CreateDate
	case "documentid":
		return DocumentID
	case "extensions":
		return ExtensionsTag
	case "filesource":
		return FileSource
	case "flashfired":
		return Fired
	case "iccprofile":
		return ICCProfile
	case "identifier":
		return Identifier
	case "imagewidth":
		return ImageWidth
	case "instanceid":
		return InstanceID
	case "modifydate":
		return ModifyDate
	case "oecfvalues":
		return OECFValues
	case "parameters":
		return Parameters
	case "redeyemode":
		return RedEyeMode
	case "saturation":
		return Saturation
	case "subsectime":
		return SubsecTime
	case "xmptoolkit":
		return XMPToolkit
	case "alttapename":
		return AltTapeName
	case "alttimecode":
		return AltTimecode
	case "appliedtodimensions":
		return AppliedToDimensions
	case "compression":
		return Compression
	case "contributor":
		return Contributor
	case "creatortool":
		return CreatorTool
	case "datecreated":
		return DateCreated
	case "derivedfrom":
		return DerivedFrom
	case "description":
		return Description
	case "exifversion":
		return ExifVersion
	case "flashenergy":
		return FlashEnergy
	case "flashreturn":
		return Return
	case "focallength":
		return FocalLength
	case "gaincontrol":
		return GainControl
	case "gpsaltitude":
		return GPSAltitude
	case "gpsdatetime":
		return GPSTimeStamp
	case "gpslatitude":
		return GPSLatitude
	case "gpsmapdatum":
		return GPSMapDatum
	case "gpsspeedref":
		return GPSSpeedRef
	case "gpstrackref":
		return GPSTrackRef
	case "historywhen":
		return When
	case "imageheight":
		return ImageLength
	case "imagelength":
		return ImageLength
	case "imagenumber":
		return ImageNumber
	case "lightsource":
		return LightSource
	case "oecfcolumns":
		return OECFColumns
	case "orientation":
		return Orientation
	case "rawfilename":
		return RawFileName
	case "subjectarea":
		return SubjectArea
	case "temperature":
		return Temperature
	case "usercomment":
		return UserComment
	case "xresolution":
		return XResolution
	case "yresolution":
		return YResolution
	case "exposuremode":
		return ExposureMode
	case "exposuretime":
		return ExposureTime
	case "gpslongitude":
		return GPSLongitude
	case "gpstimestamp":
		return GPSTimeStamp
	case "gpsversionid":
		return GPSVersionID
	case "metadatadate":
		return MetadataDate
	case "meteringmode":
		return MeteringMode
	case "nativedigest":
		return NativeDigest
	case "serialnumber":
		return SerialNumber
	case "tonecurvered":
		return ToneCurveRed
	case "whitebalance":
		return WhiteBalance
	case "aperturevalue":
		return ApertureValue
	case "bitspersample":
		return BitsPerSample
	case "exposureindex":
		return ExposureIndex
	case "flashfunction":
		return Function
	case "gpssatellites":
		return GPSSatellites
	case "historyaction":
		return Action
	case "imageuniqueid":
		return ImageUniqueID
	case "redsaturation":
		return SaturationAdjustmentRed
	case "sensingmethod":
		return SensingMethod
	case "softwareagent":
		return SoftwareAgent
	case "starttimecode":
		return StartTimecode
	case "tonecurveblue":
		return ToneCurveBlue
	case "alreadyapplied":
		return AlreadyApplied
	case "bluesaturation":
		return SaturationAdjustmentBlue
	case "cfapatternrows":
		return CFAPatternRows
	case "customrendered":
		return CustomRendered
	case "exifimagewidth":
		return PixelXDimension
	case "gpsaltituderef":
		return GPSAltitudeRef
	case "gpsdestbearing":
		return GPSDestBearing
	case "gpsmeasuremode":
		return GPSMeasureMode
	case "historychanged":
		return Changed
	case "resolutionunit":
		return ResolutionUnit
	case "tonecurvegreen":
		return ToneCurveGreen
	case "videoframerate":
		return VideoFrameRate
	case "videoframesize":
		return VideoFrameSize
	case "brightnessvalue":
		return BrightnessValue
	case "cameraownername":
		return CameraOwnerName
	case "exifimageheight":
		return PixelYDimension
	case "exposureprogram":
		return ExposureProgram
	case "flashpixversion":
		return FlashpixVersion
	case "flashredeyemode":
		return RedEyeMode
	case "gpsdestdistance":
		return GPSDestDistance
	case "gpsdestlatitude":
		return GPSDestLatitude
	case "gpsdifferential":
		return GPSDifferential
	case "gpsimgdirection":
		return GPSImgDirection
	case "greensaturation":
		return SaturationAdjustmentGreen
	case "isospeedratings":
		return ISOSpeedRatings
	case "pixelxdimension":
		return PixelXDimension
	case "pixelydimension":
		return PixelYDimension
	case "samplesperpixel":
		return SamplesPerPixel
	case "sensitivitytype":
		return SensitivityType
	case "subjectdistance":
		return SubjectDistance
	case "subjectlocation":
		return SubjectLocation
	case "tonecurvepv2012":
		return ToneCurvePV2012
	case "videofieldorder":
		return VideoFieldOrder
	case "videopixeldepth":
		return VideoPixelDepth
	case "bodyserialnumber":
		return BodySerialNumber
	case "cfapatternvalues":
		return CFAPatternValues
	case "colortemperature":
		return Temperature
	case "datetimeoriginal":
		return DateTimeOriginal
	case "digitalzoomratio":
		return DigitalZoomRatio
	case "gpsdestlongitude":
		return GPSDestLongitude
	case "hueadjustmentred":
		return HueAdjustmentRed
	case "imagedescription":
		return ImageDescription
	case "legacyiptcdigest":
		return LegacyIPTCDigest
	case "lensserialnumber":
		return LensSerialNumber
	case "maxaperturevalue":
		return MaxApertureValue
	case "relatedsoundfile":
		return RelatedSoundFile
	case "scenecapturetype":
		return SceneCaptureType
	case "ycbcrpositioning":
		return YCbCrPositioning
	case "cfapatterncolumns":
		return CFAPatternColumns
	case "datetimedigitized":
		return DateTimeDigitized
	case "embeddedxmpdigest":
		return EmbeddedXMPDigest
	case "exposurebiasvalue":
		return ExposureBiasValue
	case "flashcompensation":
		return FlashCompensation
	case "gpsdestbearingref":
		return GPSDestBearingRef
	case "historyinstanceid":
		return InstanceID
	case "historyparameters":
		return Parameters
	case "hueadjustmentaqua":
		return HueAdjustmentAqua
	case "hueadjustmentblue":
		return HueAdjustmentBlue
	case "preservedfilename":
		return PreservedFileName
	case "shutterspeedvalue":
		return ShutterSpeedValue
	case "gpsareainformation":
		return GPSAreaInformation
	case "gpsdestdistanceref":
		return GPSDestDistanceRef
	case "gpsimgdirectionref":
		return GPSImgDirectionRef
	case "hueadjustmentgreen":
		return HueAdjustmentGreen
	case "originaldocumentid":
		return OriginalDocumentID
	case "subsectimeoriginal":
		return SubsecTimeOriginal
	case "tonecurvepv2012red":
		return ToneCurvePV2012Red
	case "gpsprocessingmethod":
		return GPSProcessingMethod
	case "hierarchicalsubject":
		return HierarchicalSubject
	case "hueadjustmentorange":
		return HueAdjustmentOrange
	case "hueadjustmentpurple":
		return HueAdjustmentPurple
	case "hueadjustmentyellow":
		return HueAdjustmentYellow
	case "planarconfiguration":
		return PlanarConfiguration
	case "sidecarforextension":
		return SidecarForExtension
	case "spectralsensitivity":
		return SpectralSensitivity
	case "subsectimedigitized":
		return SubsecTimeDigitized
	case "tonecurvepv2012blue":
		return ToneCurvePV2012Blue
	case "weightedflatsubject":
		return WeightedFlatSubject
	case "exposurecompensation":
		return ExposureBiasValue
	case "gpshpositioningerror":
		return GPSHPositioningError
	case "historysoftwareagent":
		return SoftwareAgent
	case "hueadjustmentmagenta":
		return HueAdjustmentMagenta
	case "subjectdistancerange":
		return SubjectDistanceRange
	case "tonecurvepv2012green":
		return ToneCurvePV2012Green
	case "derivedfromdocumentid":
		return DerivedFromDocumentID
	case "confidencelevel":
		return RegionExtensionsConfidenceLevel
	case "focallengthin35mmfilm":
		return FocalLengthIn35mmFilm
	case "focalplanexresolution":
		return FocalPlaneXResolution
	case "focalplaneyresolution":
		return FocalPlaneYResolution
	case "interopindex":
		return InteroperabilityIndex
	case "interoperabilityindex":
		return InteroperabilityIndex
	case "videopixelaspectratio":
		return VideoPixelAspectRatio
	case "compressedbitsperpixel":
		return CompressedBitsPerPixel
	case "luminanceadjustmentred":
		return LuminanceAdjustmentRed
	case "componentsconfiguration":
		return ComponentsConfiguration
	case "focallengthin35mmformat":
		return FocalLengthIn35mmFilm
	case "angleinforoll":
		return RegionExtensionsAngleInfoRoll
	case "angleinfoyaw":
		return RegionExtensionsAngleInfoYaw
	case "regionlist":
		return RegionListTag
	case "timestamp":
		return RegionExtensionsTimeStamp
	case "luminanceadjustmentaqua":
		return LuminanceAdjustmentAqua
	case "luminanceadjustmentblue":
		return LuminanceAdjustmentBlue
	case "opto-electricconvfactor":
		return OECF
	case "photographicsensitivity":
		return PhotographicSensitivity
	case "saturationadjustmentred":
		return SaturationAdjustmentRed
	case "approximatefocusdistance":
		return ApproximateFocusDistance
	case "devicesettingdescription":
		return DeviceSettingDescription
	case "focalplaneresolutionunit":
		return FocalPlaneResolutionUnit
	case "luminanceadjustmentgreen":
		return LuminanceAdjustmentGreen
	case "recommendedexposureindex":
		return RecommendedExposureIndex
	case "saturationadjustmentaqua":
		return SaturationAdjustmentAqua
	case "saturationadjustmentblue":
		return SaturationAdjustmentBlue
	case "spatialfrequencyresponse":
		return SpatialFrequencyResponse
	case "luminanceadjustmentorange":
		return LuminanceAdjustmentOrange
	case "luminanceadjustmentpurple":
		return LuminanceAdjustmentPurple
	case "luminanceadjustmentyellow":
		return LuminanceAdjustmentYellow
	case "photometricinterpretation":
		return PhotometricInterpretation
	case "saturationadjustmentgreen":
		return SaturationAdjustmentGreen
	case "luminanceadjustmentmagenta":
		return LuminanceAdjustmentMagenta
	case "saturationadjustmentorange":
		return SaturationAdjustmentOrange
	case "saturationadjustmentpurple":
		return SaturationAdjustmentPurple
	case "saturationadjustmentyellow":
		return SaturationAdjustmentYellow
	case "saturationadjustmentmagenta":
		return SaturationAdjustmentMagenta
	case "devicesettingdescriptionrows":
		return DeviceSettingDescriptionRows
	case "faceid":
		return RegionExtensionsFaceID
	case "regions":
		return RegionsTag
	case "spatialfrequencyresponserows":
		return SpatialFrequencyResponseRows
	case "derivedfromoriginaldocumentid":
		return DerivedFromOriginalDocumentID
	case "spatialfrequencyresponsenames":
		return SpatialFrequencyResponseNames
	case "spatialfrequencyresponsevalues":
		return SpatialFrequencyResponseValues
	case "devicesettingdescriptioncolumns":
		return DeviceSettingDescriptionColumns
	case "spatialfrequencyresponsecolumns":
		return SpatialFrequencyResponseColumns
	case "devicesettingdescriptionsettings":
		return DeviceSettingDescriptionSettings
	case "vignettecorrectionalreadyapplied":
		return VignetteCorrectionAlreadyApplied
	case "distortioncorrectionalreadyapplied":
		return DistortionCorrectionAlreadyApplied
	case "lateralchromaticaberrationcorrectionalreadyapplied":
		return LateralChromaticAberrationCorrectionAlreadyApplied
	case "autolateralca":
		return AutoLateralCA
	case "blacks2012":
		return Blacks2012
	case "cameraprofile":
		return CameraProfile
	case "cameraprofiledigest":
		return CameraProfileDigest
	case "clarity2012":
		return Clarity2012
	case "colornoisereduction":
		return ColorNoiseReduction
	case "colornoisereductiondetail":
		return ColorNoiseReductionDetail
	case "colornoisereductionsmoothness":
		return ColorNoiseReductionSmoothness
	case "contrast2012":
		return Contrast2012
	case "converttograyscale":
		return ConvertToGrayscale
	case "defringegreenamount":
		return DefringeGreenAmount
	case "defringegreenhuehi":
		return DefringeGreenHueHi
	case "defringegreenhuelo":
		return DefringeGreenHueLo
	case "defringepurpleamount":
		return DefringePurpleAmount
	case "defringepurplehuehi":
		return DefringePurpleHueHi
	case "defringepurplehuelo":
		return DefringePurpleHueLo
	case "dehaze":
		return Dehaze
	case "exposure2012":
		return Exposure2012
	case "grainamount":
		return GrainAmount
	case "grainfrequency":
		return GrainFrequency
	case "grainseed":
		return GrainSeed
	case "grainsize":
		return GrainSize
	case "hascrop":
		return HasCrop
	case "hassettings":
		return HasSettings
	case "highlights2012":
		return Highlights2012
	case "lensmanualdistortionamount":
		return LensManualDistortionAmount
	case "lensprofilechromaticaberrationscale":
		return LensProfileChromaticAberrationScale
	case "lensprofiledigest":
		return LensProfileDigest
	case "lensprofiledistortionscale":
		return LensProfileDistortionScale
	case "lensprofileenable":
		return LensProfileEnable
	case "lensprofilefilename":
		return LensProfileFilename
	case "lensprofilename":
		return LensProfileName
	case "lensprofilesetup":
		return LensProfileSetup
	case "lensprofilevignettingscale":
		return LensProfileVignettingScale
	case "lookname":
		return LookName
	case "luminancenoisereductioncontrast":
		return LuminanceNoiseReductionContrast
	case "luminancenoisereductiondetail":
		return LuminanceNoiseReductionDetail
	case "luminancesmoothing":
		return LuminanceSmoothing
	case "overridelookvignette":
		return OverrideLookVignette
	case "parametricdarks":
		return ParametricDarks
	case "parametrichighlights":
		return ParametricHighlights
	case "parametrichighlightsplit":
		return ParametricHighlightSplit
	case "parametriclights":
		return ParametricLights
	case "parametricmidtonesplit":
		return ParametricMidtoneSplit
	case "parametricshadowsplit":
		return ParametricShadowSplit
	case "parametricshadows":
		return ParametricShadows
	case "perspectiveaspect":
		return PerspectiveAspect
	case "perspectivehorizontal":
		return PerspectiveHorizontal
	case "perspectiverotate":
		return PerspectiveRotate
	case "perspectivescale":
		return PerspectiveScale
	case "perspectiveupright":
		return PerspectiveUpright
	case "perspectivevertical":
		return PerspectiveVertical
	case "perspectivex":
		return PerspectiveX
	case "perspectivey":
		return PerspectiveY
	case "postcropvignetteamount":
		return PostCropVignetteAmount
	case "postcropvignettefeather":
		return PostCropVignetteFeather
	case "postcropvignettehighlightcontrast":
		return PostCropVignetteHighlightContrast
	case "postcropvignettemidpoint":
		return PostCropVignetteMidpoint
	case "postcropvignetteroundness":
		return PostCropVignetteRoundness
	case "postcropvignettestyle":
		return PostCropVignetteStyle
	case "processversion":
		return ProcessVersion
	case "shadowtint":
		return ShadowTint
	case "shadows2012":
		return Shadows2012
	case "sharpendetail":
		return SharpenDetail
	case "sharpenedgemasking":
		return SharpenEdgeMasking
	case "sharpenradius":
		return SharpenRadius
	case "splittoningbalance":
		return SplitToningBalance
	case "splittoninghighlighthue":
		return SplitToningHighlightHue
	case "splittoninghighlightsaturation":
		return SplitToningHighlightSaturation
	case "splittoningshadowhue":
		return SplitToningShadowHue
	case "splittoningshadowsaturation":
		return SplitToningShadowSaturation
	case "tint":
		return Tint
	case "tonecurvename":
		return ToneCurveName
	case "tonecurvename2012":
		return ToneCurveName2012
	case "tonemapstrength":
		return ToneMapStrength
	case "uprightcentermode":
		return UprightCenterMode
	case "uprightcenternormx":
		return UprightCenterNormX
	case "uprightcenternormy":
		return UprightCenterNormY
	case "uprightfocallength35mm":
		return UprightFocalLength35mm
	case "uprightfocalmode":
		return UprightFocalMode
	case "uprightfoursegmentscount":
		return UprightFourSegmentsCount
	case "uprightpreview":
		return UprightPreview
	case "uprighttransformcount":
		return UprightTransformCount
	case "uprightversion":
		return UprightVersion
	case "version":
		return Version
	case "vibrance":
		return Vibrance
	case "vignetteamount":
		return VignetteAmount
	case "whites2012":
		return Whites2012
	case "derivedfrominstanceid":
		return DerivedFromInstanceID
	case "regionappliedtodimensionsh":
		return RegionAppliedToDimensionsH
	case "regionappliedtodimensionsunit":
		return RegionAppliedToDimensionsUnit
	case "regionappliedtodimensionsw":
		return RegionAppliedToDimensionsW
	case "regionareah":
		return RegionAreaH
	case "regionareaunit":
		return RegionAreaUnit
	case "regionareaw":
		return RegionAreaW
	case "regionareax":
		return RegionAreaX
	case "regionareay":
		return RegionAreaY
	case "regionextensionsangleinforoll":
		return RegionExtensionsAngleInfoRoll
	case "regionextensionsangleinfoyaw":
		return RegionExtensionsAngleInfoYaw
	case "regionextensionsconfidencelevel":
		return RegionExtensionsConfidenceLevel
	case "regionextensionsfaceid":
		return RegionExtensionsFaceID
	case "regionextensionstimestamp":
		return RegionExtensionsTimeStamp
	case "regiontype":
		return RegionTypeTag
	case "acceleration":
		return Acceleration
	case "ambienttemperature":
		return AmbientTemperature
	case "artist":
		return Artist
	case "cameraelevationangle":
		return CameraElevationAngle
	case "camerafirmware":
		return CameraFirmware
	case "compimageimagespersequence":
		return CompImageImagesPerSequence
	case "compimagemaxexposureall":
		return CompImageMaxExposureAll
	case "compimagemaxexposureused":
		return CompImageMaxExposureUsed
	case "compimageminexposureall":
		return CompImageMinExposureAll
	case "compimageminexposureused":
		return CompImageMinExposureUsed
	case "compimagenumsequences":
		return CompImageNumSequences
	case "compimagesumexposureall":
		return CompImageSumExposureAll
	case "compimagesumexposureused":
		return CompImageSumExposureUsed
	case "compimagetotalexposureperiod":
		return CompImageTotalExposurePeriod
	case "compimagevalues":
		return CompImageValues
	case "compositeimage":
		return CompositeImage
	case "compositeimagecount":
		return CompositeImageCount
	case "compositeimageexposuretimes":
		return CompositeImageExposureTimes
	case "gamma":
		return Gamma
	case "humidity":
		return Humidity
	case "isospeed":
		return ISOSpeed
	case "isospeedlatitudeyyy":
		return ISOSpeedLatitudeyyy
	case "isospeedlatitudezzz":
		return ISOSpeedLatitudezzz
	case "imageeditingsoftware":
		return ImageEditingSoftware
	case "imageeditor":
		return ImageEditor
	case "imagetitle":
		return ImageTitle
	case "lensmake":
		return LensMake
	case "metadataeditingsoftware":
		return MetadataEditingSoftware
	case "ownername":
		return OwnerName
	case "photographer":
		return Photographer
	case "pressure":
		return Pressure
	case "primarychromaticities":
		return PrimaryChromaticities
	case "rawdevelopingsoftware":
		return RAWDevelopingSoftware
	case "referenceblackwhite":
		return ReferenceBlackWhite
	case "standardoutputsensitivity":
		return StandardOutputSensitivity
	case "transferfunction":
		return TransferFunction
	case "waterdepth":
		return WaterDepth
	case "whitepoint":
		return WhitePoint
	case "ycbcrcoefficients":
		return YCbCrCoefficients
	case "ycbcrsubsampling":
		return YCbCrSubSampling
	default:
		return UnknownPropertyName
	}
}

// toLowercaseBufInPlace lowercases ASCII letters in buf in-place.
func toLowercaseBufInPlace(buf []byte) {
	for i := 0; i < len(buf); i++ {
		if buf[i] >= 'A' && buf[i] <= 'Z' {
			buf[i] |= 0x20
		}
	}
}
